/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import <thrift/TProtocol.h>
#import <thrift/TApplicationException.h>
#import <thrift/TProtocolException.h>
#import <thrift/TProtocolUtil.h>
#import <thrift/TProcessor.h>
#import <thrift/TObjective-C.h>
#import <thrift/TBase.h>

#import "shared.h"

@interface Event : NSObject <TBase, NSCoding> {
  NSString * __id;
  NSString * __name;
  NSMutableDictionary * __parameters;
  int64_t __startTime;
  int64_t __endTime;

  BOOL __id_isset;
  BOOL __name_isset;
  BOOL __parameters_isset;
  BOOL __startTime_isset;
  BOOL __endTime_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=id, setter=setId:) NSString * id;
@property (nonatomic, retain, getter=name, setter=setName:) NSString * name;
@property (nonatomic, retain, getter=parameters, setter=setParameters:) NSMutableDictionary * parameters;
@property (nonatomic, getter=startTime, setter=setStartTime:) int64_t startTime;
@property (nonatomic, getter=endTime, setter=setEndTime:) int64_t endTime;
#endif

- (id) init;
- (id) initWithId: (NSString *) id name: (NSString *) name parameters: (NSMutableDictionary *) parameters startTime: (int64_t) startTime endTime: (int64_t) endTime;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) id;
- (void) setId: (NSString *) id;
#endif
- (BOOL) idIsSet;

#if !__has_feature(objc_arc)
- (NSString *) name;
- (void) setName: (NSString *) name;
#endif
- (BOOL) nameIsSet;

#if !__has_feature(objc_arc)
- (NSMutableDictionary *) parameters;
- (void) setParameters: (NSMutableDictionary *) parameters;
#endif
- (BOOL) parametersIsSet;

#if !__has_feature(objc_arc)
- (int64_t) startTime;
- (void) setStartTime: (int64_t) startTime;
#endif
- (BOOL) startTimeIsSet;

#if !__has_feature(objc_arc)
- (int64_t) endTime;
- (void) setEndTime: (int64_t) endTime;
#endif
- (BOOL) endTimeIsSet;

@end

@interface Error : NSObject <TBase, NSCoding> {
  NSString * __id;
  int64_t __time;
  NSString * __message;
  NSMutableDictionary * __parameters;

  BOOL __id_isset;
  BOOL __time_isset;
  BOOL __message_isset;
  BOOL __parameters_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=id, setter=setId:) NSString * id;
@property (nonatomic, getter=time, setter=setTime:) int64_t time;
@property (nonatomic, retain, getter=message, setter=setMessage:) NSString * message;
@property (nonatomic, retain, getter=parameters, setter=setParameters:) NSMutableDictionary * parameters;
#endif

- (id) init;
- (id) initWithId: (NSString *) id time: (int64_t) time message: (NSString *) message parameters: (NSMutableDictionary *) parameters;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) id;
- (void) setId: (NSString *) id;
#endif
- (BOOL) idIsSet;

#if !__has_feature(objc_arc)
- (int64_t) time;
- (void) setTime: (int64_t) time;
#endif
- (BOOL) timeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) message;
- (void) setMessage: (NSString *) message;
#endif
- (BOOL) messageIsSet;

#if !__has_feature(objc_arc)
- (NSMutableDictionary *) parameters;
- (void) setParameters: (NSMutableDictionary *) parameters;
#endif
- (BOOL) parametersIsSet;

@end

@interface EventRecordFailedError : NSException <TBase, NSCoding> {
  NSString * __message;
  Event * __event;
  Error * __error;

  BOOL __message_isset;
  BOOL __event_isset;
  BOOL __error_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=message, setter=setMessage:) NSString * message;
@property (nonatomic, retain, getter=event, setter=setEvent:) Event * event;
@property (nonatomic, retain, getter=error, setter=setError:) Error * error;
#endif

- (id) init;
- (id) initWithMessage: (NSString *) message event: (Event *) event error: (Error *) error;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) message;
- (void) setMessage: (NSString *) message;
#endif
- (BOOL) messageIsSet;

#if !__has_feature(objc_arc)
- (Event *) event;
- (void) setEvent: (Event *) event;
#endif
- (BOOL) eventIsSet;

#if !__has_feature(objc_arc)
- (Error *) error;
- (void) setError: (Error *) error;
#endif
- (BOOL) errorIsSet;

@end

@protocol AnalyticsService <NSObject>
- (BOOL) isOptedIn: (AuthenticationToken *) token;  // throws TException
- (void) optOut: (AuthenticationToken *) token;  // throws TException
- (void) optIn: (AuthenticationToken *) token;  // throws TException
- (void) logEvent: (AuthenticationToken *) token event: (Event *) event;  // throws EventRecordFailedError *, TException
- (void) logError: (AuthenticationToken *) token error: (Error *) error;  // throws EventRecordFailedError *, TException
@end

@interface AnalyticsServiceClient : NSObject <AnalyticsService> {
  id <TProtocol> inProtocol;
  id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface AnalyticsServiceProcessor : NSObject <TProcessor> {
  id <AnalyticsService> mService;
  NSDictionary * mMethodMap;
}
- (id) initWithAnalyticsService: (id <AnalyticsService>) service;
- (id<AnalyticsService>) service;
@end

@interface analyticConstants : NSObject {
}
@end
