/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import <thrift/TProtocol.h>
#import <thrift/TApplicationException.h>
#import <thrift/TProtocolException.h>
#import <thrift/TProtocolUtil.h>
#import <thrift/TProcessor.h>
#import <thrift/TObjective-C.h>
#import <thrift/TBase.h>

#import "shared.h"

@interface CompanyAuthenticationResult : NSObject <TBase, NSCoding> {
  BOOL __success;
  NSString * __message;
  AuthenticationToken * __authenticationToken;
  NSString * __companyId;

  BOOL __success_isset;
  BOOL __message_isset;
  BOOL __authenticationToken_isset;
  BOOL __companyId_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=success, setter=setSuccess:) BOOL success;
@property (nonatomic, retain, getter=message, setter=setMessage:) NSString * message;
@property (nonatomic, retain, getter=authenticationToken, setter=setAuthenticationToken:) AuthenticationToken * authenticationToken;
@property (nonatomic, retain, getter=companyId, setter=setCompanyId:) NSString * companyId;
#endif

- (id) init;
- (id) initWithSuccess: (BOOL) success message: (NSString *) message authenticationToken: (AuthenticationToken *) authenticationToken companyId: (NSString *) companyId;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (BOOL) success;
- (void) setSuccess: (BOOL) success;
#endif
- (BOOL) successIsSet;

#if !__has_feature(objc_arc)
- (NSString *) message;
- (void) setMessage: (NSString *) message;
#endif
- (BOOL) messageIsSet;

#if !__has_feature(objc_arc)
- (AuthenticationToken) authenticationToken;
- (void) setAuthenticationToken: (AuthenticationToken) authenticationToken;
#endif
- (BOOL) authenticationTokenIsSet;

#if !__has_feature(objc_arc)
- (NSString *) companyId;
- (void) setCompanyId: (NSString *) companyId;
#endif
- (BOOL) companyIdIsSet;

@end

@interface UserAuthenticationResult : NSObject <TBase, NSCoding> {
  BOOL __success;
  NSString * __message;
  AuthenticationToken * __authenticationToken;
  NSString * __userPrincipal;

  BOOL __success_isset;
  BOOL __message_isset;
  BOOL __authenticationToken_isset;
  BOOL __userPrincipal_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=success, setter=setSuccess:) BOOL success;
@property (nonatomic, retain, getter=message, setter=setMessage:) NSString * message;
@property (nonatomic, retain, getter=authenticationToken, setter=setAuthenticationToken:) AuthenticationToken * authenticationToken;
@property (nonatomic, retain, getter=userPrincipal, setter=setUserPrincipal:) NSString * userPrincipal;
#endif

- (id) init;
- (id) initWithSuccess: (BOOL) success message: (NSString *) message authenticationToken: (AuthenticationToken *) authenticationToken userPrincipal: (NSString *) userPrincipal;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (BOOL) success;
- (void) setSuccess: (BOOL) success;
#endif
- (BOOL) successIsSet;

#if !__has_feature(objc_arc)
- (NSString *) message;
- (void) setMessage: (NSString *) message;
#endif
- (BOOL) messageIsSet;

#if !__has_feature(objc_arc)
- (AuthenticationToken) authenticationToken;
- (void) setAuthenticationToken: (AuthenticationToken) authenticationToken;
#endif
- (BOOL) authenticationTokenIsSet;

#if !__has_feature(objc_arc)
- (NSString *) userPrincipal;
- (void) setUserPrincipal: (NSString *) userPrincipal;
#endif
- (BOOL) userPrincipalIsSet;

@end

@interface DeviceAuthenticationResult : NSObject <TBase, NSCoding> {
  BOOL __success;
  NSString * __message;
  AuthenticationToken * __authenticationToken;
  NSString * __deviceId;

  BOOL __success_isset;
  BOOL __message_isset;
  BOOL __authenticationToken_isset;
  BOOL __deviceId_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=success, setter=setSuccess:) BOOL success;
@property (nonatomic, retain, getter=message, setter=setMessage:) NSString * message;
@property (nonatomic, retain, getter=authenticationToken, setter=setAuthenticationToken:) AuthenticationToken * authenticationToken;
@property (nonatomic, retain, getter=deviceId, setter=setDeviceId:) NSString * deviceId;
#endif

- (id) init;
- (id) initWithSuccess: (BOOL) success message: (NSString *) message authenticationToken: (AuthenticationToken *) authenticationToken deviceId: (NSString *) deviceId;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (BOOL) success;
- (void) setSuccess: (BOOL) success;
#endif
- (BOOL) successIsSet;

#if !__has_feature(objc_arc)
- (NSString *) message;
- (void) setMessage: (NSString *) message;
#endif
- (BOOL) messageIsSet;

#if !__has_feature(objc_arc)
- (AuthenticationToken) authenticationToken;
- (void) setAuthenticationToken: (AuthenticationToken) authenticationToken;
#endif
- (BOOL) authenticationTokenIsSet;

#if !__has_feature(objc_arc)
- (NSString *) deviceId;
- (void) setDeviceId: (NSString *) deviceId;
#endif
- (BOOL) deviceIdIsSet;

@end

@protocol AuthenticationService <NSObject>
- (CompanyAuthenticationResult *) authenticateCompany: (NSString *) companyId companySecret: (NSString *) companySecret;  // throws TException
- (UserAuthenticationResult *) authenticateUser: (AuthenticationToken *) companyAuthenticationToken userPrincipal: (NSString *) userPrincipal userCredentials: (NSString *) userCredentials;  // throws TException
- (DeviceAuthenticationResult *) authenticateDevice: (AuthenticationToken *) UserAuthenticationToken deviceId: (NSString *) deviceId;  // throws TException
- (void) deauthenticate: (AuthenticationToken *) token;  // throws TException
@end

@interface AuthenticationServiceClient : NSObject <AuthenticationService> {
  id <TProtocol> inProtocol;
  id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface AuthenticationServiceProcessor : NSObject <TProcessor> {
  id <AuthenticationService> mService;
  NSDictionary * mMethodMap;
}
- (id) initWithAuthenticationService: (id <AuthenticationService>) service;
- (id<AuthenticationService>) service;
@end

@interface authcConstants : NSObject {
}
@end
