/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "authc.h"

@implementation CompanyAuthenticationResult

- (id) init
{
  self = [super init];
#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
#endif
  return self;
}

- (id) initWithSuccess: (BOOL) success message: (NSString *) message authenticationToken: (AuthenticationToken*) authenticationToken companyId: (NSString *) companyId
{
  self = [super init];
  __success = success;
  __success_isset = YES;
  __message = [message retain_stub];
  __message_isset = YES;
  __authenticationToken = [authenticationToken retain_stub];
  __authenticationToken_isset = YES;
  __companyId = [companyId retain_stub];
  __companyId_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"success"])
  {
    __success = [decoder decodeBoolForKey: @"success"];
    __success_isset = YES;
  }
  if ([decoder containsValueForKey: @"message"])
  {
    __message = [[decoder decodeObjectForKey: @"message"] retain_stub];
    __message_isset = YES;
  }
  if ([decoder containsValueForKey: @"authenticationToken"])
  {
    __authenticationToken = [[decoder decodeObjectForKey: @"authenticationToken"] retain_stub];
    __authenticationToken_isset = YES;
  }
  if ([decoder containsValueForKey: @"companyId"])
  {
    __companyId = [[decoder decodeObjectForKey: @"companyId"] retain_stub];
    __companyId_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__success_isset)
  {
    [encoder encodeBool: __success forKey: @"success"];
  }
  if (__message_isset)
  {
    [encoder encodeObject: __message forKey: @"message"];
  }
  if (__authenticationToken_isset)
  {
    [encoder encodeObject: __authenticationToken forKey: @"authenticationToken"];
  }
  if (__companyId_isset)
  {
    [encoder encodeObject: __companyId forKey: @"companyId"];
  }
}

- (void) dealloc
{
  [__message release_stub];
  [__authenticationToken release_stub];
  [__companyId release_stub];
  [super dealloc_stub];
}

- (BOOL) success {
  return __success;
}

- (void) setSuccess: (BOOL) success {
  __success = success;
  __success_isset = YES;
}

- (BOOL) successIsSet {
  return __success_isset;
}

- (void) unsetSuccess {
  __success_isset = NO;
}

- (NSString *) message {
  return [[__message retain_stub] autorelease_stub];
}

- (void) setMessage: (NSString *) message {
  [message retain_stub];
  [__message release_stub];
  __message = message;
  __message_isset = YES;
}

- (BOOL) messageIsSet {
  return __message_isset;
}

- (void) unsetMessage {
  [__message release_stub];
  __message = nil;
  __message_isset = NO;
}

- (AuthenticationToken *) authenticationToken {
  return [[__authenticationToken retain_stub] autorelease_stub];
}

- (void) setAuthenticationToken: (AuthenticationToken *) authenticationToken {
  [authenticationToken retain_stub];
  [__authenticationToken release_stub];
  __authenticationToken = authenticationToken;
  __authenticationToken_isset = YES;
}

- (BOOL) authenticationTokenIsSet {
  return __authenticationToken_isset;
}

- (void) unsetAuthenticationToken {
  [__authenticationToken release_stub];
  __authenticationToken = nil;
  __authenticationToken_isset = NO;
}

- (NSString *) companyId {
  return [[__companyId retain_stub] autorelease_stub];
}

- (void) setCompanyId: (NSString *) companyId {
  [companyId retain_stub];
  [__companyId release_stub];
  __companyId = companyId;
  __companyId_isset = YES;
}

- (BOOL) companyIdIsSet {
  return __companyId_isset;
}

- (void) unsetCompanyId {
  [__companyId release_stub];
  __companyId = nil;
  __companyId_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) {
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_BOOL) {
          BOOL fieldValue = [inProtocol readBool];
          [self setSuccess: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setMessage: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 3:
        if (fieldType == TType_STRUCT) {
          AuthenticationToken *fieldValue = [[AuthenticationToken alloc] init];
          [fieldValue read: inProtocol];
          [self setAuthenticationToken: fieldValue];
          [fieldValue release_stub];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 4:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setCompanyId: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"CompanyAuthenticationResult"];
  if (__success_isset) {
    [outProtocol writeFieldBeginWithName: @"success" type: TType_BOOL fieldID: 1];
    [outProtocol writeBool: __success];
    [outProtocol writeFieldEnd];
  }
  if (__message_isset) {
    if (__message != nil) {
      [outProtocol writeFieldBeginWithName: @"message" type: TType_STRING fieldID: 2];
      [outProtocol writeString: __message];
      [outProtocol writeFieldEnd];
    }
  }
  if (__authenticationToken_isset) {
    if (__authenticationToken != nil) {
      [outProtocol writeFieldBeginWithName: @"authenticationToken" type: TType_STRUCT fieldID: 3];
      [__authenticationToken write: outProtocol];
      [outProtocol writeFieldEnd];
    }
  }
  if (__companyId_isset) {
    if (__companyId != nil) {
      [outProtocol writeFieldBeginWithName: @"companyId" type: TType_STRING fieldID: 4];
      [outProtocol writeString: __companyId];
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (void) validate {
  // check for required fields
  if (!__success_isset) {
    @throw [TProtocolException exceptionWithName: @"TProtocolException"
                               reason: @"Required field 'success' is not set."];
  }
  if (!__companyId_isset) {
    @throw [TProtocolException exceptionWithName: @"TProtocolException"
                               reason: @"Required field 'companyId' is not set."];
  }
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"CompanyAuthenticationResult("];
  [ms appendString: @"success:"];
  [ms appendFormat: @"%i", __success];
  [ms appendString: @",message:"];
  [ms appendFormat: @"\"%@\"", __message];
  [ms appendString: @",authenticationToken:"];
  [ms appendFormat: @"%@", __authenticationToken];
  [ms appendString: @",companyId:"];
  [ms appendFormat: @"\"%@\"", __companyId];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@implementation UserAuthenticationResult

- (id) init
{
  self = [super init];
#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
#endif
  return self;
}

- (id) initWithSuccess: (BOOL) success message: (NSString *) message authenticationToken: (AuthenticationToken*) authenticationToken userPrincipal: (NSString *) userPrincipal
{
  self = [super init];
  __success = success;
  __success_isset = YES;
  __message = [message retain_stub];
  __message_isset = YES;
  __authenticationToken = [authenticationToken retain_stub];
  __authenticationToken_isset = YES;
  __userPrincipal = [userPrincipal retain_stub];
  __userPrincipal_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"success"])
  {
    __success = [decoder decodeBoolForKey: @"success"];
    __success_isset = YES;
  }
  if ([decoder containsValueForKey: @"message"])
  {
    __message = [[decoder decodeObjectForKey: @"message"] retain_stub];
    __message_isset = YES;
  }
  if ([decoder containsValueForKey: @"authenticationToken"])
  {
    __authenticationToken = [[decoder decodeObjectForKey: @"authenticationToken"] retain_stub];
    __authenticationToken_isset = YES;
  }
  if ([decoder containsValueForKey: @"userPrincipal"])
  {
    __userPrincipal = [[decoder decodeObjectForKey: @"userPrincipal"] retain_stub];
    __userPrincipal_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__success_isset)
  {
    [encoder encodeBool: __success forKey: @"success"];
  }
  if (__message_isset)
  {
    [encoder encodeObject: __message forKey: @"message"];
  }
  if (__authenticationToken_isset)
  {
    [encoder encodeObject: __authenticationToken forKey: @"authenticationToken"];
  }
  if (__userPrincipal_isset)
  {
    [encoder encodeObject: __userPrincipal forKey: @"userPrincipal"];
  }
}

- (void) dealloc
{
  [__message release_stub];
  [__authenticationToken release_stub];
  [__userPrincipal release_stub];
  [super dealloc_stub];
}

- (BOOL) success {
  return __success;
}

- (void) setSuccess: (BOOL) success {
  __success = success;
  __success_isset = YES;
}

- (BOOL) successIsSet {
  return __success_isset;
}

- (void) unsetSuccess {
  __success_isset = NO;
}

- (NSString *) message {
  return [[__message retain_stub] autorelease_stub];
}

- (void) setMessage: (NSString *) message {
  [message retain_stub];
  [__message release_stub];
  __message = message;
  __message_isset = YES;
}

- (BOOL) messageIsSet {
  return __message_isset;
}

- (void) unsetMessage {
  [__message release_stub];
  __message = nil;
  __message_isset = NO;
}

- (AuthenticationToken *) authenticationToken {
  return [[__authenticationToken retain_stub] autorelease_stub];
}

- (void) setAuthenticationToken: (AuthenticationToken *) authenticationToken {
  [authenticationToken retain_stub];
  [__authenticationToken release_stub];
  __authenticationToken = authenticationToken;
  __authenticationToken_isset = YES;
}

- (BOOL) authenticationTokenIsSet {
  return __authenticationToken_isset;
}

- (void) unsetAuthenticationToken {
  [__authenticationToken release_stub];
  __authenticationToken = nil;
  __authenticationToken_isset = NO;
}

- (NSString *) userPrincipal {
  return [[__userPrincipal retain_stub] autorelease_stub];
}

- (void) setUserPrincipal: (NSString *) userPrincipal {
  [userPrincipal retain_stub];
  [__userPrincipal release_stub];
  __userPrincipal = userPrincipal;
  __userPrincipal_isset = YES;
}

- (BOOL) userPrincipalIsSet {
  return __userPrincipal_isset;
}

- (void) unsetUserPrincipal {
  [__userPrincipal release_stub];
  __userPrincipal = nil;
  __userPrincipal_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_BOOL) {
          BOOL fieldValue = [inProtocol readBool];
          [self setSuccess: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setMessage: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 3:
        if (fieldType == TType_STRUCT) {
          AuthenticationToken *fieldValue = [[AuthenticationToken alloc] init];
          [fieldValue read: inProtocol];
          [self setAuthenticationToken: fieldValue];
          [fieldValue release_stub];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 4:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setUserPrincipal: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"UserAuthenticationResult"];
  if (__success_isset) {
    [outProtocol writeFieldBeginWithName: @"success" type: TType_BOOL fieldID: 1];
    [outProtocol writeBool: __success];
    [outProtocol writeFieldEnd];
  }
  if (__message_isset) {
    if (__message != nil) {
      [outProtocol writeFieldBeginWithName: @"message" type: TType_STRING fieldID: 2];
      [outProtocol writeString: __message];
      [outProtocol writeFieldEnd];
    }
  }
  if (__authenticationToken_isset) {
    if (__authenticationToken != nil) {
      [outProtocol writeFieldBeginWithName: @"authenticationToken" type: TType_STRUCT fieldID: 3];
      [__authenticationToken write: outProtocol];
      [outProtocol writeFieldEnd];
    }
  }
  if (__userPrincipal_isset) {
    if (__userPrincipal != nil) {
      [outProtocol writeFieldBeginWithName: @"userPrincipal" type: TType_STRING fieldID: 4];
      [outProtocol writeString: __userPrincipal];
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (void) validate {
  // check for required fields
  if (!__success_isset) {
    @throw [TProtocolException exceptionWithName: @"TProtocolException"
                               reason: @"Required field 'success' is not set."];
  }
  if (!__userPrincipal_isset) {
    @throw [TProtocolException exceptionWithName: @"TProtocolException"
                               reason: @"Required field 'userPrincipal' is not set."];
  }
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"UserAuthenticationResult("];
  [ms appendString: @"success:"];
  [ms appendFormat: @"%i", __success];
  [ms appendString: @",message:"];
  [ms appendFormat: @"\"%@\"", __message];
  [ms appendString: @",authenticationToken:"];
  [ms appendFormat: @"%@", __authenticationToken];
  [ms appendString: @",userPrincipal:"];
  [ms appendFormat: @"\"%@\"", __userPrincipal];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@implementation DeviceAuthenticationResult

- (id) init
{
  self = [super init];
#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
#endif
  return self;
}

- (id) initWithSuccess: (BOOL) success message: (NSString *) message authenticationToken: (AuthenticationToken*) authenticationToken deviceId: (NSString *) deviceId
{
  self = [super init];
  __success = success;
  __success_isset = YES;
  __message = [message retain_stub];
  __message_isset = YES;
  __authenticationToken = [authenticationToken retain_stub];
  __authenticationToken_isset = YES;
  __deviceId = [deviceId retain_stub];
  __deviceId_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"success"])
  {
    __success = [decoder decodeBoolForKey: @"success"];
    __success_isset = YES;
  }
  if ([decoder containsValueForKey: @"message"])
  {
    __message = [[decoder decodeObjectForKey: @"message"] retain_stub];
    __message_isset = YES;
  }
  if ([decoder containsValueForKey: @"authenticationToken"])
  {
    __authenticationToken = [[decoder decodeObjectForKey: @"authenticationToken"] retain_stub];
    __authenticationToken_isset = YES;
  }
  if ([decoder containsValueForKey: @"deviceId"])
  {
    __deviceId = [[decoder decodeObjectForKey: @"deviceId"] retain_stub];
    __deviceId_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__success_isset)
  {
    [encoder encodeBool: __success forKey: @"success"];
  }
  if (__message_isset)
  {
    [encoder encodeObject: __message forKey: @"message"];
  }
  if (__authenticationToken_isset)
  {
    [encoder encodeObject: __authenticationToken forKey: @"authenticationToken"];
  }
  if (__deviceId_isset)
  {
    [encoder encodeObject: __deviceId forKey: @"deviceId"];
  }
}

- (void) dealloc
{
  [__message release_stub];
  [__authenticationToken release_stub];
  [__deviceId release_stub];
  [super dealloc_stub];
}

- (BOOL) success {
  return __success;
}

- (void) setSuccess: (BOOL) success {
  __success = success;
  __success_isset = YES;
}

- (BOOL) successIsSet {
  return __success_isset;
}

- (void) unsetSuccess {
  __success_isset = NO;
}

- (NSString *) message {
  return [[__message retain_stub] autorelease_stub];
}

- (void) setMessage: (NSString *) message {
  [message retain_stub];
  [__message release_stub];
  __message = message;
  __message_isset = YES;
}

- (BOOL) messageIsSet {
  return __message_isset;
}

- (void) unsetMessage {
  [__message release_stub];
  __message = nil;
  __message_isset = NO;
}

- (AuthenticationToken *) authenticationToken {
  return [[__authenticationToken retain_stub] autorelease_stub];
}

- (void) setAuthenticationToken: (AuthenticationToken *) authenticationToken {
  [authenticationToken retain_stub];
  [__authenticationToken release_stub];
  __authenticationToken = authenticationToken;
  __authenticationToken_isset = YES;
}

- (BOOL) authenticationTokenIsSet {
  return __authenticationToken_isset;
}

- (void) unsetAuthenticationToken {
  [__authenticationToken release_stub];
  __authenticationToken = nil;
  __authenticationToken_isset = NO;
}

- (NSString *) deviceId {
  return [[__deviceId retain_stub] autorelease_stub];
}

- (void) setDeviceId: (NSString *) deviceId {
  [deviceId retain_stub];
  [__deviceId release_stub];
  __deviceId = deviceId;
  __deviceId_isset = YES;
}

- (BOOL) deviceIdIsSet {
  return __deviceId_isset;
}

- (void) unsetDeviceId {
  [__deviceId release_stub];
  __deviceId = nil;
  __deviceId_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_BOOL) {
          BOOL fieldValue = [inProtocol readBool];
          [self setSuccess: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setMessage: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 3:
        if (fieldType == TType_STRUCT) {
          AuthenticationToken *fieldValue = [[AuthenticationToken alloc] init];
          [fieldValue read: inProtocol];
          [self setAuthenticationToken: fieldValue];
          [fieldValue release_stub];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 4:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setDeviceId: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"DeviceAuthenticationResult"];
  if (__success_isset) {
    [outProtocol writeFieldBeginWithName: @"success" type: TType_BOOL fieldID: 1];
    [outProtocol writeBool: __success];
    [outProtocol writeFieldEnd];
  }
  if (__message_isset) {
    if (__message != nil) {
      [outProtocol writeFieldBeginWithName: @"message" type: TType_STRING fieldID: 2];
      [outProtocol writeString: __message];
      [outProtocol writeFieldEnd];
    }
  }
  if (__authenticationToken_isset) {
    if (__authenticationToken != nil) {
      [outProtocol writeFieldBeginWithName: @"authenticationToken" type: TType_STRUCT fieldID: 3];
      [__authenticationToken write: outProtocol];
      [outProtocol writeFieldEnd];
    }
  }
  if (__deviceId_isset) {
    if (__deviceId != nil) {
      [outProtocol writeFieldBeginWithName: @"deviceId" type: TType_STRING fieldID: 4];
      [outProtocol writeString: __deviceId];
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (void) validate {
  // check for required fields
  if (!__success_isset) {
    @throw [TProtocolException exceptionWithName: @"TProtocolException"
                               reason: @"Required field 'success' is not set."];
  }
  if (!__deviceId_isset) {
    @throw [TProtocolException exceptionWithName: @"TProtocolException"
                               reason: @"Required field 'deviceId' is not set."];
  }
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"DeviceAuthenticationResult("];
  [ms appendString: @"success:"];
  [ms appendFormat: @"%i", __success];
  [ms appendString: @",message:"];
  [ms appendFormat: @"\"%@\"", __message];
  [ms appendString: @",authenticationToken:"];
  [ms appendFormat: @"%@", __authenticationToken];
  [ms appendString: @",deviceId:"];
  [ms appendFormat: @"\"%@\"", __deviceId];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end


@implementation authcConstants
+ (void) initialize {
}
@end

@interface authenticateCompany_args : NSObject <TBase, NSCoding> {
  NSString * __companyId;
  NSString * __companySecret;

  BOOL __companyId_isset;
  BOOL __companySecret_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=companyId, setter=setCompanyId:) NSString * companyId;
@property (nonatomic, retain, getter=companySecret, setter=setCompanySecret:) NSString * companySecret;
#endif

- (id) init;
- (id) initWithCompanyId: (NSString *) companyId companySecret: (NSString *) companySecret;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) companyId;
- (void) setCompanyId: (NSString *) companyId;
#endif
- (BOOL) companyIdIsSet;

#if !__has_feature(objc_arc)
- (NSString *) companySecret;
- (void) setCompanySecret: (NSString *) companySecret;
#endif
- (BOOL) companySecretIsSet;

@end

@implementation authenticateCompany_args

- (id) init
{
  self = [super init];
#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
#endif
  return self;
}

- (id) initWithCompanyId: (NSString *) companyId companySecret: (NSString *) companySecret
{
  self = [super init];
  __companyId = [companyId retain_stub];
  __companyId_isset = YES;
  __companySecret = [companySecret retain_stub];
  __companySecret_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"companyId"])
  {
    __companyId = [[decoder decodeObjectForKey: @"companyId"] retain_stub];
    __companyId_isset = YES;
  }
  if ([decoder containsValueForKey: @"companySecret"])
  {
    __companySecret = [[decoder decodeObjectForKey: @"companySecret"] retain_stub];
    __companySecret_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__companyId_isset)
  {
    [encoder encodeObject: __companyId forKey: @"companyId"];
  }
  if (__companySecret_isset)
  {
    [encoder encodeObject: __companySecret forKey: @"companySecret"];
  }
}

- (void) dealloc
{
  [__companyId release_stub];
  [__companySecret release_stub];
  [super dealloc_stub];
}

- (NSString *) companyId {
  return [[__companyId retain_stub] autorelease_stub];
}

- (void) setCompanyId: (NSString *) companyId {
  [companyId retain_stub];
  [__companyId release_stub];
  __companyId = companyId;
  __companyId_isset = YES;
}

- (BOOL) companyIdIsSet {
  return __companyId_isset;
}

- (void) unsetCompanyId {
  [__companyId release_stub];
  __companyId = nil;
  __companyId_isset = NO;
}

- (NSString *) companySecret {
  return [[__companySecret retain_stub] autorelease_stub];
}

- (void) setCompanySecret: (NSString *) companySecret {
  [companySecret retain_stub];
  [__companySecret release_stub];
  __companySecret = companySecret;
  __companySecret_isset = YES;
}

- (BOOL) companySecretIsSet {
  return __companySecret_isset;
}

- (void) unsetCompanySecret {
  [__companySecret release_stub];
  __companySecret = nil;
  __companySecret_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setCompanyId: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setCompanySecret: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"authenticateCompany_args"];
  if (__companyId_isset) {
    if (__companyId != nil) {
      [outProtocol writeFieldBeginWithName: @"companyId" type: TType_STRING fieldID: 1];
      [outProtocol writeString: __companyId];
      [outProtocol writeFieldEnd];
    }
  }
  if (__companySecret_isset) {
    if (__companySecret != nil) {
      [outProtocol writeFieldBeginWithName: @"companySecret" type: TType_STRING fieldID: 2];
      [outProtocol writeString: __companySecret];
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (void) validate {
  // check for required fields
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"authenticateCompany_args("];
  [ms appendString: @"companyId:"];
  [ms appendFormat: @"\"%@\"", __companyId];
  [ms appendString: @",companySecret:"];
  [ms appendFormat: @"\"%@\"", __companySecret];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@interface AuthenticateCompany_result : NSObject <TBase, NSCoding> {
  CompanyAuthenticationResult * __success;

  BOOL __success_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=success, setter=setSuccess:) CompanyAuthenticationResult * success;
#endif

- (id) init;
- (id) initWithSuccess: (CompanyAuthenticationResult *) success;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (CompanyAuthenticationResult *) success;
- (void) setSuccess: (CompanyAuthenticationResult *) success;
#endif
- (BOOL) successIsSet;

@end

@implementation AuthenticateCompany_result

- (id) init
{
  self = [super init];
#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
#endif
  return self;
}

- (id) initWithSuccess: (CompanyAuthenticationResult *) success
{
  self = [super init];
  __success = [success retain_stub];
  __success_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"success"])
  {
    __success = [[decoder decodeObjectForKey: @"success"] retain_stub];
    __success_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__success_isset)
  {
    [encoder encodeObject: __success forKey: @"success"];
  }
}

- (void) dealloc
{
  [__success release_stub];
  [super dealloc_stub];
}

- (CompanyAuthenticationResult *) success {
  return [[__success retain_stub] autorelease_stub];
}

- (void) setSuccess: (CompanyAuthenticationResult *) success {
  [success retain_stub];
  [__success release_stub];
  __success = success;
  __success_isset = YES;
}

- (BOOL) successIsSet {
  return __success_isset;
}

- (void) unsetSuccess {
  [__success release_stub];
  __success = nil;
  __success_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 0:
        if (fieldType == TType_STRUCT) {
          CompanyAuthenticationResult *fieldValue = [[CompanyAuthenticationResult alloc] init];
          [fieldValue read: inProtocol];
          [self setSuccess: fieldValue];
          [fieldValue release_stub];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"AuthenticateCompany_result"];

  if (__success_isset) {
    if (__success != nil) {
      [outProtocol writeFieldBeginWithName: @"success" type: TType_STRUCT fieldID: 0];
      [__success write: outProtocol];
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (void) validate {
  // check for required fields
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"AuthenticateCompany_result("];
  [ms appendString: @"success:"];
  [ms appendFormat: @"%@", __success];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@interface authenticateUser_args : NSObject <TBase, NSCoding> {
  AuthenticationToken *__companyAuthenticationToken;
  NSString * __userPrincipal;
  NSString * __userCredentials;

  BOOL __companyAuthenticationToken_isset;
  BOOL __userPrincipal_isset;
  BOOL __userCredentials_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=companyAuthenticationToken, setter=setCompanyAuthenticationToken:) AuthenticationToken* companyAuthenticationToken;
@property (nonatomic, retain, getter=userPrincipal, setter=setUserPrincipal:) NSString * userPrincipal;
@property (nonatomic, retain, getter=userCredentials, setter=setUserCredentials:) NSString * userCredentials;
#endif

- (id) init;
- (id) initWithCompanyAuthenticationToken: (AuthenticationToken*) companyAuthenticationToken userPrincipal: (NSString *) userPrincipal userCredentials: (NSString *) userCredentials;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (AuthenticationToken) companyAuthenticationToken;
- (void) setCompanyAuthenticationToken: (AuthenticationToken) companyAuthenticationToken;
#endif
- (BOOL) companyAuthenticationTokenIsSet;

#if !__has_feature(objc_arc)
- (NSString *) userPrincipal;
- (void) setUserPrincipal: (NSString *) userPrincipal;
#endif
- (BOOL) userPrincipalIsSet;

#if !__has_feature(objc_arc)
- (NSString *) userCredentials;
- (void) setUserCredentials: (NSString *) userCredentials;
#endif
- (BOOL) userCredentialsIsSet;

@end

@implementation authenticateUser_args

- (id) init
{
  self = [super init];
#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
#endif
  return self;
}

- (id) initWithCompanyAuthenticationToken: (AuthenticationToken*
                                            ) companyAuthenticationToken userPrincipal: (NSString *) userPrincipal userCredentials: (NSString *) userCredentials
{
  self = [super init];
  __companyAuthenticationToken = [companyAuthenticationToken retain_stub];
  __companyAuthenticationToken_isset = YES;
  __userPrincipal = [userPrincipal retain_stub];
  __userPrincipal_isset = YES;
  __userCredentials = [userCredentials retain_stub];
  __userCredentials_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"companyAuthenticationToken"])
  {
    __companyAuthenticationToken = [[decoder decodeObjectForKey: @"companyAuthenticationToken"] retain_stub];
    __companyAuthenticationToken_isset = YES;
  }
  if ([decoder containsValueForKey: @"userPrincipal"])
  {
    __userPrincipal = [[decoder decodeObjectForKey: @"userPrincipal"] retain_stub];
    __userPrincipal_isset = YES;
  }
  if ([decoder containsValueForKey: @"userCredentials"])
  {
    __userCredentials = [[decoder decodeObjectForKey: @"userCredentials"] retain_stub];
    __userCredentials_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__companyAuthenticationToken_isset)
  {
    [encoder encodeObject: __companyAuthenticationToken forKey: @"companyAuthenticationToken"];
  }
  if (__userPrincipal_isset)
  {
    [encoder encodeObject: __userPrincipal forKey: @"userPrincipal"];
  }
  if (__userCredentials_isset)
  {
    [encoder encodeObject: __userCredentials forKey: @"userCredentials"];
  }
}

- (void) dealloc
{
  [__companyAuthenticationToken release_stub];
  [__userPrincipal release_stub];
  [__userCredentials release_stub];
  [super dealloc_stub];
}

- (AuthenticationToken *) companyAuthenticationToken {
  return [[__companyAuthenticationToken retain_stub] autorelease_stub];
}

- (void) setCompanyAuthenticationToken: (AuthenticationToken *) companyAuthenticationToken {
  [companyAuthenticationToken retain_stub];
  [__companyAuthenticationToken release_stub];
  __companyAuthenticationToken = companyAuthenticationToken;
  __companyAuthenticationToken_isset = YES;
}

- (BOOL) companyAuthenticationTokenIsSet {
  return __companyAuthenticationToken_isset;
}

- (void) unsetCompanyAuthenticationToken {
  [__companyAuthenticationToken release_stub];
  __companyAuthenticationToken = nil;
  __companyAuthenticationToken_isset = NO;
}

- (NSString *) userPrincipal {
  return [[__userPrincipal retain_stub] autorelease_stub];
}

- (void) setUserPrincipal: (NSString *) userPrincipal {
  [userPrincipal retain_stub];
  [__userPrincipal release_stub];
  __userPrincipal = userPrincipal;
  __userPrincipal_isset = YES;
}

- (BOOL) userPrincipalIsSet {
  return __userPrincipal_isset;
}

- (void) unsetUserPrincipal {
  [__userPrincipal release_stub];
  __userPrincipal = nil;
  __userPrincipal_isset = NO;
}

- (NSString *) userCredentials {
  return [[__userCredentials retain_stub] autorelease_stub];
}

- (void) setUserCredentials: (NSString *) userCredentials {
  [userCredentials retain_stub];
  [__userCredentials release_stub];
  __userCredentials = userCredentials;
  __userCredentials_isset = YES;
}

- (BOOL) userCredentialsIsSet {
  return __userCredentials_isset;
}

- (void) unsetUserCredentials {
  [__userCredentials release_stub];
  __userCredentials = nil;
  __userCredentials_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_STRUCT) {
          AuthenticationToken *fieldValue = [[AuthenticationToken alloc] init];
          [fieldValue read: inProtocol];
          [self setCompanyAuthenticationToken: fieldValue];
          [fieldValue release_stub];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setUserPrincipal: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 3:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setUserCredentials: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"authenticateUser_args"];
  if (__companyAuthenticationToken_isset) {
    if (__companyAuthenticationToken != nil) {
      [outProtocol writeFieldBeginWithName: @"companyAuthenticationToken" type: TType_STRUCT fieldID: 1];
      [__companyAuthenticationToken write: outProtocol];
      [outProtocol writeFieldEnd];
    }
  }
  if (__userPrincipal_isset) {
    if (__userPrincipal != nil) {
      [outProtocol writeFieldBeginWithName: @"userPrincipal" type: TType_STRING fieldID: 2];
      [outProtocol writeString: __userPrincipal];
      [outProtocol writeFieldEnd];
    }
  }
  if (__userCredentials_isset) {
    if (__userCredentials != nil) {
      [outProtocol writeFieldBeginWithName: @"userCredentials" type: TType_STRING fieldID: 3];
      [outProtocol writeString: __userCredentials];
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (void) validate {
  // check for required fields
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"authenticateUser_args("];
  [ms appendString: @"companyAuthenticationToken:"];
  [ms appendFormat: @"%@", __companyAuthenticationToken];
  [ms appendString: @",userPrincipal:"];
  [ms appendFormat: @"\"%@\"", __userPrincipal];
  [ms appendString: @",userCredentials:"];
  [ms appendFormat: @"\"%@\"", __userCredentials];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@interface AuthenticateUser_result : NSObject <TBase, NSCoding> {
  UserAuthenticationResult * __success;

  BOOL __success_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=success, setter=setSuccess:) UserAuthenticationResult * success;
#endif

- (id) init;
- (id) initWithSuccess: (UserAuthenticationResult *) success;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (UserAuthenticationResult *) success;
- (void) setSuccess: (UserAuthenticationResult *) success;
#endif
- (BOOL) successIsSet;

@end

@implementation AuthenticateUser_result

- (id) init
{
  self = [super init];
#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
#endif
  return self;
}

- (id) initWithSuccess: (UserAuthenticationResult *) success
{
  self = [super init];
  __success = [success retain_stub];
  __success_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"success"])
  {
    __success = [[decoder decodeObjectForKey: @"success"] retain_stub];
    __success_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__success_isset)
  {
    [encoder encodeObject: __success forKey: @"success"];
  }
}

- (void) dealloc
{
  [__success release_stub];
  [super dealloc_stub];
}

- (UserAuthenticationResult *) success {
  return [[__success retain_stub] autorelease_stub];
}

- (void) setSuccess: (UserAuthenticationResult *) success {
  [success retain_stub];
  [__success release_stub];
  __success = success;
  __success_isset = YES;
}

- (BOOL) successIsSet {
  return __success_isset;
}

- (void) unsetSuccess {
  [__success release_stub];
  __success = nil;
  __success_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 0:
        if (fieldType == TType_STRUCT) {
          UserAuthenticationResult *fieldValue = [[UserAuthenticationResult alloc] init];
          [fieldValue read: inProtocol];
          [self setSuccess: fieldValue];
          [fieldValue release_stub];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"AuthenticateUser_result"];

  if (__success_isset) {
    if (__success != nil) {
      [outProtocol writeFieldBeginWithName: @"success" type: TType_STRUCT fieldID: 0];
      [__success write: outProtocol];
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (void) validate {
  // check for required fields
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"AuthenticateUser_result("];
  [ms appendString: @"success:"];
  [ms appendFormat: @"%@", __success];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@interface authenticateDevice_args : NSObject <TBase, NSCoding> {
  AuthenticationToken *__UserAuthenticationToken;
  NSString * __deviceId;

  BOOL __UserAuthenticationToken_isset;
  BOOL __deviceId_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=userAuthenticationToken, setter=setUserAuthenticationToken:) AuthenticationToken* UserAuthenticationToken;
@property (nonatomic, retain, getter=deviceId, setter=setDeviceId:) NSString * deviceId;
#endif

- (id) init;
- (id) initWithUserAuthenticationToken: (AuthenticationToken*) UserAuthenticationToken deviceId: (NSString *) deviceId;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (AuthenticationToken) userAuthenticationToken;
- (void) setUserAuthenticationToken: (AuthenticationToken) UserAuthenticationToken;
#endif
- (BOOL) UserAuthenticationTokenIsSet;

#if !__has_feature(objc_arc)
- (NSString *) deviceId;
- (void) setDeviceId: (NSString *) deviceId;
#endif
- (BOOL) deviceIdIsSet;

@end

@implementation authenticateDevice_args

- (id) init
{
  self = [super init];
#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
#endif
  return self;
}

- (id) initWithUserAuthenticationToken: (AuthenticationToken*) UserAuthenticationToken deviceId: (NSString *) deviceId
{
  self = [super init];
  __UserAuthenticationToken = [UserAuthenticationToken retain_stub];
  __UserAuthenticationToken_isset = YES;
  __deviceId = [deviceId retain_stub];
  __deviceId_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"UserAuthenticationToken"])
  {
    __UserAuthenticationToken = [[decoder decodeObjectForKey: @"UserAuthenticationToken"] retain_stub];
    __UserAuthenticationToken_isset = YES;
  }
  if ([decoder containsValueForKey: @"deviceId"])
  {
    __deviceId = [[decoder decodeObjectForKey: @"deviceId"] retain_stub];
    __deviceId_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__UserAuthenticationToken_isset)
  {
    [encoder encodeObject: __UserAuthenticationToken forKey: @"UserAuthenticationToken"];
  }
  if (__deviceId_isset)
  {
    [encoder encodeObject: __deviceId forKey: @"deviceId"];
  }
}

- (void) dealloc
{
  [__UserAuthenticationToken release_stub];
  [__deviceId release_stub];
  [super dealloc_stub];
}

- (AuthenticationToken *) UserAuthenticationToken {
  return [[__UserAuthenticationToken retain_stub] autorelease_stub];
}

- (void) setUserAuthenticationToken: (AuthenticationToken *) UserAuthenticationToken {
  [UserAuthenticationToken retain_stub];
  [__UserAuthenticationToken release_stub];
  __UserAuthenticationToken = UserAuthenticationToken;
  __UserAuthenticationToken_isset = YES;
}

- (BOOL) UserAuthenticationTokenIsSet {
  return __UserAuthenticationToken_isset;
}

- (void) unsetUserAuthenticationToken {
  [__UserAuthenticationToken release_stub];
  __UserAuthenticationToken = nil;
  __UserAuthenticationToken_isset = NO;
}

- (NSString *) deviceId {
  return [[__deviceId retain_stub] autorelease_stub];
}

- (void) setDeviceId: (NSString *) deviceId {
  [deviceId retain_stub];
  [__deviceId release_stub];
  __deviceId = deviceId;
  __deviceId_isset = YES;
}

- (BOOL) deviceIdIsSet {
  return __deviceId_isset;
}

- (void) unsetDeviceId {
  [__deviceId release_stub];
  __deviceId = nil;
  __deviceId_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_STRUCT) {
          AuthenticationToken *fieldValue = [[AuthenticationToken alloc] init];
          [fieldValue read: inProtocol];
          [self setUserAuthenticationToken: fieldValue];
          [fieldValue release_stub];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setDeviceId: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"authenticateDevice_args"];
  if (__UserAuthenticationToken_isset) {
    if (__UserAuthenticationToken != nil) {
      [outProtocol writeFieldBeginWithName: @"UserAuthenticationToken" type: TType_STRUCT fieldID: 1];
      [__UserAuthenticationToken write: outProtocol];
      [outProtocol writeFieldEnd];
    }
  }
  if (__deviceId_isset) {
    if (__deviceId != nil) {
      [outProtocol writeFieldBeginWithName: @"deviceId" type: TType_STRING fieldID: 2];
      [outProtocol writeString: __deviceId];
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (void) validate {
  // check for required fields
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"authenticateDevice_args("];
  [ms appendString: @"UserAuthenticationToken:"];
  [ms appendFormat: @"%@", __UserAuthenticationToken];
  [ms appendString: @",deviceId:"];
  [ms appendFormat: @"\"%@\"", __deviceId];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@interface AuthenticateDevice_result : NSObject <TBase, NSCoding> {
  DeviceAuthenticationResult * __success;

  BOOL __success_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=success, setter=setSuccess:) DeviceAuthenticationResult * success;
#endif

- (id) init;
- (id) initWithSuccess: (DeviceAuthenticationResult *) success;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (DeviceAuthenticationResult *) success;
- (void) setSuccess: (DeviceAuthenticationResult *) success;
#endif
- (BOOL) successIsSet;

@end

@implementation AuthenticateDevice_result

- (id) init
{
  self = [super init];
#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
#endif
  return self;
}

- (id) initWithSuccess: (DeviceAuthenticationResult *) success
{
  self = [super init];
  __success = [success retain_stub];
  __success_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"success"])
  {
    __success = [[decoder decodeObjectForKey: @"success"] retain_stub];
    __success_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__success_isset)
  {
    [encoder encodeObject: __success forKey: @"success"];
  }
}

- (void) dealloc
{
  [__success release_stub];
  [super dealloc_stub];
}

- (DeviceAuthenticationResult *) success {
  return [[__success retain_stub] autorelease_stub];
}

- (void) setSuccess: (DeviceAuthenticationResult *) success {
  [success retain_stub];
  [__success release_stub];
  __success = success;
  __success_isset = YES;
}

- (BOOL) successIsSet {
  return __success_isset;
}

- (void) unsetSuccess {
  [__success release_stub];
  __success = nil;
  __success_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 0:
        if (fieldType == TType_STRUCT) {
          DeviceAuthenticationResult *fieldValue = [[DeviceAuthenticationResult alloc] init];
          [fieldValue read: inProtocol];
          [self setSuccess: fieldValue];
          [fieldValue release_stub];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"AuthenticateDevice_result"];

  if (__success_isset) {
    if (__success != nil) {
      [outProtocol writeFieldBeginWithName: @"success" type: TType_STRUCT fieldID: 0];
      [__success write: outProtocol];
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (void) validate {
  // check for required fields
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"AuthenticateDevice_result("];
  [ms appendString: @"success:"];
  [ms appendFormat: @"%@", __success];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@interface deauthenticate_args : NSObject <TBase, NSCoding> {
  AuthenticationToken *__token;

  BOOL __token_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=token, setter=setToken:) AuthenticationToken* token;
#endif

- (id) init;
- (id) initWithToken: (AuthenticationToken*) token;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (AuthenticationToken) token;
- (void) setToken: (AuthenticationToken) token;
#endif
- (BOOL) tokenIsSet;

@end

@implementation deauthenticate_args

- (id) init
{
  self = [super init];
#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
#endif
  return self;
}

- (id) initWithToken: (AuthenticationToken*) token
{
  self = [super init];
  __token = [token retain_stub];
  __token_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"token"])
  {
    __token = [[decoder decodeObjectForKey: @"token"] retain_stub];
    __token_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__token_isset)
  {
    [encoder encodeObject: __token forKey: @"token"];
  }
}

- (void) dealloc
{
  [__token release_stub];
  [super dealloc_stub];
}

- (AuthenticationToken *) token {
  return [[__token retain_stub] autorelease_stub];
}

- (void) setToken: (AuthenticationToken *) token {
  [token retain_stub];
  [__token release_stub];
  __token = token;
  __token_isset = YES;
}

- (BOOL) tokenIsSet {
  return __token_isset;
}

- (void) unsetToken {
  [__token release_stub];
  __token = nil;
  __token_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_STRUCT) {
          AuthenticationToken *fieldValue = [[AuthenticationToken alloc] init];
          [fieldValue read: inProtocol];
          [self setToken: fieldValue];
          [fieldValue release_stub];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"deauthenticate_args"];
  if (__token_isset) {
    if (__token != nil) {
      [outProtocol writeFieldBeginWithName: @"token" type: TType_STRUCT fieldID: 1];
      [__token write: outProtocol];
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (void) validate {
  // check for required fields
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"deauthenticate_args("];
  [ms appendString: @"token:"];
  [ms appendFormat: @"%@", __token];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@interface Deauthenticate_result : NSObject <TBase, NSCoding> {
}

- (id) init;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

@end

@implementation Deauthenticate_result

- (id) init
{
  self = [super init];
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"Deauthenticate_result"];

  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (void) validate {
  // check for required fields
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"Deauthenticate_result("];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@implementation AuthenticationServiceClient
- (id) initWithProtocol: (id <TProtocol>) protocol
{
  return [self initWithInProtocol: protocol outProtocol: protocol];
}

- (id) initWithInProtocol: (id <TProtocol>) anInProtocol outProtocol: (id <TProtocol>) anOutProtocol
{
  self = [super init];
  inProtocol = [anInProtocol retain_stub];
  outProtocol = [anOutProtocol retain_stub];
  return self;
}

- (void) dealloc
{
  [inProtocol release_stub];
  [outProtocol release_stub];
  [super dealloc_stub];
}

- (void) send_authenticateCompany: (NSString *) companyId companySecret: (NSString *) companySecret
{
  [outProtocol writeMessageBeginWithName: @"authenticateCompany" type: TMessageType_CALL sequenceID: 0];
  [outProtocol writeStructBeginWithName: @"authenticateCompany_args"];
  if (companyId != nil)  {
    [outProtocol writeFieldBeginWithName: @"companyId" type: TType_STRING fieldID: 1];
    [outProtocol writeString: companyId];
    [outProtocol writeFieldEnd];
  }
  if (companySecret != nil)  {
    [outProtocol writeFieldBeginWithName: @"companySecret" type: TType_STRING fieldID: 2];
    [outProtocol writeString: companySecret];
    [outProtocol writeFieldEnd];
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
  [outProtocol writeMessageEnd];
  [[outProtocol transport] flush];
}

- (CompanyAuthenticationResult *) recv_authenticateCompany
{
  int msgType = 0;
  [inProtocol readMessageBeginReturningName: nil type: &msgType sequenceID: NULL];
  if (msgType == TMessageType_EXCEPTION) {
    TApplicationException * x = [TApplicationException read: inProtocol];
    [inProtocol readMessageEnd];
    @throw x;
  }
  AuthenticateCompany_result * result = [[[AuthenticateCompany_result alloc] init] autorelease_stub];
  [result read: inProtocol];
  [inProtocol readMessageEnd];
  if ([result successIsSet]) {
    return [result success];
  }
  @throw [TApplicationException exceptionWithType: TApplicationException_MISSING_RESULT
                                           reason: @"authenticateCompany failed: unknown result"];
}

- (CompanyAuthenticationResult *) authenticateCompany: (NSString *) companyId companySecret: (NSString *) companySecret
{
  [self send_authenticateCompany : companyId companySecret: companySecret];
  return [self recv_authenticateCompany];
}

- (void) send_authenticateUser: (AuthenticationToken*) companyAuthenticationToken userPrincipal: (NSString *) userPrincipal userCredentials: (NSString *) userCredentials
{
  [outProtocol writeMessageBeginWithName: @"authenticateUser" type: TMessageType_CALL sequenceID: 0];
  [outProtocol writeStructBeginWithName: @"authenticateUser_args"];
  if (companyAuthenticationToken != nil)  {
    [outProtocol writeFieldBeginWithName: @"companyAuthenticationToken" type: TType_STRUCT fieldID: 1];
    [companyAuthenticationToken write: outProtocol];
    [outProtocol writeFieldEnd];
  }
  if (userPrincipal != nil)  {
    [outProtocol writeFieldBeginWithName: @"userPrincipal" type: TType_STRING fieldID: 2];
    [outProtocol writeString: userPrincipal];
    [outProtocol writeFieldEnd];
  }
  if (userCredentials != nil)  {
    [outProtocol writeFieldBeginWithName: @"userCredentials" type: TType_STRING fieldID: 3];
    [outProtocol writeString: userCredentials];
    [outProtocol writeFieldEnd];
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
  [outProtocol writeMessageEnd];
  [[outProtocol transport] flush];
}

- (UserAuthenticationResult *) recv_authenticateUser
{
  int msgType = 0;
  [inProtocol readMessageBeginReturningName: nil type: &msgType sequenceID: NULL];
  if (msgType == TMessageType_EXCEPTION) {
    TApplicationException * x = [TApplicationException read: inProtocol];
    [inProtocol readMessageEnd];
    @throw x;
  }
  AuthenticateUser_result * result = [[[AuthenticateUser_result alloc] init] autorelease_stub];
  [result read: inProtocol];
  [inProtocol readMessageEnd];
  if ([result successIsSet]) {
    return [result success];
  }
  @throw [TApplicationException exceptionWithType: TApplicationException_MISSING_RESULT
                                           reason: @"authenticateUser failed: unknown result"];
}

- (UserAuthenticationResult *) authenticateUser: (AuthenticationToken*) companyAuthenticationToken userPrincipal: (NSString *) userPrincipal userCredentials: (NSString *) userCredentials
{
  [self send_authenticateUser : companyAuthenticationToken userPrincipal: userPrincipal userCredentials: userCredentials];
  return [self recv_authenticateUser];
}

- (void) send_authenticateDevice: (AuthenticationToken*) UserAuthenticationToken deviceId: (NSString *) deviceId
{
  [outProtocol writeMessageBeginWithName: @"authenticateDevice" type: TMessageType_CALL sequenceID: 0];
  [outProtocol writeStructBeginWithName: @"authenticateDevice_args"];
  if (UserAuthenticationToken != nil)  {
    [outProtocol writeFieldBeginWithName: @"UserAuthenticationToken" type: TType_STRUCT fieldID: 1];
    [UserAuthenticationToken write: outProtocol];
    [outProtocol writeFieldEnd];
  }
  if (deviceId != nil)  {
    [outProtocol writeFieldBeginWithName: @"deviceId" type: TType_STRING fieldID: 2];
    [outProtocol writeString: deviceId];
    [outProtocol writeFieldEnd];
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
  [outProtocol writeMessageEnd];
  [[outProtocol transport] flush];
}

- (DeviceAuthenticationResult *) recv_authenticateDevice
{
  int msgType = 0;
  [inProtocol readMessageBeginReturningName: nil type: &msgType sequenceID: NULL];
  if (msgType == TMessageType_EXCEPTION) {
    TApplicationException * x = [TApplicationException read: inProtocol];
    [inProtocol readMessageEnd];
    @throw x;
  }
  AuthenticateDevice_result * result = [[[AuthenticateDevice_result alloc] init] autorelease_stub];
  [result read: inProtocol];
  [inProtocol readMessageEnd];
  if ([result successIsSet]) {
    return [result success];
  }
  @throw [TApplicationException exceptionWithType: TApplicationException_MISSING_RESULT
                                           reason: @"authenticateDevice failed: unknown result"];
}

- (DeviceAuthenticationResult *) authenticateDevice: (AuthenticationToken*) UserAuthenticationToken deviceId: (NSString *) deviceId
{
  [self send_authenticateDevice : UserAuthenticationToken deviceId: deviceId];
  return [self recv_authenticateDevice];
}

- (void) send_deauthenticate: (AuthenticationToken*) token
{
  [outProtocol writeMessageBeginWithName: @"deauthenticate" type: TMessageType_CALL sequenceID: 0];
  [outProtocol writeStructBeginWithName: @"deauthenticate_args"];
  if (token != nil)  {
    [outProtocol writeFieldBeginWithName: @"token" type: TType_STRUCT fieldID: 1];
    [token write: outProtocol];
    [outProtocol writeFieldEnd];
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
  [outProtocol writeMessageEnd];
  [[outProtocol transport] flush];
}

- (void) recv_deauthenticate
{
  int msgType = 0;
  [inProtocol readMessageBeginReturningName: nil type: &msgType sequenceID: NULL];
  if (msgType == TMessageType_EXCEPTION) {
    TApplicationException * x = [TApplicationException read: inProtocol];
    [inProtocol readMessageEnd];
    @throw x;
  }
  Deauthenticate_result * result = [[[Deauthenticate_result alloc] init] autorelease_stub];
  [result read: inProtocol];
  [inProtocol readMessageEnd];
  return;
}

- (void) deauthenticate: (AuthenticationToken*) token
{
  [self send_deauthenticate : token];
  [self recv_deauthenticate];
}

@end

@implementation AuthenticationServiceProcessor

- (id) initWithAuthenticationService: (id <AuthenticationService>) service
{
  self = [super init];
  if (!self) {
    return nil;
  }
  mService = [service retain_stub];
  mMethodMap = [[NSMutableDictionary dictionary] retain_stub];
  {
    SEL s = @selector(process_authenticateCompany_withSequenceID:inProtocol:outProtocol:);
    NSMethodSignature * sig = [self methodSignatureForSelector: s];
    NSInvocation * invocation = [NSInvocation invocationWithMethodSignature: sig];
    [invocation setSelector: s];
    [invocation retainArguments];
    [mMethodMap setValue: invocation forKey: @"authenticateCompany"];
  }
  {
    SEL s = @selector(process_authenticateUser_withSequenceID:inProtocol:outProtocol:);
    NSMethodSignature * sig = [self methodSignatureForSelector: s];
    NSInvocation * invocation = [NSInvocation invocationWithMethodSignature: sig];
    [invocation setSelector: s];
    [invocation retainArguments];
    [mMethodMap setValue: invocation forKey: @"authenticateUser"];
  }
  {
    SEL s = @selector(process_authenticateDevice_withSequenceID:inProtocol:outProtocol:);
    NSMethodSignature * sig = [self methodSignatureForSelector: s];
    NSInvocation * invocation = [NSInvocation invocationWithMethodSignature: sig];
    [invocation setSelector: s];
    [invocation retainArguments];
    [mMethodMap setValue: invocation forKey: @"authenticateDevice"];
  }
  {
    SEL s = @selector(process_deauthenticate_withSequenceID:inProtocol:outProtocol:);
    NSMethodSignature * sig = [self methodSignatureForSelector: s];
    NSInvocation * invocation = [NSInvocation invocationWithMethodSignature: sig];
    [invocation setSelector: s];
    [invocation retainArguments];
    [mMethodMap setValue: invocation forKey: @"deauthenticate"];
  }
  return self;
}

- (id<AuthenticationService>) service
{
  return [[mService retain_stub] autorelease_stub];
}

- (BOOL) processOnInputProtocol: (id <TProtocol>) inProtocol
                 outputProtocol: (id <TProtocol>) outProtocol
{
  NSString * messageName;
  int messageType;
  int seqID;
  [inProtocol readMessageBeginReturningName: &messageName
                                       type: &messageType
                                 sequenceID: &seqID];
  NSInvocation * invocation = [mMethodMap valueForKey: messageName];
  if (invocation == nil) {
    [TProtocolUtil skipType: TType_STRUCT onProtocol: inProtocol];
    [inProtocol readMessageEnd];
    TApplicationException * x = [TApplicationException exceptionWithType: TApplicationException_UNKNOWN_METHOD reason: [NSString stringWithFormat: @"Invalid method name: '%@'", messageName]];
    [outProtocol writeMessageBeginWithName: messageName
                                      type: TMessageType_EXCEPTION
                                sequenceID: seqID];
    [x write: outProtocol];
    [outProtocol writeMessageEnd];
    [[outProtocol transport] flush];
    return YES;
  }
  // NSInvocation does not conform to NSCopying protocol
  NSInvocation * i = [NSInvocation invocationWithMethodSignature: [invocation methodSignature]];
  [i setSelector: [invocation selector]];
  [i setArgument: &seqID atIndex: 2];
  [i setArgument: &inProtocol atIndex: 3];
  [i setArgument: &outProtocol atIndex: 4];
  [i setTarget: self];
  [i invoke];
  return YES;
}

- (void) process_authenticateCompany_withSequenceID: (int32_t) seqID inProtocol: (id<TProtocol>) inProtocol outProtocol: (id<TProtocol>) outProtocol
{
  authenticateCompany_args * args = [[authenticateCompany_args alloc] init];
  [args read: inProtocol];
  [inProtocol readMessageEnd];
  AuthenticateCompany_result * result = [[AuthenticateCompany_result alloc] init];
  [result setSuccess: [mService authenticateCompany: [args companyId] companySecret: [args companySecret]]];
  [outProtocol writeMessageBeginWithName: @"authenticateCompany"
                                    type: TMessageType_REPLY
                              sequenceID: seqID];
  [result write: outProtocol];
  [outProtocol writeMessageEnd];
  [[outProtocol transport] flush];
  [result release_stub];
  [args release_stub];
}

- (void) process_authenticateUser_withSequenceID: (int32_t) seqID inProtocol: (id<TProtocol>) inProtocol outProtocol: (id<TProtocol>) outProtocol
{
  authenticateUser_args * args = [[authenticateUser_args alloc] init];
  [args read: inProtocol];
  [inProtocol readMessageEnd];
  AuthenticateUser_result * result = [[AuthenticateUser_result alloc] init];
  [result setSuccess: [mService authenticateUser: [args companyAuthenticationToken] userPrincipal: [args userPrincipal] userCredentials: [args userCredentials]]];
  [outProtocol writeMessageBeginWithName: @"authenticateUser"
                                    type: TMessageType_REPLY
                              sequenceID: seqID];
  [result write: outProtocol];
  [outProtocol writeMessageEnd];
  [[outProtocol transport] flush];
  [result release_stub];
  [args release_stub];
}

- (void) process_authenticateDevice_withSequenceID: (int32_t) seqID inProtocol: (id<TProtocol>) inProtocol outProtocol: (id<TProtocol>) outProtocol
{
  authenticateDevice_args * args = [[authenticateDevice_args alloc] init];
  [args read: inProtocol];
  [inProtocol readMessageEnd];
  AuthenticateDevice_result * result = [[AuthenticateDevice_result alloc] init];
  [result setSuccess: [mService authenticateDevice: [args UserAuthenticationToken] deviceId: [args deviceId]]];
  [outProtocol writeMessageBeginWithName: @"authenticateDevice"
                                    type: TMessageType_REPLY
                              sequenceID: seqID];
  [result write: outProtocol];
  [outProtocol writeMessageEnd];
  [[outProtocol transport] flush];
  [result release_stub];
  [args release_stub];
}

- (void) process_deauthenticate_withSequenceID: (int32_t) seqID inProtocol: (id<TProtocol>) inProtocol outProtocol: (id<TProtocol>) outProtocol
{
  deauthenticate_args * args = [[deauthenticate_args alloc] init];
  [args read: inProtocol];
  [inProtocol readMessageEnd];
  Deauthenticate_result * result = [[Deauthenticate_result alloc] init];
  [mService deauthenticate: [args token]];
  [outProtocol writeMessageBeginWithName: @"deauthenticate"
                                    type: TMessageType_REPLY
                              sequenceID: seqID];
  [result write: outProtocol];
  [outProtocol writeMessageEnd];
  [[outProtocol transport] flush];
  [result release_stub];
  [args release_stub];
}

- (void) dealloc
{
  [mService release_stub];
  [mMethodMap release_stub];
  [super dealloc_stub];
}

@end

