/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import <thrift/TProtocol.h>
#import <thrift/TApplicationException.h>
#import <thrift/TProtocolException.h>
#import <thrift/TProtocolUtil.h>
#import <thrift/TProcessor.h>
#import <thrift/TObjective-C.h>
#import <thrift/TBase.h>

#import "shared.h"

#import "file.h"

@implementation FileTransferSession

- (id) init
{
  self = [super init];
#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
  self.currentIndex = 0;

#endif
  return self;
}

- (id) initWithId: (NSString *) id bucketCount: (int64_t) bucketCount currentIndex: (int64_t) currentIndex file: (File *) file
{
  self = [super init];
  __id = [id retain_stub];
  __id_isset = YES;
  __bucketCount = bucketCount;
  __bucketCount_isset = YES;
  __currentIndex = currentIndex;
  __currentIndex_isset = YES;
  __file = [file retain_stub];
  __file_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"id"])
  {
    __id = [[decoder decodeObjectForKey: @"id"] retain_stub];
    __id_isset = YES;
  }
  if ([decoder containsValueForKey: @"bucketCount"])
  {
    __bucketCount = [decoder decodeInt64ForKey: @"bucketCount"];
    __bucketCount_isset = YES;
  }
  if ([decoder containsValueForKey: @"currentIndex"])
  {
    __currentIndex = [decoder decodeInt64ForKey: @"currentIndex"];
    __currentIndex_isset = YES;
  }
  if ([decoder containsValueForKey: @"file"])
  {
    __file = [[decoder decodeObjectForKey: @"file"] retain_stub];
    __file_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__id_isset)
  {
    [encoder encodeObject: __id forKey: @"id"];
  }
  if (__bucketCount_isset)
  {
    [encoder encodeInt64: __bucketCount forKey: @"bucketCount"];
  }
  if (__currentIndex_isset)
  {
    [encoder encodeInt64: __currentIndex forKey: @"currentIndex"];
  }
  if (__file_isset)
  {
    [encoder encodeObject: __file forKey: @"file"];
  }
}

- (void) dealloc
{
  [__id release_stub];
  [__file release_stub];
  [super dealloc_stub];
}

- (NSString *) id {
  return [[__id retain_stub] autorelease_stub];
}

- (void) setId: (NSString *) id {
  [id retain_stub];
  [__id release_stub];
  __id = id;
  __id_isset = YES;
}

- (BOOL) idIsSet {
  return __id_isset;
}

- (void) unsetId {
  [__id release_stub];
  __id = nil;
  __id_isset = NO;
}

- (int64_t) bucketCount {
  return __bucketCount;
}

- (void) setBucketCount: (int64_t) bucketCount {
  __bucketCount = bucketCount;
  __bucketCount_isset = YES;
}

- (BOOL) bucketCountIsSet {
  return __bucketCount_isset;
}

- (void) unsetBucketCount {
  __bucketCount_isset = NO;
}

- (int64_t) currentIndex {
  return __currentIndex;
}

- (void) setCurrentIndex: (int64_t) currentIndex {
  __currentIndex = currentIndex;
  __currentIndex_isset = YES;
}

- (BOOL) currentIndexIsSet {
  return __currentIndex_isset;
}

- (void) unsetCurrentIndex {
  __currentIndex_isset = NO;
}

- (File *) file {
  return [[__file retain_stub] autorelease_stub];
}

- (void) setFile: (File *) file {
  [file retain_stub];
  [__file release_stub];
  __file = file;
  __file_isset = YES;
}

- (BOOL) fileIsSet {
  return __file_isset;
}

- (void) unsetFile {
  [__file release_stub];
  __file = nil;
  __file_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setId: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setBucketCount: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 3:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setCurrentIndex: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 4:
        if (fieldType == TType_STRUCT) {
          File *fieldValue = [[File alloc] init];
          [fieldValue read: inProtocol];
          [self setFile: fieldValue];
          [fieldValue release_stub];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"FileTransferSession"];
  if (__id_isset) {
    if (__id != nil) {
      [outProtocol writeFieldBeginWithName: @"id" type: TType_STRING fieldID: 1];
      [outProtocol writeString: __id];
      [outProtocol writeFieldEnd];
    }
  }
  if (__bucketCount_isset) {
    [outProtocol writeFieldBeginWithName: @"bucketCount" type: TType_I64 fieldID: 2];
    [outProtocol writeI64: __bucketCount];
    [outProtocol writeFieldEnd];
  }
  if (__currentIndex_isset) {
    [outProtocol writeFieldBeginWithName: @"currentIndex" type: TType_I64 fieldID: 3];
    [outProtocol writeI64: __currentIndex];
    [outProtocol writeFieldEnd];
  }
  if (__file_isset) {
    if (__file != nil) {
      [outProtocol writeFieldBeginWithName: @"file" type: TType_STRUCT fieldID: 4];
      [__file write: outProtocol];
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (void) validate {
  // check for required fields
  if (!__id_isset) {
    @throw [TProtocolException exceptionWithName: @"TProtocolException"
                               reason: @"Required field 'id' is not set."];
  }
  if (!__bucketCount_isset) {
    @throw [TProtocolException exceptionWithName: @"TProtocolException"
                               reason: @"Required field 'bucketCount' is not set."];
  }
  if (!__currentIndex_isset) {
    @throw [TProtocolException exceptionWithName: @"TProtocolException"
                               reason: @"Required field 'currentIndex' is not set."];
  }
  if (!__file_isset) {
    @throw [TProtocolException exceptionWithName: @"TProtocolException"
                               reason: @"Required field 'file' is not set."];
  }
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"FileTransferSession("];
  [ms appendString: @"id:"];
  [ms appendFormat: @"\"%@\"", __id];
  [ms appendString: @",bucketCount:"];
  [ms appendFormat: @"%qi", __bucketCount];
  [ms appendString: @",currentIndex:"];
  [ms appendFormat: @"%qi", __currentIndex];
  [ms appendString: @",file:"];
  [ms appendFormat: @"%@", __file];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end


@implementation fileConstants
+ (void) initialize {
}
@end

@interface initiateSession_args : NSObject <TBase, NSCoding> {
  File *__file;
  int64_t __bucketSize;

  BOOL __file_isset;
  BOOL __bucketSize_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=file, setter=setFile:) File *file;
@property (nonatomic, getter=bucketSize, setter=setBucketSize:) int64_t bucketSize;
#endif

- (id) init;
- (id) initWithFile: (File *) file bucketSize: (int64_t) bucketSize;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (File) file;
- (void) setFile: (File) file;
#endif
- (BOOL) fileIsSet;

#if !__has_feature(objc_arc)
- (int64_t) bucketSize;
- (void) setBucketSize: (int64_t) bucketSize;
#endif
- (BOOL) bucketSizeIsSet;

@end

@implementation initiateSession_args

- (id) init
{
  self = [super init];
#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
#endif
  return self;
}

- (id) initWithFile: (File *) file bucketSize: (int64_t) bucketSize
{
  self = [super init];
  __file = [file retain_stub];
  __file_isset = YES;
  __bucketSize = bucketSize;
  __bucketSize_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"file"])
  {
    __file = [[decoder decodeObjectForKey: @"file"] retain_stub];
    __file_isset = YES;
  }
  if ([decoder containsValueForKey: @"bucketSize"])
  {
    __bucketSize = [decoder decodeInt64ForKey: @"bucketSize"];
    __bucketSize_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__file_isset)
  {
    [encoder encodeObject: __file forKey: @"file"];
  }
  if (__bucketSize_isset)
  {
    [encoder encodeInt64: __bucketSize forKey: @"bucketSize"];
  }
}

- (void) dealloc
{
  [__file release_stub];
  [super dealloc_stub];
}

- (File *) file {
  return [[__file retain_stub] autorelease_stub];
}

- (void) setFile: (File *) file {
  [file retain_stub];
  [__file release_stub];
  __file = file;
  __file_isset = YES;
}

- (BOOL) fileIsSet {
  return __file_isset;
}

- (void) unsetFile {
  [__file release_stub];
  __file = nil;
  __file_isset = NO;
}

- (int64_t) bucketSize {
  return __bucketSize;
}

- (void) setBucketSize: (int64_t) bucketSize {
  __bucketSize = bucketSize;
  __bucketSize_isset = YES;
}

- (BOOL) bucketSizeIsSet {
  return __bucketSize_isset;
}

- (void) unsetBucketSize {
  __bucketSize_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_STRUCT) {
          File *fieldValue = [[File alloc] init];
          [fieldValue read: inProtocol];
          [self setFile: fieldValue];
          [fieldValue release_stub];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setBucketSize: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"initiateSession_args"];
  if (__file_isset) {
    if (__file != nil) {
      [outProtocol writeFieldBeginWithName: @"file" type: TType_STRUCT fieldID: 1];
      [__file write: outProtocol];
      [outProtocol writeFieldEnd];
    }
  }
  if (__bucketSize_isset) {
    [outProtocol writeFieldBeginWithName: @"bucketSize" type: TType_I64 fieldID: 2];
    [outProtocol writeI64: __bucketSize];
    [outProtocol writeFieldEnd];
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (void) validate {
  // check for required fields
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"initiateSession_args("];
  [ms appendString: @"file:"];
  [ms appendFormat: @"%@", __file];
  [ms appendString: @",bucketSize:"];
  [ms appendFormat: @"%qi", __bucketSize];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@interface InitiateSession_result : NSObject <TBase, NSCoding> {
  FileTransferSession * __success;

  BOOL __success_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=success, setter=setSuccess:) FileTransferSession * success;
#endif

- (id) init;
- (id) initWithSuccess: (FileTransferSession *) success;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (FileTransferSession *) success;
- (void) setSuccess: (FileTransferSession *) success;
#endif
- (BOOL) successIsSet;

@end

@implementation InitiateSession_result

- (id) init
{
  self = [super init];
#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
#endif
  return self;
}

- (id) initWithSuccess: (FileTransferSession *) success
{
  self = [super init];
  __success = [success retain_stub];
  __success_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"success"])
  {
    __success = [[decoder decodeObjectForKey: @"success"] retain_stub];
    __success_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__success_isset)
  {
    [encoder encodeObject: __success forKey: @"success"];
  }
}

- (void) dealloc
{
  [__success release_stub];
  [super dealloc_stub];
}

- (FileTransferSession *) success {
  return [[__success retain_stub] autorelease_stub];
}

- (void) setSuccess: (FileTransferSession *) success {
  [success retain_stub];
  [__success release_stub];
  __success = success;
  __success_isset = YES;
}

- (BOOL) successIsSet {
  return __success_isset;
}

- (void) unsetSuccess {
  [__success release_stub];
  __success = nil;
  __success_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 0:
        if (fieldType == TType_STRUCT) {
          FileTransferSession *fieldValue = [[FileTransferSession alloc] init];
          [fieldValue read: inProtocol];
          [self setSuccess: fieldValue];
          [fieldValue release_stub];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"InitiateSession_result"];

  if (__success_isset) {
    if (__success != nil) {
      [outProtocol writeFieldBeginWithName: @"success" type: TType_STRUCT fieldID: 0];
      [__success write: outProtocol];
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (void) validate {
  // check for required fields
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"InitiateSession_result("];
  [ms appendString: @"success:"];
  [ms appendFormat: @"%@", __success];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@interface destroySession_args : NSObject <TBase, NSCoding> {
  FileTransferSession * __session;

  BOOL __session_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=session, setter=setSession:) FileTransferSession * session;
#endif

- (id) init;
- (id) initWithSession: (FileTransferSession *) session;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (FileTransferSession *) session;
- (void) setSession: (FileTransferSession *) session;
#endif
- (BOOL) sessionIsSet;

@end

@implementation destroySession_args

- (id) init
{
  self = [super init];
#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
#endif
  return self;
}

- (id) initWithSession: (FileTransferSession *) session
{
  self = [super init];
  __session = [session retain_stub];
  __session_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"session"])
  {
    __session = [[decoder decodeObjectForKey: @"session"] retain_stub];
    __session_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__session_isset)
  {
    [encoder encodeObject: __session forKey: @"session"];
  }
}

- (void) dealloc
{
  [__session release_stub];
  [super dealloc_stub];
}

- (FileTransferSession *) session {
  return [[__session retain_stub] autorelease_stub];
}

- (void) setSession: (FileTransferSession *) session {
  [session retain_stub];
  [__session release_stub];
  __session = session;
  __session_isset = YES;
}

- (BOOL) sessionIsSet {
  return __session_isset;
}

- (void) unsetSession {
  [__session release_stub];
  __session = nil;
  __session_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_STRUCT) {
          FileTransferSession *fieldValue = [[FileTransferSession alloc] init];
          [fieldValue read: inProtocol];
          [self setSession: fieldValue];
          [fieldValue release_stub];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"destroySession_args"];
  if (__session_isset) {
    if (__session != nil) {
      [outProtocol writeFieldBeginWithName: @"session" type: TType_STRUCT fieldID: 1];
      [__session write: outProtocol];
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (void) validate {
  // check for required fields
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"destroySession_args("];
  [ms appendString: @"session:"];
  [ms appendFormat: @"%@", __session];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@interface DestroySession_result : NSObject <TBase, NSCoding> {
}

- (id) init;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

@end

@implementation DestroySession_result

- (id) init
{
  self = [super init];
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"DestroySession_result"];

  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (void) validate {
  // check for required fields
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"DestroySession_result("];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@interface fetchBucket_args : NSObject <TBase, NSCoding> {
  FileTransferSession * __session;

  BOOL __session_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=session, setter=setSession:) FileTransferSession * session;
#endif

- (id) init;
- (id) initWithSession: (FileTransferSession *) session;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (FileTransferSession *) session;
- (void) setSession: (FileTransferSession *) session;
#endif
- (BOOL) sessionIsSet;

@end

@implementation fetchBucket_args

- (id) init
{
  self = [super init];
#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
#endif
  return self;
}

- (id) initWithSession: (FileTransferSession *) session
{
  self = [super init];
  __session = [session retain_stub];
  __session_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"session"])
  {
    __session = [[decoder decodeObjectForKey: @"session"] retain_stub];
    __session_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__session_isset)
  {
    [encoder encodeObject: __session forKey: @"session"];
  }
}

- (void) dealloc
{
  [__session release_stub];
  [super dealloc_stub];
}

- (FileTransferSession *) session {
  return [[__session retain_stub] autorelease_stub];
}

- (void) setSession: (FileTransferSession *) session {
  [session retain_stub];
  [__session release_stub];
  __session = session;
  __session_isset = YES;
}

- (BOOL) sessionIsSet {
  return __session_isset;
}

- (void) unsetSession {
  [__session release_stub];
  __session = nil;
  __session_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_STRUCT) {
          FileTransferSession *fieldValue = [[FileTransferSession alloc] init];
          [fieldValue read: inProtocol];
          [self setSession: fieldValue];
          [fieldValue release_stub];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"fetchBucket_args"];
  if (__session_isset) {
    if (__session != nil) {
      [outProtocol writeFieldBeginWithName: @"session" type: TType_STRUCT fieldID: 1];
      [__session write: outProtocol];
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (void) validate {
  // check for required fields
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"fetchBucket_args("];
  [ms appendString: @"session:"];
  [ms appendFormat: @"%@", __session];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@interface FetchBucket_result : NSObject <TBase, NSCoding> {
  NSData * __success;

  BOOL __success_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=success, setter=setSuccess:) NSData * success;
#endif

- (id) init;
- (id) initWithSuccess: (NSData *) success;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSData *) success;
- (void) setSuccess: (NSData *) success;
#endif
- (BOOL) successIsSet;

@end

@implementation FetchBucket_result

- (id) init
{
  self = [super init];
#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
#endif
  return self;
}

- (id) initWithSuccess: (NSData *) success
{
  self = [super init];
  __success = [success retain_stub];
  __success_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"success"])
  {
    __success = [[decoder decodeObjectForKey: @"success"] retain_stub];
    __success_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__success_isset)
  {
    [encoder encodeObject: __success forKey: @"success"];
  }
}

- (void) dealloc
{
  [__success release_stub];
  [super dealloc_stub];
}

- (NSData *) success {
  return [[__success retain_stub] autorelease_stub];
}

- (void) setSuccess: (NSData *) success {
  [success retain_stub];
  [__success release_stub];
  __success = success;
  __success_isset = YES;
}

- (BOOL) successIsSet {
  return __success_isset;
}

- (void) unsetSuccess {
  [__success release_stub];
  __success = nil;
  __success_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 0:
        if (fieldType == TType_STRING) {
          NSData * fieldValue = [inProtocol readBinary];
          [self setSuccess: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"FetchBucket_result"];

  if (__success_isset) {
    if (__success != nil) {
      [outProtocol writeFieldBeginWithName: @"success" type: TType_STRING fieldID: 0];
      [outProtocol writeBinary: __success];
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (void) validate {
  // check for required fields
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"FetchBucket_result("];
  [ms appendString: @"success:"];
  [ms appendFormat: @"\"%@\"", __success];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@implementation FileTransferServiceClient
- (id) initWithProtocol: (id <TProtocol>) protocol
{
  return [self initWithInProtocol: protocol outProtocol: protocol];
}

- (id) initWithInProtocol: (id <TProtocol>) anInProtocol outProtocol: (id <TProtocol>) anOutProtocol
{
  self = [super init];
  inProtocol = [anInProtocol retain_stub];
  outProtocol = [anOutProtocol retain_stub];
  return self;
}

- (void) dealloc
{
  [inProtocol release_stub];
  [outProtocol release_stub];
  [super dealloc_stub];
}

- (void) send_initiateSession: (File *) file bucketSize: (int64_t) bucketSize
{
  [outProtocol writeMessageBeginWithName: @"initiateSession" type: TMessageType_CALL sequenceID: 0];
  [outProtocol writeStructBeginWithName: @"initiateSession_args"];
  if (file != nil)  {
    [outProtocol writeFieldBeginWithName: @"file" type: TType_STRUCT fieldID: 1];
    [file write: outProtocol];
    [outProtocol writeFieldEnd];
  }
  [outProtocol writeFieldBeginWithName: @"bucketSize" type: TType_I64 fieldID: 2];
  [outProtocol writeI64: bucketSize];
  [outProtocol writeFieldEnd];
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
  [outProtocol writeMessageEnd];
  [[outProtocol transport] flush];
}

- (FileTransferSession *) recv_initiateSession
{
  int msgType = 0;
  [inProtocol readMessageBeginReturningName: nil type: &msgType sequenceID: NULL];
  if (msgType == TMessageType_EXCEPTION) {
    TApplicationException * x = [TApplicationException read: inProtocol];
    [inProtocol readMessageEnd];
    @throw x;
  }
  InitiateSession_result * result = [[[InitiateSession_result alloc] init] autorelease_stub];
  [result read: inProtocol];
  [inProtocol readMessageEnd];
  if ([result successIsSet]) {
    return [result success];
  }
  @throw [TApplicationException exceptionWithType: TApplicationException_MISSING_RESULT
                                           reason: @"initiateSession failed: unknown result"];
}

- (FileTransferSession *) initiateSession: (File *) file bucketSize: (int64_t) bucketSize
{
  [self send_initiateSession : file bucketSize: bucketSize];
  return [self recv_initiateSession];
}

- (void) send_destroySession: (FileTransferSession *) session
{
  [outProtocol writeMessageBeginWithName: @"destroySession" type: TMessageType_CALL sequenceID: 0];
  [outProtocol writeStructBeginWithName: @"destroySession_args"];
  if (session != nil)  {
    [outProtocol writeFieldBeginWithName: @"session" type: TType_STRUCT fieldID: 1];
    [session write: outProtocol];
    [outProtocol writeFieldEnd];
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
  [outProtocol writeMessageEnd];
  [[outProtocol transport] flush];
}

- (void) recv_destroySession
{
  int msgType = 0;
  [inProtocol readMessageBeginReturningName: nil type: &msgType sequenceID: NULL];
  if (msgType == TMessageType_EXCEPTION) {
    TApplicationException * x = [TApplicationException read: inProtocol];
    [inProtocol readMessageEnd];
    @throw x;
  }
  DestroySession_result * result = [[[DestroySession_result alloc] init] autorelease_stub];
  [result read: inProtocol];
  [inProtocol readMessageEnd];
  return;
}

- (void) destroySession: (FileTransferSession *) session
{
  [self send_destroySession : session];
  [self recv_destroySession];
}

- (void) send_fetchBucket: (FileTransferSession *) session
{
  [outProtocol writeMessageBeginWithName: @"fetchBucket" type: TMessageType_CALL sequenceID: 0];
  [outProtocol writeStructBeginWithName: @"fetchBucket_args"];
  if (session != nil)  {
    [outProtocol writeFieldBeginWithName: @"session" type: TType_STRUCT fieldID: 1];
    [session write: outProtocol];
    [outProtocol writeFieldEnd];
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
  [outProtocol writeMessageEnd];
  [[outProtocol transport] flush];
}

- (NSData *) recv_fetchBucket
{
  int msgType = 0;
  [inProtocol readMessageBeginReturningName: nil type: &msgType sequenceID: NULL];
  if (msgType == TMessageType_EXCEPTION) {
    TApplicationException * x = [TApplicationException read: inProtocol];
    [inProtocol readMessageEnd];
    @throw x;
  }
  FetchBucket_result * result = [[[FetchBucket_result alloc] init] autorelease_stub];
  [result read: inProtocol];
  [inProtocol readMessageEnd];
  if ([result successIsSet]) {
    return [result success];
  }
  @throw [TApplicationException exceptionWithType: TApplicationException_MISSING_RESULT
                                           reason: @"fetchBucket failed: unknown result"];
}

- (NSData *) fetchBucket: (FileTransferSession *) session
{
  [self send_fetchBucket : session];
  return [self recv_fetchBucket];
}

@end

@implementation FileTransferServiceProcessor

- (id) initWithFileTransferService: (id <FileTransferService>) service
{
  self = [super init];
  if (!self) {
    return nil;
  }
  mService = [service retain_stub];
  mMethodMap = [[NSMutableDictionary dictionary] retain_stub];
  {
    SEL s = @selector(process_initiateSession_withSequenceID:inProtocol:outProtocol:);
    NSMethodSignature * sig = [self methodSignatureForSelector: s];
    NSInvocation * invocation = [NSInvocation invocationWithMethodSignature: sig];
    [invocation setSelector: s];
    [invocation retainArguments];
    [mMethodMap setValue: invocation forKey: @"initiateSession"];
  }
  {
    SEL s = @selector(process_destroySession_withSequenceID:inProtocol:outProtocol:);
    NSMethodSignature * sig = [self methodSignatureForSelector: s];
    NSInvocation * invocation = [NSInvocation invocationWithMethodSignature: sig];
    [invocation setSelector: s];
    [invocation retainArguments];
    [mMethodMap setValue: invocation forKey: @"destroySession"];
  }
  {
    SEL s = @selector(process_fetchBucket_withSequenceID:inProtocol:outProtocol:);
    NSMethodSignature * sig = [self methodSignatureForSelector: s];
    NSInvocation * invocation = [NSInvocation invocationWithMethodSignature: sig];
    [invocation setSelector: s];
    [invocation retainArguments];
    [mMethodMap setValue: invocation forKey: @"fetchBucket"];
  }
  return self;
}

- (id<FileTransferService>) service
{
  return [[mService retain_stub] autorelease_stub];
}

- (BOOL) processOnInputProtocol: (id <TProtocol>) inProtocol
                 outputProtocol: (id <TProtocol>) outProtocol
{
  NSString * messageName;
  int messageType;
  int seqID;
  [inProtocol readMessageBeginReturningName: &messageName
                                       type: &messageType
                                 sequenceID: &seqID];
  NSInvocation * invocation = [mMethodMap valueForKey: messageName];
  if (invocation == nil) {
    [TProtocolUtil skipType: TType_STRUCT onProtocol: inProtocol];
    [inProtocol readMessageEnd];
    TApplicationException * x = [TApplicationException exceptionWithType: TApplicationException_UNKNOWN_METHOD reason: [NSString stringWithFormat: @"Invalid method name: '%@'", messageName]];
    [outProtocol writeMessageBeginWithName: messageName
                                      type: TMessageType_EXCEPTION
                                sequenceID: seqID];
    [x write: outProtocol];
    [outProtocol writeMessageEnd];
    [[outProtocol transport] flush];
    return YES;
  }
  // NSInvocation does not conform to NSCopying protocol
  NSInvocation * i = [NSInvocation invocationWithMethodSignature: [invocation methodSignature]];
  [i setSelector: [invocation selector]];
  [i setArgument: &seqID atIndex: 2];
  [i setArgument: &inProtocol atIndex: 3];
  [i setArgument: &outProtocol atIndex: 4];
  [i setTarget: self];
  [i invoke];
  return YES;
}

- (void) process_initiateSession_withSequenceID: (int32_t) seqID inProtocol: (id<TProtocol>) inProtocol outProtocol: (id<TProtocol>) outProtocol
{
  initiateSession_args * args = [[initiateSession_args alloc] init];
  [args read: inProtocol];
  [inProtocol readMessageEnd];
  InitiateSession_result * result = [[InitiateSession_result alloc] init];
  [result setSuccess: [mService initiateSession: [args file] bucketSize: [args bucketSize]]];
  [outProtocol writeMessageBeginWithName: @"initiateSession"
                                    type: TMessageType_REPLY
                              sequenceID: seqID];
  [result write: outProtocol];
  [outProtocol writeMessageEnd];
  [[outProtocol transport] flush];
  [result release_stub];
  [args release_stub];
}

- (void) process_destroySession_withSequenceID: (int32_t) seqID inProtocol: (id<TProtocol>) inProtocol outProtocol: (id<TProtocol>) outProtocol
{
  destroySession_args * args = [[destroySession_args alloc] init];
  [args read: inProtocol];
  [inProtocol readMessageEnd];
  DestroySession_result * result = [[DestroySession_result alloc] init];
  [mService destroySession: [args session]];
  [outProtocol writeMessageBeginWithName: @"destroySession"
                                    type: TMessageType_REPLY
                              sequenceID: seqID];
  [result write: outProtocol];
  [outProtocol writeMessageEnd];
  [[outProtocol transport] flush];
  [result release_stub];
  [args release_stub];
}

- (void) process_fetchBucket_withSequenceID: (int32_t) seqID inProtocol: (id<TProtocol>) inProtocol outProtocol: (id<TProtocol>) outProtocol
{
  fetchBucket_args * args = [[fetchBucket_args alloc] init];
  [args read: inProtocol];
  [inProtocol readMessageEnd];
  FetchBucket_result * result = [[FetchBucket_result alloc] init];
  [result setSuccess: [mService fetchBucket: [args session]]];
  [outProtocol writeMessageBeginWithName: @"fetchBucket"
                                    type: TMessageType_REPLY
                              sequenceID: seqID];
  [result write: outProtocol];
  [outProtocol writeMessageEnd];
  [[outProtocol transport] flush];
  [result release_stub];
  [args release_stub];
}

- (void) dealloc
{
  [mService release_stub];
  [mMethodMap release_stub];
  [super dealloc_stub];
}

@end

