/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import <thrift/TProtocol.h>
#import <thrift/TApplicationException.h>
#import <thrift/TProtocolException.h>
#import <thrift/TProtocolUtil.h>
#import <thrift/TProcessor.h>
#import <thrift/TObjective-C.h>
#import <thrift/TBase.h>

#import "shared.h"

@interface FileTransferSession : NSObject <TBase, NSCoding> {
  NSString * __id;
  int64_t __bucketCount;
  int64_t __currentIndex;
  File *__file;

  BOOL __id_isset;
  BOOL __bucketCount_isset;
  BOOL __currentIndex_isset;
  BOOL __file_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=id, setter=setId:) NSString * id;
@property (nonatomic, getter=bucketCount, setter=setBucketCount:) int64_t bucketCount;
@property (nonatomic, getter=currentIndex, setter=setCurrentIndex:) int64_t currentIndex;
@property (nonatomic, retain, getter=file, setter=setFile:) File *file;
#endif

- (id) init;
- (id) initWithId: (NSString *) id bucketCount: (int64_t) bucketCount currentIndex: (int64_t) currentIndex file: (File *) file;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) id;
- (void) setId: (NSString *) id;
#endif
- (BOOL) idIsSet;

#if !__has_feature(objc_arc)
- (int64_t) bucketCount;
- (void) setBucketCount: (int64_t) bucketCount;
#endif
- (BOOL) bucketCountIsSet;

#if !__has_feature(objc_arc)
- (int64_t) currentIndex;
- (void) setCurrentIndex: (int64_t) currentIndex;
#endif
- (BOOL) currentIndexIsSet;

#if !__has_feature(objc_arc)
- (File) file;
- (void) setFile: (File) file;
#endif
- (BOOL) fileIsSet;

@end

@protocol FileTransferService <NSObject>
- (FileTransferSession *) initiateSession: (File *) file bucketSize: (int64_t) bucketSize;  // throws TException
- (void) destroySession: (FileTransferSession *) session;  // throws TException
- (NSData *) fetchBucket: (FileTransferSession *) session;  // throws TException
@end

@interface FileTransferServiceClient : NSObject <FileTransferService> {
  id <TProtocol> inProtocol;
  id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface FileTransferServiceProcessor : NSObject <TProcessor> {
  id <FileTransferService> mService;
  NSDictionary * mMethodMap;
}
- (id) initWithFileTransferService: (id <FileTransferService>) service;
- (id<FileTransferService>) service;
@end

@interface fileConstants : NSObject {
}
@end
