/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import <thrift/TProtocol.h>
#import <thrift/TApplicationException.h>
#import <thrift/TProtocolException.h>
#import <thrift/TProtocolUtil.h>
#import <thrift/TProcessor.h>
#import <thrift/TObjective-C.h>
#import <thrift/TBase.h>

#import "shared.h"

@protocol ProvisioningService <NSObject>
- (Profile *) checkProvision: (AuthenticationToken *) token applicationId: (NSString *) applicationId localProfile: (Profile *) localProfile;  // throws TException
@end

@interface ProvisioningServiceClient : NSObject <ProvisioningService> {
  id <TProtocol> inProtocol;
  id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface ProvisioningServiceProcessor : NSObject <TProcessor> {
  id <ProvisioningService> mService;
  NSDictionary * mMethodMap;
}
- (id) initWithProvisioningService: (id <ProvisioningService>) service;
- (id<ProvisioningService>) service;
@end

@interface provisionConstants : NSObject {
}
@end
