/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "shared.h"

#import "serviceobj.h"

@implementation ServiceObject

- (id) init
{
  self = [super init];
#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
#endif
  return self;
}

- (id) initWithName: (NSString *) name type: (NSString *) type operationNames: (NSMutableSet *) operationNames
{
  self = [super init];
  __name = [name retain_stub];
  __name_isset = YES;
  __type = [type retain_stub];
  __type_isset = YES;
  __operationNames = [operationNames retain_stub];
  __operationNames_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"name"])
  {
    __name = [[decoder decodeObjectForKey: @"name"] retain_stub];
    __name_isset = YES;
  }
  if ([decoder containsValueForKey: @"type"])
  {
    __type = [[decoder decodeObjectForKey: @"type"] retain_stub];
    __type_isset = YES;
  }
  if ([decoder containsValueForKey: @"operationNames"])
  {
    __operationNames = [[decoder decodeObjectForKey: @"operationNames"] retain_stub];
    __operationNames_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__name_isset)
  {
    [encoder encodeObject: __name forKey: @"name"];
  }
  if (__type_isset)
  {
    [encoder encodeObject: __type forKey: @"type"];
  }
  if (__operationNames_isset)
  {
    [encoder encodeObject: __operationNames forKey: @"operationNames"];
  }
}

- (void) dealloc
{
  [__name release_stub];
  [__type release_stub];
  [__operationNames release_stub];
  [super dealloc_stub];
}

- (NSString *) name {
  return [[__name retain_stub] autorelease_stub];
}

- (void) setName: (NSString *) name {
  [name retain_stub];
  [__name release_stub];
  __name = name;
  __name_isset = YES;
}

- (BOOL) nameIsSet {
  return __name_isset;
}

- (void) unsetName {
  [__name release_stub];
  __name = nil;
  __name_isset = NO;
}

- (NSString *) type {
  return [[__type retain_stub] autorelease_stub];
}

- (void) setType: (NSString *) type {
  [type retain_stub];
  [__type release_stub];
  __type = type;
  __type_isset = YES;
}

- (BOOL) typeIsSet {
  return __type_isset;
}

- (void) unsetType {
  [__type release_stub];
  __type = nil;
  __type_isset = NO;
}

- (NSMutableSet *) operationNames {
  return [[__operationNames retain_stub] autorelease_stub];
}

- (void) setOperationNames: (NSMutableSet *) operationNames {
  [operationNames retain_stub];
  [__operationNames release_stub];
  __operationNames = operationNames;
  __operationNames_isset = YES;
}

- (BOOL) operationNamesIsSet {
  return __operationNames_isset;
}

- (void) unsetOperationNames {
  [__operationNames release_stub];
  __operationNames = nil;
  __operationNames_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setName: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setType: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 3:
        if (fieldType == TType_SET) {
          int _size0;
          [inProtocol readSetBeginReturningElementType: NULL size: &_size0];
          NSMutableSet * fieldValue = [[NSMutableSet alloc] initWithCapacity: _size0];
          int _i1;
          for (_i1 = 0; _i1 < _size0; ++_i1)
          {
            NSString * _elem2 = [inProtocol readString];
            [fieldValue addObject: _elem2];
          }
          [inProtocol readSetEnd];
          [self setOperationNames: fieldValue];
          [fieldValue release_stub];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"ServiceObject"];
  if (__name_isset) {
    if (__name != nil) {
      [outProtocol writeFieldBeginWithName: @"name" type: TType_STRING fieldID: 1];
      [outProtocol writeString: __name];
      [outProtocol writeFieldEnd];
    }
  }
  if (__type_isset) {
    if (__type != nil) {
      [outProtocol writeFieldBeginWithName: @"type" type: TType_STRING fieldID: 2];
      [outProtocol writeString: __type];
      [outProtocol writeFieldEnd];
    }
  }
  if (__operationNames_isset) {
    if (__operationNames != nil) {
      [outProtocol writeFieldBeginWithName: @"operationNames" type: TType_SET fieldID: 3];
      {
        [outProtocol writeSetBeginWithElementType: TType_STRING size: [__operationNames count]];
        NSEnumerator * _iter3 = [__operationNames objectEnumerator];
        id obj4;
        while ((obj4 = [_iter3 nextObject]))
        {
          [outProtocol writeString: obj4];
        }
        [outProtocol writeSetEnd];
      }
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (void) validate {
  // check for required fields
  if (!__name_isset) {
    @throw [TProtocolException exceptionWithName: @"TProtocolException"
                               reason: @"Required field 'name' is not set."];
  }
  if (!__type_isset) {
    @throw [TProtocolException exceptionWithName: @"TProtocolException"
                               reason: @"Required field 'type' is not set."];
  }
  if (!__operationNames_isset) {
    @throw [TProtocolException exceptionWithName: @"TProtocolException"
                               reason: @"Required field 'operationNames' is not set."];
  }
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"ServiceObject("];
  [ms appendString: @"name:"];
  [ms appendFormat: @"\"%@\"", __name];
  [ms appendString: @",type:"];
  [ms appendFormat: @"\"%@\"", __type];
  [ms appendString: @",operationNames:"];
  [ms appendFormat: @"%@", __operationNames];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@implementation ServiceObjectOperationPayload

- (id) init
{
  self = [super init];
#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
#endif
  return self;
}

- (id) initWithContent: (NSString *) content contentType: (NSString *) contentType rootElement: (NSString *) rootElement
{
  self = [super init];
  __content = [content retain_stub];
  __content_isset = YES;
  __contentType = [contentType retain_stub];
  __contentType_isset = YES;
  __rootElement = [rootElement retain_stub];
  __rootElement_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"content"])
  {
    __content = [[decoder decodeObjectForKey: @"content"] retain_stub];
    __content_isset = YES;
  }
  if ([decoder containsValueForKey: @"contentType"])
  {
    __contentType = [[decoder decodeObjectForKey: @"contentType"] retain_stub];
    __contentType_isset = YES;
  }
  if ([decoder containsValueForKey: @"rootElement"])
  {
    __rootElement = [[decoder decodeObjectForKey: @"rootElement"] retain_stub];
    __rootElement_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__content_isset)
  {
    [encoder encodeObject: __content forKey: @"content"];
  }
  if (__contentType_isset)
  {
    [encoder encodeObject: __contentType forKey: @"contentType"];
  }
  if (__rootElement_isset)
  {
    [encoder encodeObject: __rootElement forKey: @"rootElement"];
  }
}

- (void) dealloc
{
  [__content release_stub];
  [__contentType release_stub];
  [__rootElement release_stub];
  [super dealloc_stub];
}

- (NSString *) content {
  return [[__content retain_stub] autorelease_stub];
}

- (void) setContent: (NSString *) content {
  [content retain_stub];
  [__content release_stub];
  __content = content;
  __content_isset = YES;
}

- (BOOL) contentIsSet {
  return __content_isset;
}

- (void) unsetContent {
  [__content release_stub];
  __content = nil;
  __content_isset = NO;
}

- (NSString *) contentType {
  return [[__contentType retain_stub] autorelease_stub];
}

- (void) setContentType: (NSString *) contentType {
  [contentType retain_stub];
  [__contentType release_stub];
  __contentType = contentType;
  __contentType_isset = YES;
}

- (BOOL) contentTypeIsSet {
  return __contentType_isset;
}

- (void) unsetContentType {
  [__contentType release_stub];
  __contentType = nil;
  __contentType_isset = NO;
}

- (NSString *) rootElement {
  return [[__rootElement retain_stub] autorelease_stub];
}

- (void) setRootElement: (NSString *) rootElement {
  [rootElement retain_stub];
  [__rootElement release_stub];
  __rootElement = rootElement;
  __rootElement_isset = YES;
}

- (BOOL) rootElementIsSet {
  return __rootElement_isset;
}

- (void) unsetRootElement {
  [__rootElement release_stub];
  __rootElement = nil;
  __rootElement_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setContent: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setContentType: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 3:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setRootElement: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"ServiceObjectOperationPayload"];
  if (__content_isset) {
    if (__content != nil) {
      [outProtocol writeFieldBeginWithName: @"content" type: TType_STRING fieldID: 1];
      [outProtocol writeString: __content];
      [outProtocol writeFieldEnd];
    }
  }
  if (__contentType_isset) {
    if (__contentType != nil) {
      [outProtocol writeFieldBeginWithName: @"contentType" type: TType_STRING fieldID: 2];
      [outProtocol writeString: __contentType];
      [outProtocol writeFieldEnd];
    }
  }
  if (__rootElement_isset) {
    if (__rootElement != nil) {
      [outProtocol writeFieldBeginWithName: @"rootElement" type: TType_STRING fieldID: 3];
      [outProtocol writeString: __rootElement];
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (void) validate {
  // check for required fields
  if (!__content_isset) {
    @throw [TProtocolException exceptionWithName: @"TProtocolException"
                               reason: @"Required field 'content' is not set."];
  }
  if (!__contentType_isset) {
    @throw [TProtocolException exceptionWithName: @"TProtocolException"
                               reason: @"Required field 'contentType' is not set."];
  }
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"ServiceObjectOperationPayload("];
  [ms appendString: @"content:"];
  [ms appendFormat: @"\"%@\"", __content];
  [ms appendString: @",contentType:"];
  [ms appendFormat: @"\"%@\"", __contentType];
  [ms appendString: @",rootElement:"];
  [ms appendFormat: @"\"%@\"", __rootElement];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@implementation ServiceObjectNotFoundError

- (id) init
{
  return [super initWithName: @"ServiceObjectNotFoundError" reason: @"unknown" userInfo: nil];
}

- (id) initWithServiceObjectName: (NSString *) serviceObjectName
{
  self = [self init];
  __serviceObjectName = [serviceObjectName retain_stub];
  __serviceObjectName_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super initWithCoder: decoder];
  if ([decoder containsValueForKey: @"serviceObjectName"])
  {
    __serviceObjectName = [[decoder decodeObjectForKey: @"serviceObjectName"] retain_stub];
    __serviceObjectName_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  [super encodeWithCoder: encoder];
  if (__serviceObjectName_isset)
  {
    [encoder encodeObject: __serviceObjectName forKey: @"serviceObjectName"];
  }
}

- (void) dealloc
{
  [__serviceObjectName release_stub];
  [super dealloc_stub];
}

- (NSString *) serviceObjectName {
  return [[__serviceObjectName retain_stub] autorelease_stub];
}

- (void) setServiceObjectName: (NSString *) serviceObjectName {
  [serviceObjectName retain_stub];
  [__serviceObjectName release_stub];
  __serviceObjectName = serviceObjectName;
  __serviceObjectName_isset = YES;
}

- (BOOL) serviceObjectNameIsSet {
  return __serviceObjectName_isset;
}

- (void) unsetServiceObjectName {
  [__serviceObjectName release_stub];
  __serviceObjectName = nil;
  __serviceObjectName_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setServiceObjectName: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"ServiceObjectNotFoundError"];
  if (__serviceObjectName_isset) {
    if (__serviceObjectName != nil) {
      [outProtocol writeFieldBeginWithName: @"serviceObjectName" type: TType_STRING fieldID: 1];
      [outProtocol writeString: __serviceObjectName];
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (void) validate {
  // check for required fields
  if (!__serviceObjectName_isset) {
    @throw [TProtocolException exceptionWithName: @"TProtocolException"
                               reason: @"Required field 'serviceObjectName' is not set."];
  }
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"ServiceObjectNotFoundError("];
  [ms appendString: @"serviceObjectName:"];
  [ms appendFormat: @"\"%@\"", __serviceObjectName];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@implementation ServiceObjectConfigurationError

- (id) init
{
  return [super initWithName: @"ServiceObjectConfigurationError" reason: @"unknown" userInfo: nil];
}

- (id) initWithServiceObjectName: (NSString *) serviceObjectName errorMessages: (NSMutableDictionary *) errorMessages
{
  self = [self init];
  __serviceObjectName = [serviceObjectName retain_stub];
  __serviceObjectName_isset = YES;
  __errorMessages = [errorMessages retain_stub];
  __errorMessages_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super initWithCoder: decoder];
  if ([decoder containsValueForKey: @"serviceObjectName"])
  {
    __serviceObjectName = [[decoder decodeObjectForKey: @"serviceObjectName"] retain_stub];
    __serviceObjectName_isset = YES;
  }
  if ([decoder containsValueForKey: @"errorMessages"])
  {
    __errorMessages = [[decoder decodeObjectForKey: @"errorMessages"] retain_stub];
    __errorMessages_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  [super encodeWithCoder: encoder];
  if (__serviceObjectName_isset)
  {
    [encoder encodeObject: __serviceObjectName forKey: @"serviceObjectName"];
  }
  if (__errorMessages_isset)
  {
    [encoder encodeObject: __errorMessages forKey: @"errorMessages"];
  }
}

- (void) dealloc
{
  [__serviceObjectName release_stub];
  [__errorMessages release_stub];
  [super dealloc_stub];
}

- (NSString *) serviceObjectName {
  return [[__serviceObjectName retain_stub] autorelease_stub];
}

- (void) setServiceObjectName: (NSString *) serviceObjectName {
  [serviceObjectName retain_stub];
  [__serviceObjectName release_stub];
  __serviceObjectName = serviceObjectName;
  __serviceObjectName_isset = YES;
}

- (BOOL) serviceObjectNameIsSet {
  return __serviceObjectName_isset;
}

- (void) unsetServiceObjectName {
  [__serviceObjectName release_stub];
  __serviceObjectName = nil;
  __serviceObjectName_isset = NO;
}

- (NSMutableDictionary *) errorMessages {
  return [[__errorMessages retain_stub] autorelease_stub];
}

- (void) setErrorMessages: (NSMutableDictionary *) errorMessages {
  [errorMessages retain_stub];
  [__errorMessages release_stub];
  __errorMessages = errorMessages;
  __errorMessages_isset = YES;
}

- (BOOL) errorMessagesIsSet {
  return __errorMessages_isset;
}

- (void) unsetErrorMessages {
  [__errorMessages release_stub];
  __errorMessages = nil;
  __errorMessages_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setServiceObjectName: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_MAP) {
          int _size5;
          [inProtocol readMapBeginReturningKeyType: NULL valueType: NULL size: &_size5];
          NSMutableDictionary * fieldValue = [[NSMutableDictionary alloc] initWithCapacity: _size5];
          int _i6;
          for (_i6 = 0; _i6 < _size5; ++_i6)
          {
            NSString * _key7 = [inProtocol readString];
            int _size9;
            [inProtocol readSetBeginReturningElementType: NULL size: &_size9];
            NSMutableSet * _val8 = [[NSMutableSet alloc] initWithCapacity: _size9];
            int _i10;
            for (_i10 = 0; _i10 < _size9; ++_i10)
            {
              NSString * _elem11 = [inProtocol readString];
              [_val8 addObject: _elem11];
            }
            [inProtocol readSetEnd];
            [fieldValue setObject: _val8 forKey: _key7];
            [_val8 release_stub];
          }
          [inProtocol readMapEnd];
          [self setErrorMessages: fieldValue];
          [fieldValue release_stub];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"ServiceObjectConfigurationError"];
  if (__serviceObjectName_isset) {
    if (__serviceObjectName != nil) {
      [outProtocol writeFieldBeginWithName: @"serviceObjectName" type: TType_STRING fieldID: 1];
      [outProtocol writeString: __serviceObjectName];
      [outProtocol writeFieldEnd];
    }
  }
  if (__errorMessages_isset) {
    if (__errorMessages != nil) {
      [outProtocol writeFieldBeginWithName: @"errorMessages" type: TType_MAP fieldID: 2];
      {
        [outProtocol writeMapBeginWithKeyType: TType_STRING valueType: TType_SET size: [__errorMessages count]];
        NSEnumerator * _iter12 = [__errorMessages keyEnumerator];
        id key13;
        while ((key13 = [_iter12 nextObject]))
        {
          [outProtocol writeString: key13];
          {
            [outProtocol writeSetBeginWithElementType: TType_STRING size: [[__errorMessages objectForKey: key13] count]];
            NSEnumerator * _iter14 = [[__errorMessages objectForKey: key13] objectEnumerator];
            id obj15;
            while ((obj15 = [_iter14 nextObject]))
            {
              [outProtocol writeString: obj15];
            }
            [outProtocol writeSetEnd];
          }
        }
        [outProtocol writeMapEnd];
      }
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (void) validate {
  // check for required fields
  if (!__serviceObjectName_isset) {
    @throw [TProtocolException exceptionWithName: @"TProtocolException"
                               reason: @"Required field 'serviceObjectName' is not set."];
  }
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"ServiceObjectConfigurationError("];
  [ms appendString: @"serviceObjectName:"];
  [ms appendFormat: @"\"%@\"", __serviceObjectName];
  [ms appendString: @",errorMessages:"];
  [ms appendFormat: @"%@", __errorMessages];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@implementation ServiceObjectOperationFailedError

- (id) init
{
  return [super initWithName: @"ServiceObjectOperationFailedError" reason: @"unknown" userInfo: nil];
}

- (id) initWithServiceObjectName: (NSString *) serviceObjectName operationName: (NSString *) operationName message: (NSString *) message
{
  self = [self init];
  __serviceObjectName = [serviceObjectName retain_stub];
  __serviceObjectName_isset = YES;
  __operationName = [operationName retain_stub];
  __operationName_isset = YES;
  __message = [message retain_stub];
  __message_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super initWithCoder: decoder];
  if ([decoder containsValueForKey: @"serviceObjectName"])
  {
    __serviceObjectName = [[decoder decodeObjectForKey: @"serviceObjectName"] retain_stub];
    __serviceObjectName_isset = YES;
  }
  if ([decoder containsValueForKey: @"operationName"])
  {
    __operationName = [[decoder decodeObjectForKey: @"operationName"] retain_stub];
    __operationName_isset = YES;
  }
  if ([decoder containsValueForKey: @"message"])
  {
    __message = [[decoder decodeObjectForKey: @"message"] retain_stub];
    __message_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  [super encodeWithCoder: encoder];
  if (__serviceObjectName_isset)
  {
    [encoder encodeObject: __serviceObjectName forKey: @"serviceObjectName"];
  }
  if (__operationName_isset)
  {
    [encoder encodeObject: __operationName forKey: @"operationName"];
  }
  if (__message_isset)
  {
    [encoder encodeObject: __message forKey: @"message"];
  }
}

- (void) dealloc
{
  [__serviceObjectName release_stub];
  [__operationName release_stub];
  [__message release_stub];
  [super dealloc_stub];
}

- (NSString *) serviceObjectName {
  return [[__serviceObjectName retain_stub] autorelease_stub];
}

- (void) setServiceObjectName: (NSString *) serviceObjectName {
  [serviceObjectName retain_stub];
  [__serviceObjectName release_stub];
  __serviceObjectName = serviceObjectName;
  __serviceObjectName_isset = YES;
}

- (BOOL) serviceObjectNameIsSet {
  return __serviceObjectName_isset;
}

- (void) unsetServiceObjectName {
  [__serviceObjectName release_stub];
  __serviceObjectName = nil;
  __serviceObjectName_isset = NO;
}

- (NSString *) operationName {
  return [[__operationName retain_stub] autorelease_stub];
}

- (void) setOperationName: (NSString *) operationName {
  [operationName retain_stub];
  [__operationName release_stub];
  __operationName = operationName;
  __operationName_isset = YES;
}

- (BOOL) operationNameIsSet {
  return __operationName_isset;
}

- (void) unsetOperationName {
  [__operationName release_stub];
  __operationName = nil;
  __operationName_isset = NO;
}

- (NSString *) message {
  return [[__message retain_stub] autorelease_stub];
}

- (void) setMessage: (NSString *) message {
  [message retain_stub];
  [__message release_stub];
  __message = message;
  __message_isset = YES;
}

- (BOOL) messageIsSet {
  return __message_isset;
}

- (void) unsetMessage {
  [__message release_stub];
  __message = nil;
  __message_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setServiceObjectName: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setOperationName: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 3:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setMessage: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"ServiceObjectOperationFailedError"];
  if (__serviceObjectName_isset) {
    if (__serviceObjectName != nil) {
      [outProtocol writeFieldBeginWithName: @"serviceObjectName" type: TType_STRING fieldID: 1];
      [outProtocol writeString: __serviceObjectName];
      [outProtocol writeFieldEnd];
    }
  }
  if (__operationName_isset) {
    if (__operationName != nil) {
      [outProtocol writeFieldBeginWithName: @"operationName" type: TType_STRING fieldID: 2];
      [outProtocol writeString: __operationName];
      [outProtocol writeFieldEnd];
    }
  }
  if (__message_isset) {
    if (__message != nil) {
      [outProtocol writeFieldBeginWithName: @"message" type: TType_STRING fieldID: 3];
      [outProtocol writeString: __message];
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (void) validate {
  // check for required fields
  if (!__serviceObjectName_isset) {
    @throw [TProtocolException exceptionWithName: @"TProtocolException"
                               reason: @"Required field 'serviceObjectName' is not set."];
  }
  if (!__operationName_isset) {
    @throw [TProtocolException exceptionWithName: @"TProtocolException"
                               reason: @"Required field 'operationName' is not set."];
  }
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"ServiceObjectOperationFailedError("];
  [ms appendString: @"serviceObjectName:"];
  [ms appendFormat: @"\"%@\"", __serviceObjectName];
  [ms appendString: @",operationName:"];
  [ms appendFormat: @"\"%@\"", __operationName];
  [ms appendString: @",message:"];
  [ms appendFormat: @"\"%@\"", __message];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end


@implementation serviceobjConstants
+ (void) initialize {
}
@end

@interface listServiceObjects_args : NSObject <TBase, NSCoding> {
  AuthenticationToken *__token;

  BOOL __token_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=token, setter=setToken:) AuthenticationToken *token;
#endif

- (id) init;
- (id) initWithToken: (AuthenticationToken *) token;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (AuthenticationToken) token;
- (void) setToken: (AuthenticationToken) token;
#endif
- (BOOL) tokenIsSet;

@end

@implementation listServiceObjects_args

- (id) init
{
  self = [super init];
#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
#endif
  return self;
}

- (id) initWithToken: (AuthenticationToken *) token
{
  self = [super init];
  __token = [token retain_stub];
  __token_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"token"])
  {
    __token = [[decoder decodeObjectForKey: @"token"] retain_stub];
    __token_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__token_isset)
  {
    [encoder encodeObject: __token forKey: @"token"];
  }
}

- (void) dealloc
{
  [__token release_stub];
  [super dealloc_stub];
}

- (AuthenticationToken *) token {
  return [[__token retain_stub] autorelease_stub];
}

- (void) setToken: (AuthenticationToken *) token {
  [token retain_stub];
  [__token release_stub];
  __token = token;
  __token_isset = YES;
}

- (BOOL) tokenIsSet {
  return __token_isset;
}

- (void) unsetToken {
  [__token release_stub];
  __token = nil;
  __token_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_STRUCT) {
          AuthenticationToken *fieldValue = [[AuthenticationToken alloc] init];
          [fieldValue read: inProtocol];
          [self setToken: fieldValue];
          [fieldValue release_stub];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"listServiceObjects_args"];
  if (__token_isset) {
    if (__token != nil) {
      [outProtocol writeFieldBeginWithName: @"token" type: TType_STRUCT fieldID: 1];
      [__token write: outProtocol];
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (void) validate {
  // check for required fields
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"listServiceObjects_args("];
  [ms appendString: @"token:"];
  [ms appendFormat: @"%@", __token];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@interface ListServiceObjects_result : NSObject <TBase, NSCoding> {
  NSMutableSet * __success;

  BOOL __success_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=success, setter=setSuccess:) NSMutableSet * success;
#endif

- (id) init;
- (id) initWithSuccess: (NSMutableSet *) success;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSMutableSet *) success;
- (void) setSuccess: (NSMutableSet *) success;
#endif
- (BOOL) successIsSet;

@end

@implementation ListServiceObjects_result

- (id) init
{
  self = [super init];
#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
#endif
  return self;
}

- (id) initWithSuccess: (NSMutableSet *) success
{
  self = [super init];
  __success = [success retain_stub];
  __success_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"success"])
  {
    __success = [[decoder decodeObjectForKey: @"success"] retain_stub];
    __success_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__success_isset)
  {
    [encoder encodeObject: __success forKey: @"success"];
  }
}

- (void) dealloc
{
  [__success release_stub];
  [super dealloc_stub];
}

- (NSMutableSet *) success {
  return [[__success retain_stub] autorelease_stub];
}

- (void) setSuccess: (NSMutableSet *) success {
  [success retain_stub];
  [__success release_stub];
  __success = success;
  __success_isset = YES;
}

- (BOOL) successIsSet {
  return __success_isset;
}

- (void) unsetSuccess {
  [__success release_stub];
  __success = nil;
  __success_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 0:
        if (fieldType == TType_SET) {
          int _size16;
          [inProtocol readSetBeginReturningElementType: NULL size: &_size16];
          NSMutableSet * fieldValue = [[NSMutableSet alloc] initWithCapacity: _size16];
          int _i17;
          for (_i17 = 0; _i17 < _size16; ++_i17)
          {
            ServiceObject *_elem18 = [[ServiceObject alloc] init];
            [_elem18 read: inProtocol];
            [fieldValue addObject: _elem18];
            [_elem18 release_stub];
          }
          [inProtocol readSetEnd];
          [self setSuccess: fieldValue];
          [fieldValue release_stub];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"ListServiceObjects_result"];

  if (__success_isset) {
    if (__success != nil) {
      [outProtocol writeFieldBeginWithName: @"success" type: TType_SET fieldID: 0];
      {
        [outProtocol writeSetBeginWithElementType: TType_STRUCT size: [__success count]];
        NSEnumerator * _iter19 = [__success objectEnumerator];
        id obj20;
        while ((obj20 = [_iter19 nextObject]))
        {
          [obj20 write: outProtocol];
        }
        [outProtocol writeSetEnd];
      }
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (void) validate {
  // check for required fields
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"ListServiceObjects_result("];
  [ms appendString: @"success:"];
  [ms appendFormat: @"%@", __success];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@interface getServiceObject_args : NSObject <TBase, NSCoding> {
  AuthenticationToken *__token;
  NSString * __name;
  NSMutableDictionary * __conf;

  BOOL __token_isset;
  BOOL __name_isset;
  BOOL __conf_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=token, setter=setToken:) AuthenticationToken *token;
@property (nonatomic, retain, getter=name, setter=setName:) NSString * name;
@property (nonatomic, retain, getter=conf, setter=setConf:) NSMutableDictionary * conf;
#endif

- (id) init;
- (id) initWithToken: (AuthenticationToken *) token name: (NSString *) name conf: (NSMutableDictionary *) conf;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (AuthenticationToken) token;
- (void) setToken: (AuthenticationToken) token;
#endif
- (BOOL) tokenIsSet;

#if !__has_feature(objc_arc)
- (NSString *) name;
- (void) setName: (NSString *) name;
#endif
- (BOOL) nameIsSet;

#if !__has_feature(objc_arc)
- (NSMutableDictionary *) conf;
- (void) setConf: (NSMutableDictionary *) conf;
#endif
- (BOOL) confIsSet;

@end

@implementation getServiceObject_args

- (id) init
{
  self = [super init];
#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
#endif
  return self;
}

- (id) initWithToken: (AuthenticationToken *) token name: (NSString *) name conf: (NSMutableDictionary *) conf
{
  self = [super init];
  __token = [token retain_stub];
  __token_isset = YES;
  __name = [name retain_stub];
  __name_isset = YES;
  __conf = [conf retain_stub];
  __conf_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"token"])
  {
    __token = [[decoder decodeObjectForKey: @"token"] retain_stub];
    __token_isset = YES;
  }
  if ([decoder containsValueForKey: @"name"])
  {
    __name = [[decoder decodeObjectForKey: @"name"] retain_stub];
    __name_isset = YES;
  }
  if ([decoder containsValueForKey: @"conf"])
  {
    __conf = [[decoder decodeObjectForKey: @"conf"] retain_stub];
    __conf_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__token_isset)
  {
    [encoder encodeObject: __token forKey: @"token"];
  }
  if (__name_isset)
  {
    [encoder encodeObject: __name forKey: @"name"];
  }
  if (__conf_isset)
  {
    [encoder encodeObject: __conf forKey: @"conf"];
  }
}

- (void) dealloc
{
  [__token release_stub];
  [__name release_stub];
  [__conf release_stub];
  [super dealloc_stub];
}

- (AuthenticationToken *) token {
  return [[__token retain_stub] autorelease_stub];
}

- (void) setToken: (AuthenticationToken *) token {
  [token retain_stub];
  [__token release_stub];
  __token = token;
  __token_isset = YES;
}

- (BOOL) tokenIsSet {
  return __token_isset;
}

- (void) unsetToken {
  [__token release_stub];
  __token = nil;
  __token_isset = NO;
}

- (NSString *) name {
  return [[__name retain_stub] autorelease_stub];
}

- (void) setName: (NSString *) name {
  [name retain_stub];
  [__name release_stub];
  __name = name;
  __name_isset = YES;
}

- (BOOL) nameIsSet {
  return __name_isset;
}

- (void) unsetName {
  [__name release_stub];
  __name = nil;
  __name_isset = NO;
}

- (NSMutableDictionary *) conf {
  return [[__conf retain_stub] autorelease_stub];
}

- (void) setConf: (NSMutableDictionary *) conf {
  [conf retain_stub];
  [__conf release_stub];
  __conf = conf;
  __conf_isset = YES;
}

- (BOOL) confIsSet {
  return __conf_isset;
}

- (void) unsetConf {
  [__conf release_stub];
  __conf = nil;
  __conf_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_STRUCT) {
          AuthenticationToken *fieldValue = [[AuthenticationToken alloc] init];
          [fieldValue read: inProtocol];
          [self setToken: fieldValue];
          [fieldValue release_stub];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setName: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 3:
        if (fieldType == TType_MAP) {
          int _size21;
          [inProtocol readMapBeginReturningKeyType: NULL valueType: NULL size: &_size21];
          NSMutableDictionary * fieldValue = [[NSMutableDictionary alloc] initWithCapacity: _size21];
          int _i22;
          for (_i22 = 0; _i22 < _size21; ++_i22)
          {
            NSString * _key23 = [inProtocol readString];
            NSString * _val24 = [inProtocol readString];
            [fieldValue setObject: _val24 forKey: _key23];
          }
          [inProtocol readMapEnd];
          [self setConf: fieldValue];
          [fieldValue release_stub];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"getServiceObject_args"];
  if (__token_isset) {
    if (__token != nil) {
      [outProtocol writeFieldBeginWithName: @"token" type: TType_STRUCT fieldID: 1];
      [__token write: outProtocol];
      [outProtocol writeFieldEnd];
    }
  }
  if (__name_isset) {
    if (__name != nil) {
      [outProtocol writeFieldBeginWithName: @"name" type: TType_STRING fieldID: 2];
      [outProtocol writeString: __name];
      [outProtocol writeFieldEnd];
    }
  }
  if (__conf_isset) {
    if (__conf != nil) {
      [outProtocol writeFieldBeginWithName: @"conf" type: TType_MAP fieldID: 3];
      {
        [outProtocol writeMapBeginWithKeyType: TType_STRING valueType: TType_STRING size: [__conf count]];
        NSEnumerator * _iter25 = [__conf keyEnumerator];
        id key26;
        while ((key26 = [_iter25 nextObject]))
        {
          [outProtocol writeString: key26];
          [outProtocol writeString: [__conf objectForKey: key26]];
        }
        [outProtocol writeMapEnd];
      }
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (void) validate {
  // check for required fields
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"getServiceObject_args("];
  [ms appendString: @"token:"];
  [ms appendFormat: @"%@", __token];
  [ms appendString: @",name:"];
  [ms appendFormat: @"\"%@\"", __name];
  [ms appendString: @",conf:"];
  [ms appendFormat: @"%@", __conf];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@interface GetServiceObject_result : NSObject <TBase, NSCoding> {
  ServiceObject * __success;
  ServiceObjectNotFoundError * __sonfe;
  ServiceObjectConfigurationError * __soce;

  BOOL __success_isset;
  BOOL __sonfe_isset;
  BOOL __soce_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=success, setter=setSuccess:) ServiceObject * success;
@property (nonatomic, retain, getter=sonfe, setter=setSonfe:) ServiceObjectNotFoundError * sonfe;
@property (nonatomic, retain, getter=soce, setter=setSoce:) ServiceObjectConfigurationError * soce;
#endif

- (id) init;
- (id) initWithSuccess: (ServiceObject *) success sonfe: (ServiceObjectNotFoundError *) sonfe soce: (ServiceObjectConfigurationError *) soce;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (ServiceObject *) success;
- (void) setSuccess: (ServiceObject *) success;
#endif
- (BOOL) successIsSet;

#if !__has_feature(objc_arc)
- (ServiceObjectNotFoundError *) sonfe;
- (void) setSonfe: (ServiceObjectNotFoundError *) sonfe;
#endif
- (BOOL) sonfeIsSet;

#if !__has_feature(objc_arc)
- (ServiceObjectConfigurationError *) soce;
- (void) setSoce: (ServiceObjectConfigurationError *) soce;
#endif
- (BOOL) soceIsSet;

@end

@implementation GetServiceObject_result

- (id) init
{
  self = [super init];
#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
#endif
  return self;
}

- (id) initWithSuccess: (ServiceObject *) success sonfe: (ServiceObjectNotFoundError *) sonfe soce: (ServiceObjectConfigurationError *) soce
{
  self = [super init];
  __success = [success retain_stub];
  __success_isset = YES;
  __sonfe = [sonfe retain_stub];
  __sonfe_isset = YES;
  __soce = [soce retain_stub];
  __soce_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"success"])
  {
    __success = [[decoder decodeObjectForKey: @"success"] retain_stub];
    __success_isset = YES;
  }
  if ([decoder containsValueForKey: @"sonfe"])
  {
    __sonfe = [[decoder decodeObjectForKey: @"sonfe"] retain_stub];
    __sonfe_isset = YES;
  }
  if ([decoder containsValueForKey: @"soce"])
  {
    __soce = [[decoder decodeObjectForKey: @"soce"] retain_stub];
    __soce_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__success_isset)
  {
    [encoder encodeObject: __success forKey: @"success"];
  }
  if (__sonfe_isset)
  {
    [encoder encodeObject: __sonfe forKey: @"sonfe"];
  }
  if (__soce_isset)
  {
    [encoder encodeObject: __soce forKey: @"soce"];
  }
}

- (void) dealloc
{
  [__success release_stub];
  [__sonfe release_stub];
  [__soce release_stub];
  [super dealloc_stub];
}

- (ServiceObject *) success {
  return [[__success retain_stub] autorelease_stub];
}

- (void) setSuccess: (ServiceObject *) success {
  [success retain_stub];
  [__success release_stub];
  __success = success;
  __success_isset = YES;
}

- (BOOL) successIsSet {
  return __success_isset;
}

- (void) unsetSuccess {
  [__success release_stub];
  __success = nil;
  __success_isset = NO;
}

- (ServiceObjectNotFoundError *) sonfe {
  return [[__sonfe retain_stub] autorelease_stub];
}

- (void) setSonfe: (ServiceObjectNotFoundError *) sonfe {
  [sonfe retain_stub];
  [__sonfe release_stub];
  __sonfe = sonfe;
  __sonfe_isset = YES;
}

- (BOOL) sonfeIsSet {
  return __sonfe_isset;
}

- (void) unsetSonfe {
  [__sonfe release_stub];
  __sonfe = nil;
  __sonfe_isset = NO;
}

- (ServiceObjectConfigurationError *) soce {
  return [[__soce retain_stub] autorelease_stub];
}

- (void) setSoce: (ServiceObjectConfigurationError *) soce {
  [soce retain_stub];
  [__soce release_stub];
  __soce = soce;
  __soce_isset = YES;
}

- (BOOL) soceIsSet {
  return __soce_isset;
}

- (void) unsetSoce {
  [__soce release_stub];
  __soce = nil;
  __soce_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 0:
        if (fieldType == TType_STRUCT) {
          ServiceObject *fieldValue = [[ServiceObject alloc] init];
          [fieldValue read: inProtocol];
          [self setSuccess: fieldValue];
          [fieldValue release_stub];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 1:
        if (fieldType == TType_STRUCT) {
          ServiceObjectNotFoundError *fieldValue = [[ServiceObjectNotFoundError alloc] init];
          [fieldValue read: inProtocol];
          [self setSonfe: fieldValue];
          [fieldValue release_stub];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_STRUCT) {
          ServiceObjectConfigurationError *fieldValue = [[ServiceObjectConfigurationError alloc] init];
          [fieldValue read: inProtocol];
          [self setSoce: fieldValue];
          [fieldValue release_stub];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"GetServiceObject_result"];

  if (__success_isset) {
    if (__success != nil) {
      [outProtocol writeFieldBeginWithName: @"success" type: TType_STRUCT fieldID: 0];
      [__success write: outProtocol];
      [outProtocol writeFieldEnd];
    }
  } else if (__sonfe_isset) {
    if (__sonfe != nil) {
      [outProtocol writeFieldBeginWithName: @"sonfe" type: TType_STRUCT fieldID: 1];
      [__sonfe write: outProtocol];
      [outProtocol writeFieldEnd];
    }
  } else if (__soce_isset) {
    if (__soce != nil) {
      [outProtocol writeFieldBeginWithName: @"soce" type: TType_STRUCT fieldID: 2];
      [__soce write: outProtocol];
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (void) validate {
  // check for required fields
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"GetServiceObject_result("];
  [ms appendString: @"success:"];
  [ms appendFormat: @"%@", __success];
  [ms appendString: @",sonfe:"];
  [ms appendFormat: @"%@", __sonfe];
  [ms appendString: @",soce:"];
  [ms appendFormat: @"%@", __soce];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@interface performOperation_args : NSObject <TBase, NSCoding> {
  AuthenticationToken *__token;
  ServiceObject * __object;
  NSString * __operationName;
  ServiceObjectOperationPayload * __payload;

  BOOL __token_isset;
  BOOL __object_isset;
  BOOL __operationName_isset;
  BOOL __payload_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=token, setter=setToken:) AuthenticationToken *token;
@property (nonatomic, retain, getter=object, setter=setObject:) ServiceObject * object;
@property (nonatomic, retain, getter=operationName, setter=setOperationName:) NSString * operationName;
@property (nonatomic, retain, getter=payload, setter=setPayload:) ServiceObjectOperationPayload * payload;
#endif

- (id) init;
- (id) initWithToken: (AuthenticationToken *) token object: (ServiceObject *) object operationName: (NSString *) operationName payload: (ServiceObjectOperationPayload *) payload;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (AuthenticationToken) token;
- (void) setToken: (AuthenticationToken) token;
#endif
- (BOOL) tokenIsSet;

#if !__has_feature(objc_arc)
- (ServiceObject *) object;
- (void) setObject: (ServiceObject *) object;
#endif
- (BOOL) objectIsSet;

#if !__has_feature(objc_arc)
- (NSString *) operationName;
- (void) setOperationName: (NSString *) operationName;
#endif
- (BOOL) operationNameIsSet;

#if !__has_feature(objc_arc)
- (ServiceObjectOperationPayload *) payload;
- (void) setPayload: (ServiceObjectOperationPayload *) payload;
#endif
- (BOOL) payloadIsSet;

@end

@implementation performOperation_args

- (id) init
{
  self = [super init];
#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
#endif
  return self;
}

- (id) initWithToken: (AuthenticationToken *) token object: (ServiceObject *) object operationName: (NSString *) operationName payload: (ServiceObjectOperationPayload *) payload
{
  self = [super init];
  __token = [token retain_stub];
  __token_isset = YES;
  __object = [object retain_stub];
  __object_isset = YES;
  __operationName = [operationName retain_stub];
  __operationName_isset = YES;
  __payload = [payload retain_stub];
  __payload_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"token"])
  {
    __token = [[decoder decodeObjectForKey: @"token"] retain_stub];
    __token_isset = YES;
  }
  if ([decoder containsValueForKey: @"object"])
  {
    __object = [[decoder decodeObjectForKey: @"object"] retain_stub];
    __object_isset = YES;
  }
  if ([decoder containsValueForKey: @"operationName"])
  {
    __operationName = [[decoder decodeObjectForKey: @"operationName"] retain_stub];
    __operationName_isset = YES;
  }
  if ([decoder containsValueForKey: @"payload"])
  {
    __payload = [[decoder decodeObjectForKey: @"payload"] retain_stub];
    __payload_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__token_isset)
  {
    [encoder encodeObject: __token forKey: @"token"];
  }
  if (__object_isset)
  {
    [encoder encodeObject: __object forKey: @"object"];
  }
  if (__operationName_isset)
  {
    [encoder encodeObject: __operationName forKey: @"operationName"];
  }
  if (__payload_isset)
  {
    [encoder encodeObject: __payload forKey: @"payload"];
  }
}

- (void) dealloc
{
  [__token release_stub];
  [__object release_stub];
  [__operationName release_stub];
  [__payload release_stub];
  [super dealloc_stub];
}

- (AuthenticationToken *) token {
  return [[__token retain_stub] autorelease_stub];
}

- (void) setToken: (AuthenticationToken *) token {
  [token retain_stub];
  [__token release_stub];
  __token = token;
  __token_isset = YES;
}

- (BOOL) tokenIsSet {
  return __token_isset;
}

- (void) unsetToken {
  [__token release_stub];
  __token = nil;
  __token_isset = NO;
}

- (ServiceObject *) object {
  return [[__object retain_stub] autorelease_stub];
}

- (void) setObject: (ServiceObject *) object {
  [object retain_stub];
  [__object release_stub];
  __object = object;
  __object_isset = YES;
}

- (BOOL) objectIsSet {
  return __object_isset;
}

- (void) unsetObject {
  [__object release_stub];
  __object = nil;
  __object_isset = NO;
}

- (NSString *) operationName {
  return [[__operationName retain_stub] autorelease_stub];
}

- (void) setOperationName: (NSString *) operationName {
  [operationName retain_stub];
  [__operationName release_stub];
  __operationName = operationName;
  __operationName_isset = YES;
}

- (BOOL) operationNameIsSet {
  return __operationName_isset;
}

- (void) unsetOperationName {
  [__operationName release_stub];
  __operationName = nil;
  __operationName_isset = NO;
}

- (ServiceObjectOperationPayload *) payload {
  return [[__payload retain_stub] autorelease_stub];
}

- (void) setPayload: (ServiceObjectOperationPayload *) payload {
  [payload retain_stub];
  [__payload release_stub];
  __payload = payload;
  __payload_isset = YES;
}

- (BOOL) payloadIsSet {
  return __payload_isset;
}

- (void) unsetPayload {
  [__payload release_stub];
  __payload = nil;
  __payload_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_STRUCT) {
          AuthenticationToken *fieldValue = [[AuthenticationToken alloc] init];
          [fieldValue read: inProtocol];
          [self setToken: fieldValue];
          [fieldValue release_stub];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_STRUCT) {
          ServiceObject *fieldValue = [[ServiceObject alloc] init];
          [fieldValue read: inProtocol];
          [self setObject: fieldValue];
          [fieldValue release_stub];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 3:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setOperationName: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 4:
        if (fieldType == TType_STRUCT) {
          ServiceObjectOperationPayload *fieldValue = [[ServiceObjectOperationPayload alloc] init];
          [fieldValue read: inProtocol];
          [self setPayload: fieldValue];
          [fieldValue release_stub];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"performOperation_args"];
  if (__token_isset) {
    if (__token != nil) {
      [outProtocol writeFieldBeginWithName: @"token" type: TType_STRUCT fieldID: 1];
      [__token write: outProtocol];
      [outProtocol writeFieldEnd];
    }
  }
  if (__object_isset) {
    if (__object != nil) {
      [outProtocol writeFieldBeginWithName: @"object" type: TType_STRUCT fieldID: 2];
      [__object write: outProtocol];
      [outProtocol writeFieldEnd];
    }
  }
  if (__operationName_isset) {
    if (__operationName != nil) {
      [outProtocol writeFieldBeginWithName: @"operationName" type: TType_STRING fieldID: 3];
      [outProtocol writeString: __operationName];
      [outProtocol writeFieldEnd];
    }
  }
  if (__payload_isset) {
    if (__payload != nil) {
      [outProtocol writeFieldBeginWithName: @"payload" type: TType_STRUCT fieldID: 4];
      [__payload write: outProtocol];
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (void) validate {
  // check for required fields
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"performOperation_args("];
  [ms appendString: @"token:"];
  [ms appendFormat: @"%@", __token];
  [ms appendString: @",object:"];
  [ms appendFormat: @"%@", __object];
  [ms appendString: @",operationName:"];
  [ms appendFormat: @"\"%@\"", __operationName];
  [ms appendString: @",payload:"];
  [ms appendFormat: @"%@", __payload];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@interface PerformOperation_result : NSObject <TBase, NSCoding> {
  ServiceObjectOperationPayload * __success;
  ServiceObjectOperationFailedError * __soofe;

  BOOL __success_isset;
  BOOL __soofe_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=success, setter=setSuccess:) ServiceObjectOperationPayload * success;
@property (nonatomic, retain, getter=soofe, setter=setSoofe:) ServiceObjectOperationFailedError * soofe;
#endif

- (id) init;
- (id) initWithSuccess: (ServiceObjectOperationPayload *) success soofe: (ServiceObjectOperationFailedError *) soofe;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (ServiceObjectOperationPayload *) success;
- (void) setSuccess: (ServiceObjectOperationPayload *) success;
#endif
- (BOOL) successIsSet;

#if !__has_feature(objc_arc)
- (ServiceObjectOperationFailedError *) soofe;
- (void) setSoofe: (ServiceObjectOperationFailedError *) soofe;
#endif
- (BOOL) soofeIsSet;

@end

@implementation PerformOperation_result

- (id) init
{
  self = [super init];
#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
#endif
  return self;
}

- (id) initWithSuccess: (ServiceObjectOperationPayload *) success soofe: (ServiceObjectOperationFailedError *) soofe
{
  self = [super init];
  __success = [success retain_stub];
  __success_isset = YES;
  __soofe = [soofe retain_stub];
  __soofe_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"success"])
  {
    __success = [[decoder decodeObjectForKey: @"success"] retain_stub];
    __success_isset = YES;
  }
  if ([decoder containsValueForKey: @"soofe"])
  {
    __soofe = [[decoder decodeObjectForKey: @"soofe"] retain_stub];
    __soofe_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__success_isset)
  {
    [encoder encodeObject: __success forKey: @"success"];
  }
  if (__soofe_isset)
  {
    [encoder encodeObject: __soofe forKey: @"soofe"];
  }
}

- (void) dealloc
{
  [__success release_stub];
  [__soofe release_stub];
  [super dealloc_stub];
}

- (ServiceObjectOperationPayload *) success {
  return [[__success retain_stub] autorelease_stub];
}

- (void) setSuccess: (ServiceObjectOperationPayload *) success {
  [success retain_stub];
  [__success release_stub];
  __success = success;
  __success_isset = YES;
}

- (BOOL) successIsSet {
  return __success_isset;
}

- (void) unsetSuccess {
  [__success release_stub];
  __success = nil;
  __success_isset = NO;
}

- (ServiceObjectOperationFailedError *) soofe {
  return [[__soofe retain_stub] autorelease_stub];
}

- (void) setSoofe: (ServiceObjectOperationFailedError *) soofe {
  [soofe retain_stub];
  [__soofe release_stub];
  __soofe = soofe;
  __soofe_isset = YES;
}

- (BOOL) soofeIsSet {
  return __soofe_isset;
}

- (void) unsetSoofe {
  [__soofe release_stub];
  __soofe = nil;
  __soofe_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 0:
        if (fieldType == TType_STRUCT) {
          ServiceObjectOperationPayload *fieldValue = [[ServiceObjectOperationPayload alloc] init];
          [fieldValue read: inProtocol];
          [self setSuccess: fieldValue];
          [fieldValue release_stub];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 1:
        if (fieldType == TType_STRUCT) {
          ServiceObjectOperationFailedError *fieldValue = [[ServiceObjectOperationFailedError alloc] init];
          [fieldValue read: inProtocol];
          [self setSoofe: fieldValue];
          [fieldValue release_stub];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"PerformOperation_result"];

  if (__success_isset) {
    if (__success != nil) {
      [outProtocol writeFieldBeginWithName: @"success" type: TType_STRUCT fieldID: 0];
      [__success write: outProtocol];
      [outProtocol writeFieldEnd];
    }
  } else if (__soofe_isset) {
    if (__soofe != nil) {
      [outProtocol writeFieldBeginWithName: @"soofe" type: TType_STRUCT fieldID: 1];
      [__soofe write: outProtocol];
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (void) validate {
  // check for required fields
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"PerformOperation_result("];
  [ms appendString: @"success:"];
  [ms appendFormat: @"%@", __success];
  [ms appendString: @",soofe:"];
  [ms appendFormat: @"%@", __soofe];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@implementation ServiceObjectProxyServiceClient
- (id) initWithProtocol: (id <TProtocol>) protocol
{
  return [self initWithInProtocol: protocol outProtocol: protocol];
}

- (id) initWithInProtocol: (id <TProtocol>) anInProtocol outProtocol: (id <TProtocol>) anOutProtocol
{
  self = [super init];
  inProtocol = [anInProtocol retain_stub];
  outProtocol = [anOutProtocol retain_stub];
  return self;
}

- (void) dealloc
{
  [inProtocol release_stub];
  [outProtocol release_stub];
  [super dealloc_stub];
}

- (void) send_listServiceObjects: (AuthenticationToken *) token
{
  [outProtocol writeMessageBeginWithName: @"listServiceObjects" type: TMessageType_CALL sequenceID: 0];
  [outProtocol writeStructBeginWithName: @"listServiceObjects_args"];
  if (token != nil)  {
    [outProtocol writeFieldBeginWithName: @"token" type: TType_STRUCT fieldID: 1];
    [token write: outProtocol];
    [outProtocol writeFieldEnd];
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
  [outProtocol writeMessageEnd];
  [[outProtocol transport] flush];
}

- (NSMutableSet *) recv_listServiceObjects
{
  int msgType = 0;
  [inProtocol readMessageBeginReturningName: nil type: &msgType sequenceID: NULL];
  if (msgType == TMessageType_EXCEPTION) {
    TApplicationException * x = [TApplicationException read: inProtocol];
    [inProtocol readMessageEnd];
    @throw x;
  }
  ListServiceObjects_result * result = [[[ListServiceObjects_result alloc] init] autorelease_stub];
  [result read: inProtocol];
  [inProtocol readMessageEnd];
  if ([result successIsSet]) {
    return [result success];
  }
  @throw [TApplicationException exceptionWithType: TApplicationException_MISSING_RESULT
                                           reason: @"listServiceObjects failed: unknown result"];
}

- (NSMutableSet *) listServiceObjects: (AuthenticationToken *) token
{
  [self send_listServiceObjects : token];
  return [self recv_listServiceObjects];
}

- (void) send_getServiceObject: (AuthenticationToken *) token name: (NSString *) name conf: (NSMutableDictionary *) conf
{
  [outProtocol writeMessageBeginWithName: @"getServiceObject" type: TMessageType_CALL sequenceID: 0];
  [outProtocol writeStructBeginWithName: @"getServiceObject_args"];
  if (token != nil)  {
    [outProtocol writeFieldBeginWithName: @"token" type: TType_STRUCT fieldID: 1];
    [token write: outProtocol];
    [outProtocol writeFieldEnd];
  }
  if (name != nil)  {
    [outProtocol writeFieldBeginWithName: @"name" type: TType_STRING fieldID: 2];
    [outProtocol writeString: name];
    [outProtocol writeFieldEnd];
  }
  if (conf != nil)  {
    [outProtocol writeFieldBeginWithName: @"conf" type: TType_MAP fieldID: 3];
    {
      [outProtocol writeMapBeginWithKeyType: TType_STRING valueType: TType_STRING size: [conf count]];
      NSEnumerator * _iter27 = [conf keyEnumerator];
      id key28;
      while ((key28 = [_iter27 nextObject]))
      {
        [outProtocol writeString: key28];
        [outProtocol writeString: [conf objectForKey: key28]];
      }
      [outProtocol writeMapEnd];
    }
    [outProtocol writeFieldEnd];
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
  [outProtocol writeMessageEnd];
  [[outProtocol transport] flush];
}

- (ServiceObject *) recv_getServiceObject
{
  int msgType = 0;
  [inProtocol readMessageBeginReturningName: nil type: &msgType sequenceID: NULL];
  if (msgType == TMessageType_EXCEPTION) {
    TApplicationException * x = [TApplicationException read: inProtocol];
    [inProtocol readMessageEnd];
    @throw x;
  }
  GetServiceObject_result * result = [[[GetServiceObject_result alloc] init] autorelease_stub];
  [result read: inProtocol];
  [inProtocol readMessageEnd];
  if ([result successIsSet]) {
    return [result success];
  }
  if ([result sonfeIsSet]) {
    @throw [result sonfe];
  }
  if ([result soceIsSet]) {
    @throw [result soce];
  }
  @throw [TApplicationException exceptionWithType: TApplicationException_MISSING_RESULT
                                           reason: @"getServiceObject failed: unknown result"];
}

- (ServiceObject *) getServiceObject: (AuthenticationToken *) token name: (NSString *) name conf: (NSMutableDictionary *) conf
{
  [self send_getServiceObject : token name: name conf: conf];
  return [self recv_getServiceObject];
}

- (void) send_performOperation: (AuthenticationToken *) token object: (ServiceObject *) object operationName: (NSString *) operationName payload: (ServiceObjectOperationPayload *) payload
{
  [outProtocol writeMessageBeginWithName: @"performOperation" type: TMessageType_CALL sequenceID: 0];
  [outProtocol writeStructBeginWithName: @"performOperation_args"];
  if (token != nil)  {
    [outProtocol writeFieldBeginWithName: @"token" type: TType_STRUCT fieldID: 1];
    [token write: outProtocol];
    [outProtocol writeFieldEnd];
  }
  if (object != nil)  {
    [outProtocol writeFieldBeginWithName: @"object" type: TType_STRUCT fieldID: 2];
    [object write: outProtocol];
    [outProtocol writeFieldEnd];
  }
  if (operationName != nil)  {
    [outProtocol writeFieldBeginWithName: @"operationName" type: TType_STRING fieldID: 3];
    [outProtocol writeString: operationName];
    [outProtocol writeFieldEnd];
  }
  if (payload != nil)  {
    [outProtocol writeFieldBeginWithName: @"payload" type: TType_STRUCT fieldID: 4];
    [payload write: outProtocol];
    [outProtocol writeFieldEnd];
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
  [outProtocol writeMessageEnd];
  [[outProtocol transport] flush];
}

- (ServiceObjectOperationPayload *) recv_performOperation
{
  int msgType = 0;
  [inProtocol readMessageBeginReturningName: nil type: &msgType sequenceID: NULL];
  if (msgType == TMessageType_EXCEPTION) {
    TApplicationException * x = [TApplicationException read: inProtocol];
    [inProtocol readMessageEnd];
    @throw x;
  }
  PerformOperation_result * result = [[[PerformOperation_result alloc] init] autorelease_stub];
  [result read: inProtocol];
  [inProtocol readMessageEnd];
  if ([result successIsSet]) {
    return [result success];
  }
  if ([result soofeIsSet]) {
    @throw [result soofe];
  }
  @throw [TApplicationException exceptionWithType: TApplicationException_MISSING_RESULT
                                           reason: @"performOperation failed: unknown result"];
}

- (ServiceObjectOperationPayload *) performOperation: (AuthenticationToken *) token object: (ServiceObject *) object operationName: (NSString *) operationName payload: (ServiceObjectOperationPayload *) payload
{
  [self send_performOperation : token object: object operationName: operationName payload: payload];
  return [self recv_performOperation];
}

@end

@implementation ServiceObjectProxyServiceProcessor

- (id) initWithServiceObjectProxyService: (id <ServiceObjectProxyService>) service
{
  self = [super init];
  if (!self) {
    return nil;
  }
  mService = [service retain_stub];
  mMethodMap = [[NSMutableDictionary dictionary] retain_stub];
  {
    SEL s = @selector(process_listServiceObjects_withSequenceID:inProtocol:outProtocol:);
    NSMethodSignature * sig = [self methodSignatureForSelector: s];
    NSInvocation * invocation = [NSInvocation invocationWithMethodSignature: sig];
    [invocation setSelector: s];
    [invocation retainArguments];
    [mMethodMap setValue: invocation forKey: @"listServiceObjects"];
  }
  {
    SEL s = @selector(process_getServiceObject_withSequenceID:inProtocol:outProtocol:);
    NSMethodSignature * sig = [self methodSignatureForSelector: s];
    NSInvocation * invocation = [NSInvocation invocationWithMethodSignature: sig];
    [invocation setSelector: s];
    [invocation retainArguments];
    [mMethodMap setValue: invocation forKey: @"getServiceObject"];
  }
  {
    SEL s = @selector(process_performOperation_withSequenceID:inProtocol:outProtocol:);
    NSMethodSignature * sig = [self methodSignatureForSelector: s];
    NSInvocation * invocation = [NSInvocation invocationWithMethodSignature: sig];
    [invocation setSelector: s];
    [invocation retainArguments];
    [mMethodMap setValue: invocation forKey: @"performOperation"];
  }
  return self;
}

- (id<ServiceObjectProxyService>) service
{
  return [[mService retain_stub] autorelease_stub];
}

- (BOOL) processOnInputProtocol: (id <TProtocol>) inProtocol
                 outputProtocol: (id <TProtocol>) outProtocol
{
  NSString * messageName;
  int messageType;
  int seqID;
  [inProtocol readMessageBeginReturningName: &messageName
                                       type: &messageType
                                 sequenceID: &seqID];
  NSInvocation * invocation = [mMethodMap valueForKey: messageName];
  if (invocation == nil) {
    [TProtocolUtil skipType: TType_STRUCT onProtocol: inProtocol];
    [inProtocol readMessageEnd];
    TApplicationException * x = [TApplicationException exceptionWithType: TApplicationException_UNKNOWN_METHOD reason: [NSString stringWithFormat: @"Invalid method name: '%@'", messageName]];
    [outProtocol writeMessageBeginWithName: messageName
                                      type: TMessageType_EXCEPTION
                                sequenceID: seqID];
    [x write: outProtocol];
    [outProtocol writeMessageEnd];
    [[outProtocol transport] flush];
    return YES;
  }
  // NSInvocation does not conform to NSCopying protocol
  NSInvocation * i = [NSInvocation invocationWithMethodSignature: [invocation methodSignature]];
  [i setSelector: [invocation selector]];
  [i setArgument: &seqID atIndex: 2];
  [i setArgument: &inProtocol atIndex: 3];
  [i setArgument: &outProtocol atIndex: 4];
  [i setTarget: self];
  [i invoke];
  return YES;
}

- (void) process_listServiceObjects_withSequenceID: (int32_t) seqID inProtocol: (id<TProtocol>) inProtocol outProtocol: (id<TProtocol>) outProtocol
{
  listServiceObjects_args * args = [[listServiceObjects_args alloc] init];
  [args read: inProtocol];
  [inProtocol readMessageEnd];
  ListServiceObjects_result * result = [[ListServiceObjects_result alloc] init];
  [result setSuccess: [mService listServiceObjects: [args token]]];
  [outProtocol writeMessageBeginWithName: @"listServiceObjects"
                                    type: TMessageType_REPLY
                              sequenceID: seqID];
  [result write: outProtocol];
  [outProtocol writeMessageEnd];
  [[outProtocol transport] flush];
  [result release_stub];
  [args release_stub];
}

- (void) process_getServiceObject_withSequenceID: (int32_t) seqID inProtocol: (id<TProtocol>) inProtocol outProtocol: (id<TProtocol>) outProtocol
{
  getServiceObject_args * args = [[getServiceObject_args alloc] init];
  [args read: inProtocol];
  [inProtocol readMessageEnd];
  GetServiceObject_result * result = [[GetServiceObject_result alloc] init];
  [result setSuccess: [mService getServiceObject: [args token] name: [args name] conf: [args conf]]];
  [outProtocol writeMessageBeginWithName: @"getServiceObject"
                                    type: TMessageType_REPLY
                              sequenceID: seqID];
  [result write: outProtocol];
  [outProtocol writeMessageEnd];
  [[outProtocol transport] flush];
  [result release_stub];
  [args release_stub];
}

- (void) process_performOperation_withSequenceID: (int32_t) seqID inProtocol: (id<TProtocol>) inProtocol outProtocol: (id<TProtocol>) outProtocol
{
  performOperation_args * args = [[performOperation_args alloc] init];
  [args read: inProtocol];
  [inProtocol readMessageEnd];
  PerformOperation_result * result = [[PerformOperation_result alloc] init];
  [result setSuccess: [mService performOperation: [args token] object: [args object] operationName: [args operationName] payload: [args payload]]];
  [outProtocol writeMessageBeginWithName: @"performOperation"
                                    type: TMessageType_REPLY
                              sequenceID: seqID];
  [result write: outProtocol];
  [outProtocol writeMessageEnd];
  [[outProtocol transport] flush];
  [result release_stub];
  [args release_stub];
}

- (void) dealloc
{
  [mService release_stub];
  [mMethodMap release_stub];
  [super dealloc_stub];
}

@end

