/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import <thrift/TProtocol.h>
#import <thrift/TApplicationException.h>
#import <thrift/TProtocolException.h>
#import <thrift/TProtocolUtil.h>
#import <thrift/TProcessor.h>
#import <thrift/TObjective-C.h>
#import <thrift/TBase.h>

#import "shared.h"

@interface ServiceObject : NSObject <TBase, NSCoding> {
  NSString * __name;
  NSString * __type;
  NSMutableSet * __operationNames;

  BOOL __name_isset;
  BOOL __type_isset;
  BOOL __operationNames_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=name, setter=setName:) NSString * name;
@property (nonatomic, retain, getter=type, setter=setType:) NSString * type;
@property (nonatomic, retain, getter=operationNames, setter=setOperationNames:) NSMutableSet * operationNames;
#endif

- (id) init;
- (id) initWithName: (NSString *) name type: (NSString *) type operationNames: (NSMutableSet *) operationNames;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) name;
- (void) setName: (NSString *) name;
#endif
- (BOOL) nameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) type;
- (void) setType: (NSString *) type;
#endif
- (BOOL) typeIsSet;

#if !__has_feature(objc_arc)
- (NSMutableSet *) operationNames;
- (void) setOperationNames: (NSMutableSet *) operationNames;
#endif
- (BOOL) operationNamesIsSet;

@end

@interface ServiceObjectOperationPayload : NSObject <TBase, NSCoding> {
  NSString * __content;
  NSString * __contentType;
  NSString * __rootElement;

  BOOL __content_isset;
  BOOL __contentType_isset;
  BOOL __rootElement_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=content, setter=setContent:) NSString * content;
@property (nonatomic, retain, getter=contentType, setter=setContentType:) NSString * contentType;
@property (nonatomic, retain, getter=rootElement, setter=setRootElement:) NSString * rootElement;
#endif

- (id) init;
- (id) initWithContent: (NSString *) content contentType: (NSString *) contentType rootElement: (NSString *) rootElement;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) content;
- (void) setContent: (NSString *) content;
#endif
- (BOOL) contentIsSet;

#if !__has_feature(objc_arc)
- (NSString *) contentType;
- (void) setContentType: (NSString *) contentType;
#endif
- (BOOL) contentTypeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) rootElement;
- (void) setRootElement: (NSString *) rootElement;
#endif
- (BOOL) rootElementIsSet;

@end

@interface ServiceObjectNotFoundError : NSException <TBase, NSCoding> {
  NSString * __serviceObjectName;

  BOOL __serviceObjectName_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=serviceObjectName, setter=setServiceObjectName:) NSString * serviceObjectName;
#endif

- (id) init;
- (id) initWithServiceObjectName: (NSString *) serviceObjectName;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) serviceObjectName;
- (void) setServiceObjectName: (NSString *) serviceObjectName;
#endif
- (BOOL) serviceObjectNameIsSet;

@end

@interface ServiceObjectConfigurationError : NSException <TBase, NSCoding> {
  NSString * __serviceObjectName;
  NSMutableDictionary * __errorMessages;

  BOOL __serviceObjectName_isset;
  BOOL __errorMessages_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=serviceObjectName, setter=setServiceObjectName:) NSString * serviceObjectName;
@property (nonatomic, retain, getter=errorMessages, setter=setErrorMessages:) NSMutableDictionary * errorMessages;
#endif

- (id) init;
- (id) initWithServiceObjectName: (NSString *) serviceObjectName errorMessages: (NSMutableDictionary *) errorMessages;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) serviceObjectName;
- (void) setServiceObjectName: (NSString *) serviceObjectName;
#endif
- (BOOL) serviceObjectNameIsSet;

#if !__has_feature(objc_arc)
- (NSMutableDictionary *) errorMessages;
- (void) setErrorMessages: (NSMutableDictionary *) errorMessages;
#endif
- (BOOL) errorMessagesIsSet;

@end

@interface ServiceObjectOperationFailedError : NSException <TBase, NSCoding> {
  NSString * __serviceObjectName;
  NSString * __operationName;
  NSString * __message;

  BOOL __serviceObjectName_isset;
  BOOL __operationName_isset;
  BOOL __message_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=serviceObjectName, setter=setServiceObjectName:) NSString * serviceObjectName;
@property (nonatomic, retain, getter=operationName, setter=setOperationName:) NSString * operationName;
@property (nonatomic, retain, getter=message, setter=setMessage:) NSString * message;
#endif

- (id) init;
- (id) initWithServiceObjectName: (NSString *) serviceObjectName operationName: (NSString *) operationName message: (NSString *) message;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) serviceObjectName;
- (void) setServiceObjectName: (NSString *) serviceObjectName;
#endif
- (BOOL) serviceObjectNameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) operationName;
- (void) setOperationName: (NSString *) operationName;
#endif
- (BOOL) operationNameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) message;
- (void) setMessage: (NSString *) message;
#endif
- (BOOL) messageIsSet;

@end

@protocol ServiceObjectProxyService <NSObject>
- (NSMutableSet *) listServiceObjects: (AuthenticationToken *) token;  // throws TException
- (ServiceObject *) getServiceObject: (AuthenticationToken *) token name: (NSString *) name conf: (NSMutableDictionary *) conf;  // throws ServiceObjectNotFoundError *, ServiceObjectConfigurationError *, TException
- (ServiceObjectOperationPayload *) performOperation: (AuthenticationToken *) token object: (ServiceObject *) object operationName: (NSString *) operationName payload: (ServiceObjectOperationPayload *) payload;  // throws ServiceObjectOperationFailedError *, TException
@end

@interface ServiceObjectProxyServiceClient : NSObject <ServiceObjectProxyService> {
  id <TProtocol> inProtocol;
  id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface ServiceObjectProxyServiceProcessor : NSObject <TProcessor> {
  id <ServiceObjectProxyService> mService;
  NSDictionary * mMethodMap;
}
- (id) initWithServiceObjectProxyService: (id <ServiceObjectProxyService>) service;
- (id<ServiceObjectProxyService>) service;
@end

@interface serviceobjConstants : NSObject {
}
@end
