/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import <thrift/TProtocol.h>
#import <thrift/TApplicationException.h>
#import <thrift/TProtocolException.h>
#import <thrift/TProtocolUtil.h>
#import <thrift/TProcessor.h>
#import <thrift/TObjective-C.h>
#import <thrift/TBase.h>


@interface File : NSObject <TBase, NSCoding> {
  NSString * __path;
  NSString * __hash;
  int64_t __size;
  NSString * __contentType;

  BOOL __path_isset;
  BOOL __hash_isset;
  BOOL __size_isset;
  BOOL __contentType_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=path, setter=setPath:) NSString * path;
@property (nonatomic, retain, getter=hash, setter=setHash:) NSString * hash;
@property (nonatomic, getter=size, setter=setSize:) int64_t size;
@property (nonatomic, retain, getter=contentType, setter=setContentType:) NSString * contentType;
#endif

- (id) init;
- (id) initWithPath: (NSString *) path hash: (NSString *) hash size: (int64_t) size contentType: (NSString *) contentType;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) path;
- (void) setPath: (NSString *) path;
#endif
- (BOOL) pathIsSet;

#if !__has_feature(objc_arc)
- (NSString *) hash;
- (void) setHash: (NSString *) hash;
#endif
- (BOOL) hashIsSet;

#if !__has_feature(objc_arc)
- (int64_t) size;
- (void) setSize: (int64_t) size;
#endif
- (BOOL) sizeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) contentType;
- (void) setContentType: (NSString *) contentType;
#endif
- (BOOL) contentTypeIsSet;

@end

@interface Profile : NSObject <TBase, NSCoding> {
  NSString * __hash;
  NSMutableSet * __files;
  NSMutableDictionary * __preferences;

  BOOL __hash_isset;
  BOOL __files_isset;
  BOOL __preferences_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=hash, setter=setHash:) NSString * hash;
@property (nonatomic, retain, getter=files, setter=setFiles:) NSMutableSet * files;
@property (nonatomic, retain, getter=preferences, setter=setPreferences:) NSMutableDictionary * preferences;
#endif

- (id) init;
- (id) initWithHash: (NSString *) hash files: (NSMutableSet *) files preferences: (NSMutableDictionary *) preferences;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) hash;
- (void) setHash: (NSString *) hash;
#endif
- (BOOL) hashIsSet;

#if !__has_feature(objc_arc)
- (NSMutableSet *) files;
- (void) setFiles: (NSMutableSet *) files;
#endif
- (BOOL) filesIsSet;

#if !__has_feature(objc_arc)
- (NSMutableDictionary *) preferences;
- (void) setPreferences: (NSMutableDictionary *) preferences;
#endif
- (BOOL) preferencesIsSet;

@end

@interface AuthenticationToken : NSObject <TBase, NSCoding> {
  NSString * __uniqueValue;
  NSString * __companyId;
  int64_t __authenticationTime;
  int64_t __expirationTime;
  NSString * __userPrincipal;

  BOOL __uniqueValue_isset;
  BOOL __companyId_isset;
  BOOL __authenticationTime_isset;
  BOOL __expirationTime_isset;
  BOOL __userPrincipal_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=uniqueValue, setter=setUniqueValue:) NSString * uniqueValue;
@property (nonatomic, retain, getter=companyId, setter=setCompanyId:) NSString * companyId;
@property (nonatomic, getter=authenticationTime, setter=setAuthenticationTime:) int64_t authenticationTime;
@property (nonatomic, getter=expirationTime, setter=setExpirationTime:) int64_t expirationTime;
@property (nonatomic, retain, getter=userPrincipal, setter=setUserPrincipal:) NSString * userPrincipal;
#endif

- (id) init;
- (id) initWithUniqueValue: (NSString *) uniqueValue companyId: (NSString *) companyId authenticationTime: (int64_t) authenticationTime expirationTime: (int64_t) expirationTime userPrincipal: (NSString *) userPrincipal;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) uniqueValue;
- (void) setUniqueValue: (NSString *) uniqueValue;
#endif
- (BOOL) uniqueValueIsSet;

#if !__has_feature(objc_arc)
- (NSString *) companyId;
- (void) setCompanyId: (NSString *) companyId;
#endif
- (BOOL) companyIdIsSet;

#if !__has_feature(objc_arc)
- (int64_t) authenticationTime;
- (void) setAuthenticationTime: (int64_t) authenticationTime;
#endif
- (BOOL) authenticationTimeIsSet;

#if !__has_feature(objc_arc)
- (int64_t) expirationTime;
- (void) setExpirationTime: (int64_t) expirationTime;
#endif
- (BOOL) expirationTimeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) userPrincipal;
- (void) setUserPrincipal: (NSString *) userPrincipal;
#endif
- (BOOL) userPrincipalIsSet;

@end

@interface sharedConstants : NSObject {
}
@end
