/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "shared.h"

@implementation File

- (id) init
{
  self = [super init];
#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
#endif
  return self;
}

- (id) initWithPath: (NSString *) path hash: (NSString *) hash size: (int64_t) size contentType: (NSString *) contentType
{
  self = [super init];
  __path = [path retain_stub];
  __path_isset = YES;
  __hash = [hash retain_stub];
  __hash_isset = YES;
  __size = size;
  __size_isset = YES;
  __contentType = [contentType retain_stub];
  __contentType_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"path"])
  {
    __path = [[decoder decodeObjectForKey: @"path"] retain_stub];
    __path_isset = YES;
  }
  if ([decoder containsValueForKey: @"hash"])
  {
    __hash = [[decoder decodeObjectForKey: @"hash"] retain_stub];
    __hash_isset = YES;
  }
  if ([decoder containsValueForKey: @"size"])
  {
    __size = [decoder decodeInt64ForKey: @"size"];
    __size_isset = YES;
  }
  if ([decoder containsValueForKey: @"contentType"])
  {
    __contentType = [[decoder decodeObjectForKey: @"contentType"] retain_stub];
    __contentType_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__path_isset)
  {
    [encoder encodeObject: __path forKey: @"path"];
  }
  if (__hash_isset)
  {
    [encoder encodeObject: __hash forKey: @"hash"];
  }
  if (__size_isset)
  {
    [encoder encodeInt64: __size forKey: @"size"];
  }
  if (__contentType_isset)
  {
    [encoder encodeObject: __contentType forKey: @"contentType"];
  }
}

- (void) dealloc
{
  [__path release_stub];
  [__hash release_stub];
  [__contentType release_stub];
  [super dealloc_stub];
}

- (NSString *) path {
  return [[__path retain_stub] autorelease_stub];
}

- (void) setPath: (NSString *) path {
  [path retain_stub];
  [__path release_stub];
  __path = path;
  __path_isset = YES;
}

- (BOOL) pathIsSet {
  return __path_isset;
}

- (void) unsetPath {
  [__path release_stub];
  __path = nil;
  __path_isset = NO;
}

- (NSString *) hash {
  return [[__hash retain_stub] autorelease_stub];
}

- (void) setHash: (NSString *) hash {
  [hash retain_stub];
  [__hash release_stub];
  __hash = hash;
  __hash_isset = YES;
}

- (BOOL) hashIsSet {
  return __hash_isset;
}

- (void) unsetHash {
  [__hash release_stub];
  __hash = nil;
  __hash_isset = NO;
}

- (int64_t) size {
  return __size;
}

- (void) setSize: (int64_t) size {
  __size = size;
  __size_isset = YES;
}

- (BOOL) sizeIsSet {
  return __size_isset;
}

- (void) unsetSize {
  __size_isset = NO;
}

- (NSString *) contentType {
  return [[__contentType retain_stub] autorelease_stub];
}

- (void) setContentType: (NSString *) contentType {
  [contentType retain_stub];
  [__contentType release_stub];
  __contentType = contentType;
  __contentType_isset = YES;
}

- (BOOL) contentTypeIsSet {
  return __contentType_isset;
}

- (void) unsetContentType {
  [__contentType release_stub];
  __contentType = nil;
  __contentType_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setPath: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setHash: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 3:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setSize: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 4:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setContentType: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"File"];
  if (__path_isset) {
    if (__path != nil) {
      [outProtocol writeFieldBeginWithName: @"path" type: TType_STRING fieldID: 1];
      [outProtocol writeString: __path];
      [outProtocol writeFieldEnd];
    }
  }
  if (__hash_isset) {
    if (__hash != nil) {
      [outProtocol writeFieldBeginWithName: @"hash" type: TType_STRING fieldID: 2];
      [outProtocol writeString: __hash];
      [outProtocol writeFieldEnd];
    }
  }
  if (__size_isset) {
    [outProtocol writeFieldBeginWithName: @"size" type: TType_I64 fieldID: 3];
    [outProtocol writeI64: __size];
    [outProtocol writeFieldEnd];
  }
  if (__contentType_isset) {
    if (__contentType != nil) {
      [outProtocol writeFieldBeginWithName: @"contentType" type: TType_STRING fieldID: 4];
      [outProtocol writeString: __contentType];
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (void) validate {
  // check for required fields
  if (!__path_isset) {
    @throw [TProtocolException exceptionWithName: @"TProtocolException"
                               reason: @"Required field 'path' is not set."];
  }
  if (!__hash_isset) {
    @throw [TProtocolException exceptionWithName: @"TProtocolException"
                               reason: @"Required field 'hash' is not set."];
  }
  if (!__size_isset) {
    @throw [TProtocolException exceptionWithName: @"TProtocolException"
                               reason: @"Required field 'size' is not set."];
  }
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"File("];
  [ms appendString: @"path:"];
  [ms appendFormat: @"\"%@\"", __path];
  [ms appendString: @",hash:"];
  [ms appendFormat: @"\"%@\"", __hash];
  [ms appendString: @",size:"];
  [ms appendFormat: @"%qi", __size];
  [ms appendString: @",contentType:"];
  [ms appendFormat: @"\"%@\"", __contentType];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@implementation Profile

- (id) init
{
  self = [super init];
#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
#endif
  return self;
}

- (id) initWithHash: (NSString *) hash files: (NSMutableSet *) files preferences: (NSMutableDictionary *) preferences
{
  self = [super init];
  __hash = [hash retain_stub];
  __hash_isset = YES;
  __files = [files retain_stub];
  __files_isset = YES;
  __preferences = [preferences retain_stub];
  __preferences_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"hash"])
  {
    __hash = [[decoder decodeObjectForKey: @"hash"] retain_stub];
    __hash_isset = YES;
  }
  if ([decoder containsValueForKey: @"files"])
  {
    __files = [[decoder decodeObjectForKey: @"files"] retain_stub];
    __files_isset = YES;
  }
  if ([decoder containsValueForKey: @"preferences"])
  {
    __preferences = [[decoder decodeObjectForKey: @"preferences"] retain_stub];
    __preferences_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__hash_isset)
  {
    [encoder encodeObject: __hash forKey: @"hash"];
  }
  if (__files_isset)
  {
    [encoder encodeObject: __files forKey: @"files"];
  }
  if (__preferences_isset)
  {
    [encoder encodeObject: __preferences forKey: @"preferences"];
  }
}

- (void) dealloc
{
  [__hash release_stub];
  [__files release_stub];
  [__preferences release_stub];
  [super dealloc_stub];
}

- (NSString *) hash {
  return [[__hash retain_stub] autorelease_stub];
}

- (void) setHash: (NSString *) hash {
  [hash retain_stub];
  [__hash release_stub];
  __hash = hash;
  __hash_isset = YES;
}

- (BOOL) hashIsSet {
  return __hash_isset;
}

- (void) unsetHash {
  [__hash release_stub];
  __hash = nil;
  __hash_isset = NO;
}

- (NSMutableSet *) files {
  return [[__files retain_stub] autorelease_stub];
}

- (void) setFiles: (NSMutableSet *) files {
  [files retain_stub];
  [__files release_stub];
  __files = files;
  __files_isset = YES;
}

- (BOOL) filesIsSet {
  return __files_isset;
}

- (void) unsetFiles {
  [__files release_stub];
  __files = nil;
  __files_isset = NO;
}

- (NSMutableDictionary *) preferences {
  return [[__preferences retain_stub] autorelease_stub];
}

- (void) setPreferences: (NSMutableDictionary *) preferences {
  [preferences retain_stub];
  [__preferences release_stub];
  __preferences = preferences;
  __preferences_isset = YES;
}

- (BOOL) preferencesIsSet {
  return __preferences_isset;
}

- (void) unsetPreferences {
  [__preferences release_stub];
  __preferences = nil;
  __preferences_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setHash: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_SET) {
          int _size0;
          [inProtocol readSetBeginReturningElementType: NULL size: &_size0];
          NSMutableSet * fieldValue = [[NSMutableSet alloc] initWithCapacity: _size0];
          int _i1;
          for (_i1 = 0; _i1 < _size0; ++_i1)
          {
            File *_elem2 = [[File alloc] init];
            [_elem2 read: inProtocol];
            [fieldValue addObject: _elem2];
            [_elem2 release_stub];
          }
          [inProtocol readSetEnd];
          [self setFiles: fieldValue];
          [fieldValue release_stub];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 3:
        if (fieldType == TType_MAP) {
          int _size3;
          [inProtocol readMapBeginReturningKeyType: NULL valueType: NULL size: &_size3];
          NSMutableDictionary * fieldValue = [[NSMutableDictionary alloc] initWithCapacity: _size3];
          int _i4;
          for (_i4 = 0; _i4 < _size3; ++_i4)
          {
            NSString * _key5 = [inProtocol readString];
            NSString * _val6 = [inProtocol readString];
            [fieldValue setObject: _val6 forKey: _key5];
          }
          [inProtocol readMapEnd];
          [self setPreferences: fieldValue];
          [fieldValue release_stub];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"Profile"];
  if (__hash_isset) {
    if (__hash != nil) {
      [outProtocol writeFieldBeginWithName: @"hash" type: TType_STRING fieldID: 1];
      [outProtocol writeString: __hash];
      [outProtocol writeFieldEnd];
    }
  }
  if (__files_isset) {
    if (__files != nil) {
      [outProtocol writeFieldBeginWithName: @"files" type: TType_SET fieldID: 2];
      {
        [outProtocol writeSetBeginWithElementType: TType_STRUCT size: [__files count]];
        NSEnumerator * _iter7 = [__files objectEnumerator];
        id obj8;
        while ((obj8 = [_iter7 nextObject]))
        {
          [obj8 write: outProtocol];
        }
        [outProtocol writeSetEnd];
      }
      [outProtocol writeFieldEnd];
    }
  }
  if (__preferences_isset) {
    if (__preferences != nil) {
      [outProtocol writeFieldBeginWithName: @"preferences" type: TType_MAP fieldID: 3];
      {
        [outProtocol writeMapBeginWithKeyType: TType_STRING valueType: TType_STRING size: [__preferences count]];
        NSEnumerator * _iter9 = [__preferences keyEnumerator];
        id key10;
        while ((key10 = [_iter9 nextObject]))
        {
          [outProtocol writeString: key10];
          [outProtocol writeString: [__preferences objectForKey: key10]];
        }
        [outProtocol writeMapEnd];
      }
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (void) validate {
  // check for required fields
  if (!__hash_isset) {
    @throw [TProtocolException exceptionWithName: @"TProtocolException"
                               reason: @"Required field 'hash' is not set."];
  }
  if (!__files_isset) {
    @throw [TProtocolException exceptionWithName: @"TProtocolException"
                               reason: @"Required field 'files' is not set."];
  }
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"Profile("];
  [ms appendString: @"hash:"];
  [ms appendFormat: @"\"%@\"", __hash];
  [ms appendString: @",files:"];
  [ms appendFormat: @"%@", __files];
  [ms appendString: @",preferences:"];
  [ms appendFormat: @"%@", __preferences];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@implementation AuthenticationToken

- (id) init
{
  self = [super init];
#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
#endif
  return self;
}

- (id) initWithUniqueValue: (NSString *) uniqueValue companyId: (NSString *) companyId authenticationTime: (int64_t) authenticationTime expirationTime: (int64_t) expirationTime userPrincipal: (NSString *) userPrincipal
{
  self = [super init];
  __uniqueValue = [uniqueValue retain_stub];
  __uniqueValue_isset = YES;
  __companyId = [companyId retain_stub];
  __companyId_isset = YES;
  __authenticationTime = authenticationTime;
  __authenticationTime_isset = YES;
  __expirationTime = expirationTime;
  __expirationTime_isset = YES;
  __userPrincipal = [userPrincipal retain_stub];
  __userPrincipal_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"uniqueValue"])
  {
    __uniqueValue = [[decoder decodeObjectForKey: @"uniqueValue"] retain_stub];
    __uniqueValue_isset = YES;
  }
  if ([decoder containsValueForKey: @"companyId"])
  {
    __companyId = [[decoder decodeObjectForKey: @"companyId"] retain_stub];
    __companyId_isset = YES;
  }
  if ([decoder containsValueForKey: @"authenticationTime"])
  {
    __authenticationTime = [decoder decodeInt64ForKey: @"authenticationTime"];
    __authenticationTime_isset = YES;
  }
  if ([decoder containsValueForKey: @"expirationTime"])
  {
    __expirationTime = [decoder decodeInt64ForKey: @"expirationTime"];
    __expirationTime_isset = YES;
  }
  if ([decoder containsValueForKey: @"userPrincipal"])
  {
    __userPrincipal = [[decoder decodeObjectForKey: @"userPrincipal"] retain_stub];
    __userPrincipal_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__uniqueValue_isset)
  {
    [encoder encodeObject: __uniqueValue forKey: @"uniqueValue"];
  }
  if (__companyId_isset)
  {
    [encoder encodeObject: __companyId forKey: @"companyId"];
  }
  if (__authenticationTime_isset)
  {
    [encoder encodeInt64: __authenticationTime forKey: @"authenticationTime"];
  }
  if (__expirationTime_isset)
  {
    [encoder encodeInt64: __expirationTime forKey: @"expirationTime"];
  }
  if (__userPrincipal_isset)
  {
    [encoder encodeObject: __userPrincipal forKey: @"userPrincipal"];
  }
}

- (void) dealloc
{
  [__uniqueValue release_stub];
  [__companyId release_stub];
  [__userPrincipal release_stub];
  [super dealloc_stub];
}

- (NSString *) uniqueValue {
  return [[__uniqueValue retain_stub] autorelease_stub];
}

- (void) setUniqueValue: (NSString *) uniqueValue {
  [uniqueValue retain_stub];
  [__uniqueValue release_stub];
  __uniqueValue = uniqueValue;
  __uniqueValue_isset = YES;
}

- (BOOL) uniqueValueIsSet {
  return __uniqueValue_isset;
}

- (void) unsetUniqueValue {
  [__uniqueValue release_stub];
  __uniqueValue = nil;
  __uniqueValue_isset = NO;
}

- (NSString *) companyId {
  return [[__companyId retain_stub] autorelease_stub];
}

- (void) setCompanyId: (NSString *) companyId {
  [companyId retain_stub];
  [__companyId release_stub];
  __companyId = companyId;
  __companyId_isset = YES;
}

- (BOOL) companyIdIsSet {
  return __companyId_isset;
}

- (void) unsetCompanyId {
  [__companyId release_stub];
  __companyId = nil;
  __companyId_isset = NO;
}

- (int64_t) authenticationTime {
  return __authenticationTime;
}

- (void) setAuthenticationTime: (int64_t) authenticationTime {
  __authenticationTime = authenticationTime;
  __authenticationTime_isset = YES;
}

- (BOOL) authenticationTimeIsSet {
  return __authenticationTime_isset;
}

- (void) unsetAuthenticationTime {
  __authenticationTime_isset = NO;
}

- (int64_t) expirationTime {
  return __expirationTime;
}

- (void) setExpirationTime: (int64_t) expirationTime {
  __expirationTime = expirationTime;
  __expirationTime_isset = YES;
}

- (BOOL) expirationTimeIsSet {
  return __expirationTime_isset;
}

- (void) unsetExpirationTime {
  __expirationTime_isset = NO;
}

- (NSString *) userPrincipal {
  return [[__userPrincipal retain_stub] autorelease_stub];
}

- (void) setUserPrincipal: (NSString *) userPrincipal {
  [userPrincipal retain_stub];
  [__userPrincipal release_stub];
  __userPrincipal = userPrincipal;
  __userPrincipal_isset = YES;
}

- (BOOL) userPrincipalIsSet {
  return __userPrincipal_isset;
}

- (void) unsetUserPrincipal {
  [__userPrincipal release_stub];
  __userPrincipal = nil;
  __userPrincipal_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setUniqueValue: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setCompanyId: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 3:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setAuthenticationTime: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 4:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setExpirationTime: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 5:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setUserPrincipal: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"AuthenticationToken"];
  if (__uniqueValue_isset) {
    if (__uniqueValue != nil) {
      [outProtocol writeFieldBeginWithName: @"uniqueValue" type: TType_STRING fieldID: 1];
      [outProtocol writeString: __uniqueValue];
      [outProtocol writeFieldEnd];
    }
  }
  if (__companyId_isset) {
    if (__companyId != nil) {
      [outProtocol writeFieldBeginWithName: @"companyId" type: TType_STRING fieldID: 2];
      [outProtocol writeString: __companyId];
      [outProtocol writeFieldEnd];
    }
  }
  if (__authenticationTime_isset) {
    [outProtocol writeFieldBeginWithName: @"authenticationTime" type: TType_I64 fieldID: 3];
    [outProtocol writeI64: __authenticationTime];
    [outProtocol writeFieldEnd];
  }
  if (__expirationTime_isset) {
    [outProtocol writeFieldBeginWithName: @"expirationTime" type: TType_I64 fieldID: 4];
    [outProtocol writeI64: __expirationTime];
    [outProtocol writeFieldEnd];
  }
  if (__userPrincipal_isset) {
    if (__userPrincipal != nil) {
      [outProtocol writeFieldBeginWithName: @"userPrincipal" type: TType_STRING fieldID: 5];
      [outProtocol writeString: __userPrincipal];
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (void) validate {
  // check for required fields
  if (!__uniqueValue_isset) {
    @throw [TProtocolException exceptionWithName: @"TProtocolException"
                               reason: @"Required field 'uniqueValue' is not set."];
  }
  if (!__companyId_isset) {
    @throw [TProtocolException exceptionWithName: @"TProtocolException"
                               reason: @"Required field 'companyId' is not set."];
  }
  if (!__authenticationTime_isset) {
    @throw [TProtocolException exceptionWithName: @"TProtocolException"
                               reason: @"Required field 'authenticationTime' is not set."];
  }
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"AuthenticationToken("];
  [ms appendString: @"uniqueValue:"];
  [ms appendFormat: @"\"%@\"", __uniqueValue];
  [ms appendString: @",companyId:"];
  [ms appendFormat: @"\"%@\"", __companyId];
  [ms appendString: @",authenticationTime:"];
  [ms appendFormat: @"%qi", __authenticationTime];
  [ms appendString: @",expirationTime:"];
  [ms appendFormat: @"%qi", __expirationTime];
  [ms appendString: @",userPrincipal:"];
  [ms appendFormat: @"\"%@\"", __userPrincipal];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end


@implementation sharedConstants
+ (void) initialize {
}
@end

