<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>tr.com.eno.livo</groupId>
        <artifactId>livo-parent</artifactId>
        <version>1.0.0</version>
    </parent>
    <artifactId>thrift-proc-notification</artifactId>
    <packaging>jar</packaging>
    <dependencies>
        <dependency>
            <groupId>tr.com.eno.livo</groupId>
            <artifactId>thrift-shared</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.datastax.cassandra</groupId>
            <artifactId>cassandra-driver-core</artifactId>
            <version>2.1.7</version>
        </dependency>
        <dependency>
            <groupId>tr.com.eno.livo</groupId>
            <artifactId>notification-spi</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>tr.com.eno.livo</groupId>
            <artifactId>authentication-spi</artifactId>
            <version>1.0.0</version>
        </dependency>
    </dependencies>
        <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>2.3</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <artifactSet>
                                <includes>
                                    <include>com.datastax.cassandra:cassandra-driver-core</include>
                                    <include>com.datastax.cassandra:cassandra-driver-mapping</include>
                                    <include>com.codahale.metrics:metrics-core</include>
                                </includes>
                            </artifactSet>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

        </plugins>
    </build>
</project>