<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>tr.com.eno.livo</groupId>
    <artifactId>livo-parent</artifactId>
    <version>1.0.0</version>
  </parent>
  <groupId>tr.com.eno.livo</groupId>
  <artifactId>management-jmx</artifactId>
  <version>1.0.0</version>
  <name>management-jmx</name>
  <url>http://maven.apache.org</url>
  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>
  <dependencies>
    <dependency>
      <groupId>org.osgi</groupId>
      <artifactId>org.osgi.core</artifactId>
      <version>4.3.1</version>
    </dependency>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>application-spi</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>analytics-spi</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>mail-spi</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>users-spi</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>tr.com.eno.livo</groupId>
      <artifactId>notification-spi</artifactId>
      <version>1.0.0</version>
    </dependency>
    <dependency>
      <groupId>tr.com.eno.livo</groupId>
      <artifactId>configurationadmin-proxy</artifactId>
      <version>1.0.0</version>
    </dependency>
  </dependencies>
</project>
