<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>tr.com.eno.livo</groupId>
    <artifactId>livo-parent</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <project.build.sourceVersion>1.7</project.build.sourceVersion>
        <project.build.targetVersion>1.7</project.build.targetVersion>
        <aspectj.version>1.8.5</aspectj.version>
        <metrics.version>3.1.2</metrics.version>
    </properties>
    <repositories>
        <repository>
            <id>com.springsource.repository.bundles.release</id>
            <name>SpringSource Enterprise Bundle Repository - SpringSource Bundle Releases</name>
            <url>http://repository.springsource.com/maven/bundles/release</url>
        </repository>

        <repository>
            <id>com.springsource.repository.bundles.external</id>
            <name>SpringSource Enterprise Bundle Repository - External Bundle Releases</name>
            <url>http://repository.springsource.com/maven/bundles/external</url>
        </repository>
    </repositories>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>aspects-shared</artifactId>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.7.7</version>
        </dependency>
        <dependency>
            <groupId>org.aspectj</groupId>
            <artifactId>aspectjrt</artifactId>
            <version>${aspectj.version}</version>
        </dependency>
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>6.8.13</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.4</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <version>1.10.19</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.7.12</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.2</version>
                    <configuration>
                        <source>${project.build.sourceVersion}</source>
                        <target>${project.build.targetVersion}</target>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>aspectj-maven-plugin</artifactId>
                    <version>1.7</version>
                    <configuration>
                        <XaddSerialVersionUID>true</XaddSerialVersionUID>
                        <XnotReweavable>true</XnotReweavable>
                        <complianceLevel>${project.build.targetVersion}</complianceLevel>
                        <aspectLibraries>
                            <aspectLibrary>
                                <groupId>${project.groupId}</groupId>
                                <artifactId>aspects-shared</artifactId>
                            </aspectLibrary>
                        </aspectLibraries>
                    </configuration>
                    <executions>
                        <execution>
                            <id>compile-aspectj</id>
                            <goals>
                                <goal>compile</goal>
                            </goals>
                        </execution>
                        <execution>
                            <id>testcompile-aspectj</id>
                            <goals>
                                <goal>test-compile</goal>
                            </goals>
                        </execution>
                    </executions>
                    <dependencies>
                        <dependency>
                            <groupId>org.aspectj</groupId>
                            <artifactId>aspectjrt</artifactId>
                            <version>${aspectj.version}</version>
                        </dependency>
                        <dependency>
                            <groupId>org.aspectj</groupId>
                            <artifactId>aspectjtools</artifactId>
                            <version>${aspectj.version}</version>
                        </dependency>
                    </dependencies>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-jar-plugin</artifactId>
                    <version>2.2</version>
                    <configuration>
                        <archive>
                            <manifestFile>${project.build.outputDirectory}/META-INF/MANIFEST.MF</manifestFile>
                            <addMavenDescriptor>false</addMavenDescriptor>
                        </archive>
                        <resources>
                            <resource>
                                <directory>src/main/resources/OSGI-INF</directory>
                                <includes>
                                    <include>**</include>
                                </includes>
                            </resource>
                        </resources>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>2.18.1</version>
                    <configuration>
                        <systemPropertyVariables>
                            <org.slf4j.simpleLogger.defaultLogLevel>debug</org.slf4j.simpleLogger.defaultLogLevel>
                        </systemPropertyVariables>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>cassandra-maven-plugin</artifactId>
                    <version>2.0.0-1</version>
                    <!--                    <configuration>
                        <skip>true</skip>
                    </configuration>-->
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
    <profiles>
        <profile>
            <id>all</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <build>
                <pluginManagement>
                    <plugins>
                        <plugin>
                            <groupId>org.codehaus.mojo</groupId>
                            <artifactId>cassandra-maven-plugin</artifactId>
                            <version>2.0.0-1</version>
                            <configuration>
                                <skip>true</skip>
                            </configuration>
                        </plugin>
                        <plugin>
                            <artifactId>maven-failsafe-plugin</artifactId>
                            <version>2.18.1</version>
                            <configuration>
                                <skipITs>true</skipITs>
                            </configuration>
                        </plugin>
                    </plugins>
                </pluginManagement>
            </build>
            <modules>
                <module>analytics-spi</module>
                <module>analytics-cassandra</module>
                <module>application-spi</module>
                <module>application-cassandra</module>
                <module>authentication-cassandra</module>
                <module>authentication-dummy</module>
                <module>authentication-spi</module>
                <module>authentication-ldap</module>
                <module>cassandra-shared</module>
                <module>filetransfer-spi</module>
                <module>filetransfer-disk</module>
                <module>provision-spi</module>
                <module>provision-properties</module>
                <module>serviceobjects-spi</module>
                <module>serviceobjects-monitor-spi</module>
                <module>serviceobjects-calc</module>
                <module>serviceobjects-sapservice</module>
                <module>serviceobjects-ws</module>
                <module>serviceobjects-rest</module>
                <!--<module>serviceobjects-scm-manager</module>-->
                <module>thrift-proc-authc</module>
                <module>thrift-proc-analytics</module>
                <module>thrift-proc-filetransfer</module>
                <module>thrift-proc-provision</module>
                <module>thrift-proc-serviceobjects</module>
                <module>thrift-server</module>
                <module>thrift-shared</module>
                <module>users-spi</module>
                <module>users-cassandra</module>
                <module>mail-spi</module>
                <module>mail-sender</module>
                <module>metrics-shared</module>
                <module>web-ui</module>
                <module>aspects-shared</module>
                <module>management-jmx</module>
                <module>distribution</module>
                <module>notification-spi</module>
                <module>thrift-proc-notification</module>
                <module>notification-registration-cassandra</module>
                <module>notification-push-android</module>
                <module>notification-push-combiner</module>
                <module>configurationadmin-proxy</module>
            </modules>
        </profile>
        <profile>
            <id>all-except-web</id>
            <build>
                <pluginManagement>
                    <plugins>
                        <plugin>
                            <groupId>org.codehaus.mojo</groupId>
                            <artifactId>cassandra-maven-plugin</artifactId>
                            <version>2.0.0-1</version>
                            <configuration>
                                <skip>true</skip>
                            </configuration>
                        </plugin>
                        <plugin>
                            <artifactId>maven-failsafe-plugin</artifactId>
                            <version>2.18.1</version>
                            <configuration>
                                <skipITs>true</skipITs>
                            </configuration>
                        </plugin>
                    </plugins>
                </pluginManagement>
            </build>
            <modules>
                <module>analytics-spi</module>
                <module>analytics-cassandra</module>
                <module>application-spi</module>
                <module>application-cassandra</module>
                <module>authentication-cassandra</module>
                <module>authentication-dummy</module>
                <module>authentication-spi</module>
                <module>authentication-ldap</module>
                <module>cassandra-shared</module>
                <module>filetransfer-spi</module>
                <module>filetransfer-disk</module>
                <module>provision-spi</module>
                <module>provision-properties</module>
                <module>serviceobjects-spi</module>
                <module>serviceobjects-monitor-spi</module>
                <module>serviceobjects-calc</module>
                <module>serviceobjects-sapservice</module>
                <module>serviceobjects-ws</module>
                <module>serviceobjects-rest</module>
                <!--<module>serviceobjects-scm-manager</module>-->
                <module>thrift-proc-authc</module>
                <module>thrift-proc-analytics</module>
                <module>thrift-proc-filetransfer</module>
                <module>thrift-proc-provision</module>
                <module>thrift-proc-serviceobjects</module>
                <module>thrift-server</module>
                <module>thrift-shared</module>
                <module>users-spi</module>
                <module>users-cassandra</module>
                <module>mail-spi</module>
                <module>mail-sender</module>
                <module>metrics-shared</module>
                <module>aspects-shared</module>
                <module>management-jmx</module>
                <module>distribution</module>
                <module>notification-spi</module>
                <module>thrift-proc-notification</module>
                <module>notification-registration-cassandra</module>
                <module>notification-push-android</module>
                <module>notification-push-combiner</module>
                <module>configurationadmin-proxy</module>
            </modules>
        </profile>
        <profile>
            <id>integration-test</id>
            <build>
                <pluginManagement>
                    <plugins>
                        <plugin>
                            <groupId>org.codehaus.mojo</groupId>
                            <artifactId>cassandra-maven-plugin</artifactId>
                            <version>2.0.0-1</version>
                            <configuration>
                                <skip>false</skip>
                            </configuration>
                        </plugin>
                        <plugin>
                            <groupId>org.codehaus.mojo</groupId>
                            <artifactId>aspectj-maven-plugin</artifactId>
                            <version>1.7</version>
                            <configuration>
                                <skip>true</skip>
                            </configuration>
                        </plugin>
                    </plugins>
                </pluginManagement>
            </build>
            <modules>
                <module>analytics-spi</module>
                <module>analytics-cassandra</module>
                <module>application-spi</module>
                <module>application-cassandra</module>
                <module>authentication-cassandra</module>
                <module>authentication-dummy</module>
                <module>authentication-spi</module>
                <module>authentication-ldap</module>
                <module>cassandra-shared</module>
                <module>filetransfer-spi</module>
                <module>filetransfer-disk</module>
                <module>provision-spi</module>
                <module>provision-properties</module>
                <module>serviceobjects-spi</module>
                <module>serviceobjects-monitor-spi</module>
                <module>serviceobjects-calc</module>
                <module>serviceobjects-sapservice</module>
                <module>serviceobjects-ws</module>
                <module>serviceobjects-rest</module>
                <!--<module>serviceobjects-scm-manager</module>-->
                <module>thrift-proc-authc</module>
                <module>thrift-proc-analytics</module>
                <module>thrift-proc-filetransfer</module>
                <module>thrift-proc-provision</module>
                <module>thrift-proc-serviceobjects</module>
                <module>thrift-server</module>
                <module>thrift-shared</module>
                <module>users-spi</module>
                <module>users-cassandra</module>
                <module>mail-spi</module>
                <module>mail-sender</module>
                <module>metrics-shared</module>
                <module>aspects-shared</module>
                <module>management-jmx</module>
                <module>distribution</module>
                <module>notification-spi</module>
                <module>thrift-proc-notification</module>
                <module>notification-registration-cassandra</module>
                <module>notification-push-android</module>
                <module>notification-push-combiner</module>
                <module>configurationadmin-proxy</module>
            </modules>
        </profile>
    </profiles>
  <modules>
    <module>notification-push-ios</module>
  </modules>
</project>