# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

#
# Framework config properties.
#

# To override the packages the framework exports by default from the
# class path, set this variable.
#org.osgi.framework.system.packages=

# To append packages to the default set of exported system packages,
# set this value.
org.osgi.framework.system.packages.extra=\
    javax.*, \
    javax.activation, \
    javax.annotation, \
    javax.json, \
    javax.mail, \
    javax.mail.internet, \
    javax.management, \
    javax.management.modelmbean, \
    javax.naming, \
    javax.net, \
    javax.net.ssl, \
    javax.servlet, \
    javax.tools, \
    javax.xml, \
    javax.xml.bind, \
    javax.xml.bind.annotation, \
    javax.xml.bind.attachment, \
    javax.xml.stream.events, \
    javax.xml.namespace, \
    javax.xml.parsers, \
    javax.xml.soap, \
    javax.xml.stream, \
    javax.xml.transform, \
    javax.xml.transform.dom, \
    javax.xml.transform.sax, \
    javax.xml.transform.stax, \
    javax.xml.transform.stream, \
    javax.xml.ws, \
    javax.xml.ws.handler, \
    javax.xml.ws.soap, \
    javax.xml.ws.wsaddressing, \
    javax.ws.rs, \
    javax.ws.rs.core, \
    javax.ws.rs.ext, \
    org.xml.sax, \
    org.w3c.dom, \
    com.sun, \
    com.sun.xml.internal.ws.api.message, \
    com.sun.tools.internal.xjc.api, \
    sun.misc

# The following property makes specified packages from the class path
# available to all bundles. You should avoid using this property.
#org.osgi.framework.bootdelegation=sun.*,com.sun.*

# Felix tries to guess when to implicitly boot delegate in certain
# situations to ease integration without outside code. This feature
# is enabled by default, uncomment the following line to disable it.
#felix.bootdelegation.implicit=false

# The following property explicitly specifies the location of the bundle
# cache, which defaults to "felix-cache" in the current working directory.
# If this value is not absolute, then the felix.cache.rootdir controls
# how the absolute location is calculated. (See next property)
#org.osgi.framework.storage=${felix.cache.rootdir}/felix-cache

# The following property is used to convert a relative bundle cache
# location into an absolute one by specifying the root to prepend to
# the relative cache path. The default for this property is the
# current working directory.
#felix.cache.rootdir=${user.dir}

# The following property controls whether the bundle cache is flushed
# the first time the framework is initialized. Possible values are
# "none" and "onFirstInit"; the default is "none".
org.osgi.framework.storage.clean=onFirstInit

# The following property determines which actions are performed when
# processing the auto-deploy directory. It is a comma-delimited list of
# the following values: 'install', 'start', 'update', and 'uninstall'.
# An undefined or blank value is equivalent to disabling auto-deploy
# processing.
felix.auto.deploy.action=start

# The following property specifies the directory to use as the bundle
# auto-deploy directory; the default is 'bundle' in the working directory.
felix.auto.deploy.dir=modules

# The following property is a space-delimited list of bundle URLs
# to install when the framework starts. The ending numerical component
# is the target start level. Any number of these properties may be
# specified for different start levels.

# The following property is a space-delimited list of bundle URLs
# to install and start when the framework starts. The ending numerical
# component is the target start level. Any number of these properties
# may be specified for different start levels.
felix.auto.start.1=file:modules/org.apache.felix.log-1.0.1.jar \
    file:modules/org.apache.felix.configadmin-1.8.0.jar \
    file:modules/org.apache.felix.fileinstall-3.5.0.jar \
    file:modules/org.apache.felix.metatype-1.0.10.jar \
    file:modules/org.apache.felix.scr-1.6.2.jar \
    file:modules/org.apache.felix.eventadmin-1.4.2.jar \
    file:modules/org.apache.felix.shell-1.4.3.jar \
    file:modules/org.apache.felix.shell.tui-1.4.1.jar

felix.auto.start.2=file:modules/org.apache.servicemix.bundles.aspectj-1.8.5_1.jar \
    file:modules/slf4j-api-1.7.7.jar \
    file:modules/logback-core-${logback.version}.jar \
    file:modules/logback-classic-${logback.version}.jar \
    file:modules/libthrift-0.9.1.jar \
    file:modules/commons-codec-1.9.jar \
    file:modules/commons-collections-3.2.1.jar \
    file:modules/commons-io-2.4.jar \
    file:modules/commons-lang-2.6.jar \
    file:modules/commons-lang3-3.4.jar \
    file:modules/derby-shared.jar \
    file:modules/guava-18.0.jar \
    file:modules/com.springsource.javax.wsdl-1.6.1.jar \
    file:modules/stax2-api-3.1.4.jar \
    file:modules/woodstox-core-asl-4.4.1.jar \
    file:modules/javax.json-1.0.4.jar \
    file:modules/mail.jar \
    file:modules/unboundid-ldapsdk-2.3.8.jar \
    file:modules/metrics-core-3.0.2.jar \
    file:modules/netty-common-${netty.version}.jar \
    file:modules/netty-codec-${netty.version}.jar \
    file:modules/netty-handler-${netty.version}.jar \
    file:modules/netty-transport-${netty.version}.jar \
    file:modules/netty-buffer-${netty.version}.jar \
    file:modules/cassandra-driver-core-2.1.7.jar \
    file:modules/jackson-core-${jackson.version}.jar \
    file:modules/jackson-databind-${jackson.version}.jar \
    file:modules/jackson-annotations-${jackson.version}.jar

felix.auto.start.3=file:modules/authentication-spi.jar \
    file:modules/provision-spi.jar \
    file:modules/filetransfer-spi.jar \
    file:modules/analytics-spi.jar \
    file:modules/application-spi.jar \
    file:modules/serviceobjects-spi.jar \
    file:modules/users-spi.jar \
    file:modules/notification-spi.jar \
    file:modules/mail-spi.jar \
    file:modules/metrics-shared.jar \
    file:modules/aspects-shared.jar

felix.auto.start.4=file:modules/thrift-shared.jar \
    file:modules/thrift-proc-authc.jar \
    file:modules/thrift-proc-analytics.jar \
    file:modules/thrift-proc-provision.jar \
    file:modules/thrift-proc-filetransfer.jar \
    file:modules/thrift-proc-serviceobjects.jar \
    file:modules/thrift-proc-notification.jar \
    file:modules/thrift-server.jar \
    file:modules/cassandra-shared.jar

felix.auto.start.5=file:modules/management-jmx.jar


felix.auto.start.6=file:modules/management-jmx.jar \
    file:modules/authentication-dummy.jar \
    file:modules/authentication-ldap.jar \
    file:modules/authentication-cassandra.jar \
    file:modules/analytics-cassandra.jar \
    file:modules/application-cassandra.jar \
    file:modules/users-cassandra.jar \
    file:modules/provision-properties.jar \
    file:modules/filetransfer-disk.jar \
    file:modules/serviceobjects-calc.jar \
    file:modules/serviceobjects-rest.jar \
    file:modules/serviceobjects-ws.jar \
    file:modules/serviceobjects-sapservice.jar \
    file:modules/mail-sender.jar \
    file:modules/notification-push-android.jar \
    file:modules/notification-push-combiner.jar \
    file:modules/notification-registration-cassandra.jar \
    file:modules/configurationadmin-proxy.jar

felix.log.level=1

# Sets the initial start level of the framework upon startup.
org.osgi.framework.startlevel.beginning=6

# Sets the start level of newly installed bundles.
#felix.startlevel.bundle=1

# Felix installs a stream and content handler factories by default,
# uncomment the following line to not install them.
#felix.service.urlhandlers=false

# The launcher registers a shutdown hook to cleanly stop the framework
# by default, uncomment the following line to disable it.
#felix.shutdown.hook=false

#
# Bundle config properties.
#
ds.loglevel=4

#
# Event Admin
#
org.apache.felix.eventadmin.Timeout=0
