#
# Dummy Authentication
#
dummyAuthentication.companyAuthenticationEnabled=true
dummyAuthentication.userAuthenticationEnabled=false

#
# Logback
#
logback.configurationFile=conf/logback.xml

#
# File Install
#
felix.fileinstall.filter=.*\\.cfg
felix.fileinstall.bundles.new.start=false
