<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>tr.com.eno.livo</groupId>
        <artifactId>livo-parent</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>distribution</artifactId>

    <packaging>pom</packaging>
    
    <properties>
        <jackson.version>2.6.3</jackson.version>
        <netty.version>4.0.30.Final</netty.version>
        <logback.version>1.1.2</logback.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>tr.com.eno.livo</groupId>
            <artifactId>analytics-spi</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>tr.com.eno.livo</groupId>
            <artifactId>application-spi</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>tr.com.eno.livo</groupId>
            <artifactId>application-cassandra</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>tr.com.eno.livo</groupId>
            <artifactId>authentication-spi</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>tr.com.eno.livo</groupId>
            <artifactId>authentication-dummy</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>tr.com.eno.livo</groupId>
            <artifactId>filetransfer-spi</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>tr.com.eno.livo</groupId>
            <artifactId>filetransfer-disk</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>tr.com.eno.livo</groupId>
            <artifactId>provision-spi</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>tr.com.eno.livo</groupId>
            <artifactId>provision-properties</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>tr.com.eno.livo</groupId>
            <artifactId>serviceobjects-spi</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>tr.com.eno.livo</groupId>
            <artifactId>serviceobjects-calc</artifactId>
            <version>1.0.0</version>
        </dependency>
        <!--		<dependency>
                <groupId>tr.com.eno.livo</groupId>
                <artifactId>serviceobjects-scm-manager</artifactId>
                <version>1.0.0</version>
        </dependency>-->
        <dependency>
            <groupId>tr.com.eno.livo</groupId>
            <artifactId>serviceobjects-sapservice</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>tr.com.eno.livo</groupId>
            <artifactId>thrift-shared</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>tr.com.eno.livo</groupId>
            <artifactId>thrift-proc-authc</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>tr.com.eno.livo</groupId>
            <artifactId>thrift-proc-filetransfer</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>tr.com.eno.livo</groupId>
            <artifactId>thrift-proc-provision</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>tr.com.eno.livo</groupId>
            <artifactId>thrift-proc-serviceobjects</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>tr.com.eno.livo</groupId>
            <artifactId>thrift-server</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>tr.com.eno.livo</groupId>
            <artifactId>cassandra-shared</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>tr.com.eno.livo</groupId>
            <artifactId>mail-spi</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>tr.com.eno.livo</groupId>
            <artifactId>mail-sender</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>tr.com.eno.livo</groupId>
            <artifactId>notification-spi</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>tr.com.eno.livo</groupId>
            <artifactId>notification-push-android</artifactId>
            <version>1.0.0</version>
        </dependency>
        
        <dependency>
            <groupId>tr.com.eno.livo</groupId>
            <artifactId>notification-push-combiner</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>tr.com.eno.livo</groupId>
            <artifactId>notification-registration-cassandra</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.felix</groupId>
            <artifactId>org.apache.felix.log</artifactId>
            <version>1.0.1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.felix</groupId>
            <artifactId>org.apache.felix.configadmin</artifactId>
            <version>1.8.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.felix</groupId>
            <artifactId>org.apache.felix.metatype</artifactId>
            <version>1.0.10</version>
        </dependency>
        <dependency>
            <groupId>org.apache.felix</groupId>
            <artifactId>org.apache.felix.scr</artifactId>
            <version>1.6.2</version>
        </dependency>
        <dependency>
            <groupId>org.apache.felix</groupId>
            <artifactId>org.apache.felix.eventadmin</artifactId>
            <version>1.4.2</version>
        </dependency>
        <dependency>
            <groupId>org.apache.felix</groupId>
            <artifactId>org.apache.felix.shell</artifactId>
            <version>1.4.3</version>
        </dependency>
        <dependency>
            <groupId>org.apache.felix</groupId>
            <artifactId>org.apache.felix.shell.tui</artifactId>
            <version>1.4.1</version>
        </dependency>
        <dependency>
            <groupId>commons-codec</groupId>
            <artifactId>commons-codec</artifactId>
            <version>1.9</version>
        </dependency>
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>2.4</version>
        </dependency>
        <dependency>
            <groupId>commons-collections</groupId>
            <artifactId>commons-collections</artifactId>
            <version>3.2.1</version>
        </dependency>
        <dependency>
            <groupId>commons-lang</groupId>
            <artifactId>commons-lang</artifactId>
            <version>2.6</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.7.7</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.7.7</version>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>${logback.version}</version>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-core</artifactId>
            <version>${logback.version}</version>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>18.0</version>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>thrift-proc-analytics</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>tr.com.eno.livo</groupId>
            <artifactId>thrift-proc-notification</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.felix</groupId>
            <artifactId>org.apache.felix.fileinstall</artifactId>
            <version>3.5.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.4</version>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>management-jmx</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.servicemix.bundles</groupId>
            <artifactId>org.apache.servicemix.bundles.aspectj</artifactId>
            <version>1.8.5_1</version>
        </dependency>
        <dependency>
            <groupId>javax.wsdl</groupId>
            <artifactId>com.springsource.javax.wsdl</artifactId>
            <version>1.6.1</version>
        </dependency>
        
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>${jackson.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>${jackson.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>${jackson.version}</version>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>serviceobjects-rest</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.livomobile.server</groupId>
            <artifactId>metrics-shared</artifactId>
            <version>1.0.0</version>
                        
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>serviceobjects-ws</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>aspects-shared</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>configurationadmin-proxy</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.unboundid</groupId>
            <artifactId>unboundid-ldapsdk</artifactId>
            <version>2.3.8</version>
        </dependency>
        <dependency>
            <groupId>com.datastax.cassandra</groupId>
            <artifactId>cassandra-driver-core</artifactId>
            <version>2.1.7</version>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>authentication-cassandra</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.codahale.metrics</groupId>
            <artifactId>metrics-core</artifactId>
            <version>3.0.2</version>
        </dependency>
        <dependency>
            <groupId>com.livomobile.server</groupId>
            <artifactId>metrics-shared</artifactId>
            <version>1.0.0</version>
        </dependency>
        
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-transport</artifactId>
            <version>${netty.version}</version>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-buffer</artifactId>
            <version>${netty.version}</version>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-common</artifactId>
            <version>${netty.version}</version>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-codec</artifactId>
            <version>${netty.version}</version>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-handler</artifactId>
            <version>${netty.version}</version>
        </dependency>
        <dependency>
            <groupId>org.codehaus.woodstox</groupId>
            <artifactId>woodstox-core-asl</artifactId>
            <version>4.4.1</version>
        </dependency>
        <dependency>
            <groupId>org.codehaus.woodstox</groupId>
            <artifactId>stax2-api</artifactId>
            <version>3.1.4</version>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>users-spi</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>users-cassandra</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>


    <build>
        <plugins>
            <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>2.4.1</version>
                <executions>
                    <execution>
                        <id>distro-assembly</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                        <configuration>
                            <descriptors>
                                <descriptor>src/main/assembly/bin.xml</descriptor>
                            </descriptors>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
    <profiles>
        <profile>
            <id>platform-windows</id>
            <activation>
                <os>
                    <family>windows</family>
                </os>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <version>1.3.2</version>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>exec</goal>
                                </goals>
                            </execution>
                        </executions>
                        <configuration>
                            <workingDirectory>${project.build.directory}/distribution-1.0.0-bin/</workingDirectory>
                            <environmentVariables>
                                <AEON_HOME>${project.build.directory}/livo-data</AEON_HOME>
                            </environmentVariables>
                            <executable>start.bat</executable>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>platform-unix</id>
            <activation>
                <os>
                    <family>unix</family>
                </os>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <version>1.3.2</version>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>exec</goal>
                                </goals>
                            </execution>
                        </executions>
                        <configuration>
                            <workingDirectory>${project.build.directory}/distribution-1.0.0-bin/</workingDirectory>
                            <environmentVariables>
                                <AEON_HOME>${project.build.directory}/livo-data</AEON_HOME>
                            </environmentVariables>
                            <executable>./start.sh</executable>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
